ChainSafe/gossamer

Makefile, go.mod
**Changes made in this pull request:**
- added Makefile with the following commands:
- **make help**: this will outline all possible commands within makefile
- **make lint** : this uses `gometalinter` and will `go get` the package if it's not present
- **make test** : this will run the `go test ./...` command
- **make install** : this will install dependencies
- **make clean** : this will clean build cache
Since we don't have any go files present, these will return an error.
The rationale for the makefile is to be able to use common commands with general ease. Moving forward the Makefile will be primarily used for different builds much like its used in `go-ethereum`.
[Here](https://azer.bike/journal/a-good-makefile-for-go/) is a good link for an overview of a makefile in go
=> added makefile

p2p/bootstrap_test.go
The original `TestStringsToPeerInfos` test was not calling `stringsToPeerInfos` but rather calling `stringToPeerInfo`
- Fixed `stringsToPeerInfos` test
- 
- 
```
go test ./p2p -run TestStringsToPeerInfos -v 
```
=> Fixed p2p TestStringsToPeerInfos test

trie/node.go, trie/node_test.go
- as @amerameen pointed out, the partial key length is not limited to 317 but to 2^16
- update function to conform to spec, now errors if len(pk) > 2^16
- also update some comments
```
go test ./trie/
```
=> trie pk encoding fix

trie/database_test.go, trie/node.go, trie/node_test.go, trie/trie_test.go
- this improvement came to me at 6am this morning when I was half awake
- to prevent duplicate keys being randomly generated we store the previous keys created in that test in a mapping
- previously it was just a list which was slow, tests run quite a bit faster now
```
go test ./trie/
```
=> trie: improve generation of random tests

common/common.go, common/common_test.go, trie/codec.go, trie/codec_test.go
- as pointed out by @drskalman the KeyEncode function wasn't used in the trie package
- ended up using keyToNibbles to split the key into nibbles
- as such I've moved KeyEncode to the common package and renamed it SwapNibbles as I feel that's more descriptive of what it does
```
go test ./common/ ./trie/
```
=> move keyEncode to common and rename to swapNibbles

trie/trie_test.go
- change min key length in random tests to 2
- i think there was a bug with duplicate keys still being created due to converting the byte array into a string then checking if it was created or not, looked like keys of length <2 were still being duplicated
```
go test ./trie/
```
=> trie: fix tests

runtime/wasmer_test.go
- change url for test wasm blob to reference specific commit to prevent version issues
```
go test ./runtime/...
```
=> 🌬️ runtime: change test blob url to reference specific commit

Makefile, consensus/babe/babe.go, consensus/babe/babe_test.go, consensus/babe/runtime.go, consensus/babe/types.go, copyright.txt, runtime/imports.go, scripts/ci.sh
I noticed some of the `babe` files were merged without a license header so I decided to add the command to the Makefile. Now we can easily add license headers to our files prior to being merged. 
- Adds the command `make license` to `Makefile` which adds license header to missing files
- Adds `copyright.txt` to repo which is our license header 
- Adds license header to missing files
- `make lint` now uses the configuration set in `.golangci.yml`
```
```
=> Update Makefile and add license headers

p2p/message.go, p2p/message_test.go
Code to handle Encoding and Decoding Block Announce Network Message. Palkadot Runtime Environment Specification section E.1.4.
- Added `BlockHeaderMessage` type
- Created `Encode` function for `BlockHeaderMessage`
- Created `Decode` function for `BlockHeaderMessage`
- Created `String` function for `BlockHeaderMessage`
- Created `TestEncodeBlockAnnounceMessage` test
- Created `TestDecodeBlockAnnounceMessage` test
```
go test -v ./p2p/...
```
closes #256
=> p2p, add Block Announce Network Message

p2p/message.go, p2p/message_test.go
Renamed `BlockHeaderMessage` to `BlockAnnounceMessage` so that it conforms to the name specified in section E.1.4 of the PRE spec.
- Renamed struct `BlockHeaderMessage` to `BlockAnnounceMessage`
- Renamed test that use BlockAnnounceMessage
- 
```
go test -v ./p2p/...
```
=> p2p, rename BlockHeaderMessage to BlockAnnounceMessage to conform to spec

.gitignore, cmd/gossamer/configcmd.go, cmd/netsim/main.go, core/service.go, core/service_test.go, dot/dot_test.go, internal/api/api.go, internal/services/services.go, internal/services/services_test.go, p2p/bootstrap_test.go, p2p/p2p.go, p2p/p2p_test.go, polkadb/database_test.go, polkadb/dbService.go, polkadb/dbService_test.go, polkadb/table_test.go
The main change here is the removal of error channels from the `Start()` and `Stop()` functions of the interface `Service` in favour of just returning errors. There seems to be no real need to return the errors through a channel, and we presently have no way of reading these errors. 
- Service return types
- dbService now creates dbs inside `Start()`
- Rename `NewDatabaseService` to `NewDbService` to match struct name
```
go test -v ./...
```
=> Services Updates

.gitignore, .travis.yml, p2p/bootstrap_test.go, p2p/config.go, p2p/p2p_test.go
- Load p2p identity key from data dir if it exists
- Bump travis Go version (project is already 1.13)
Note: Currently the data dir path cannot be set properly, implementing #347 will solve this. If you try running the node it will create the key in the current directory
```
go test ./p2p
```
=> p2p: Save ID Key

go.mod, go.sum, runtime/imports.go, runtime/wasmer_test.go
- implement ext_secp256k1_ecdsa_recover
- uses a go-ethereum library, this seems to be our best bet for a "go" implementation unless we want to use cgo
```
go test ./runtime/... -v
```
closes #274
=> runtime: ext_secp256k1_ecdsa_recover

cmd/gossamer/configcmd.go, cmd/gossamer/configcmd_test.go, config.toml, config/config.go, config/defaults.go, dot/dot_test.go, rpc/http.go
This PR introduces separate config structs for the P2P and RPC services for explicit use in CLI/config file setup.
Prior to these changes we relied on marshalling the toml config file directly to the P2P/RPC configs. This limits the possible functionality of our CLI/Config packages as it forces all exported fields to be included in the TOML file. This introduces further issues when we try to have shared/global config options as it breaks `dumpConfig`.
This unblock #349.
Note: I left the DB config unchanged as it will be removed in #349.
- Adds `RpcCfg` and `P2pCfg` types specifically for CLI/config usage
- Removes `rpc.Config` as we can just pass the params to the constructor
- Updates tests
- Regenerates example config
```
go test -v ./...
```
=> cmd,config,dot,rpc: Decouple configs

p2p/host.go
This pull request makes use of the [`SwapToP2pMultiaddrs`](https://github.com/multiformats/go-multiaddr/blob/64e34154803fd9bd07ef4c6480be117ec72e35fc/protocol.go#L53-L78) configuration method in [go-multiaddr](https://github.com/multiformats/go-multiaddr) in order to use `p2p` instead of `ipfs` when creating a new multiaddress.
```
go test ./p2p
```
closes #367
=> p2p: use p2p instead of ipfs for host multiaddress

go.sum, runtime/imports.go, runtime/wasmer.go
Previously a sync.Mutex was used in nearly all of the runtime environment `ext_...` functions. This would cause all VMs to block each other when calling those functions.
Additionally, new RuntimeCtx were added to the Registry, but there is no mechanism for their removal after the Runtime is garbage collected. This would cause a memory leak if Runtime's are created an GC'd throughout the lifetime of the program using the runtime package.
- Change sync.Mutext to sync.RWMutex and use RLock/RUnlock where appropriate.
- Add a Finalizer to clean up the registry whenever a Runtime is GC'd.
- Run `go mod tidy` to clean up go.sum
=> runtime: Use sync.RWMutex and add finalizer to clean up registry

go.sum, p2p/connmgr.go
This pull request adds `Connected` and `Disconnected` to `ConnManager`. These two methods are event handlers for the connect and disconnect events being monitored by `NotifeeBundle`.
`Connected` logs a dummy `StatusMessage` and `Disconnected` simply logs the disconnect. As noted in the issue, we can update the `StatusMessage` to use the current state once #400 has been implemented and we can handle disconnects accordingly as peer events are implemented.
```
```
closes #410
=> p2p: add connect/disconnect handlers to connection manager

cmd/gossamer/main.go
- Removes `MigrateFlags` method as it is no longer required.
```
go test -v ./cmd/....
```
=> Remove CLI Flag Migration

cmd/gossamer/configcmd.go, core/service.go, core/service_test.go, p2p/message.go, p2p/p2p.go, p2p/p2p_test.go
This pull request updates the remaining message channel value types to `Message` and updates all message channels named `msgChan`, `sendChan`, and `recChan` to `msgSend` and `msgRec`.
This pull request also updates how transaction messages are processed in the core service, which previously did not support multiple extrinsics.
```
go test ./...
```
=> cmd, core, p2p: update message channel types

cmd/gossamer/configcmd_test.go
- previously was pulling the test_wasm blob but we actually wanted the substrate_test_runtime blob
- updated path
```
go test ./...
```
closes #430
=> cmd: fix test blob

crypto/ed25519.go, crypto/keypair.go, crypto/sr25519.go, keystore/keystore.go, runtime/imports.go, runtime/wasmer.go, runtime/wasmer_test.go
- implement ext_ed25519_public_keys, ext_sr25519_public_keys, ext_ed25519_sign, ext_sr25519_sign
- implement functions to get public keys/keypairs from keystore
- add constants to crypto package for pubkey length, privkey length, seed length, signature length
```
go test ./crypto/ ./runtime/
```
closes #281 closes #279
=> crypto, runtime: ext_ public keys, sign

cmd/gossamer/configcmd.go, consensus/babe/babe.go, consensus/babe/babe_test.go, consensus/babe/runtime.go, consensus/babe/types.go, core/service.go, core/service_test.go
- cleanup core and babe a bit, have their constructors take a config struct instead of a bunch of params. will make it easier to update config options in the future, rather than having to update function args everywhere
- add keystore to core/babe
- replace babe key stubs with key types
```
go test ./...
```
=> cmd, core, consensus/babe: add configs for core.Service, babe.Session, add keystore

runtime/imports.go, runtime/wasmer_test.go
- Added scale encoding to key values (index values) in
ext_blake2_256_enumerated_trie_root so that root hash matches expected
values. (test values from rust code
https://github.com/paritytech/substrate/blob/6e242a5a9fcc5d5ea34386864ec064a01677efff/client/executor/src/integration_tests/mod.rs#L419)
```
cd runtime/
go test -v -run TestExt_blake2_256_enumerated_trie_root
```
closes #379
=> runtime: scale encode key values in enumerated_trie_root

go.mod, go.sum, runtime/allocator/allocator_test.go, runtime/imports.go, runtime/wasmer.go
The latest version of github.com/wasmerio/go-ext-wasm now includes the
InstanceContext.Data registry that was initially built into the runtime.
This commit removes the runtime's registry which simplifies the code.
- Update `github.com/wasmerio/go-ext-wasm` to latest in `go.mod`, run `go mod tidy`
- Remove all references to the `registry` and `mutex`.
- Update usage of `InstanceContext.Data()` to use a type assertion on the returned interface.
The tests are failing but with the same errors as can be observed on the current development branch. These fails appear to just be related to some unimplemented host functions.
```
$ go test ./runtime/...
t=2019-12-06T12:42:09-0900 lvl=dbug msg=[NewRuntime] runtimeCtx="{trie:0xc00000f280 allocator:0xc000162000 keystore:0xc00000f2a0}" …
```
=> refactor(runtime): Update wasmer & remove Registry

cmd/gossamer/configcmd.go, cmd/gossamer/configcmd_test.go, consensus/babe/babe.go, consensus/babe/babe_test.go, core/service.go, core/service_test.go, p2p/p2p_test.go
This pull request adds functionality to announce blocks from the BABE session and to process block announce messages from the p2p service.
We needed to create a new channel in order to send messages to the p2p service, which means we had to rename the channels.
```
go test ./core -v
```
closes #346
=> core: process block announce message

internal/api/api.go, internal/api/api_test.go, internal/api/modules/p2p_module.go, internal/api/modules/runtime_module.go, p2p/p2p.go, p2p/utils.go, rpc/modules/system.go, rpc/modules/system_test.go, state/network.go, state/network_test.go, state/service.go
This pull request updates the public p2p service methods to align with information needed for the rpc server. This pull request also updates the network state in preparation for migrating the rpc server from using the api service to using the state service (see #488).
The information needed for the rpc server is up-to-date host and peer information that can be made available though public p2p service methods (`Health()`, `NetworkState()` and `Peers()`). Following the implementation of the status module, we do not need to store a separate peer state (see #399).
```
go test ./...
```
closes #399 and opens #488
=> api, p2p, rpc, state: network information

cmd/gossamer/genesis.go
- Checks for datadir flag in when loading the genesis file
Closes #454
=> cmd: Genesis Init Failure Fix

p2p/gossip.go, p2p/host.go, p2p/host_test.go, p2p/message.go, p2p/service.go, p2p/service_test.go, p2p/status.go, p2p/utils.go
Use an existing stream to send messages if an existing stream is available.
See specifcation 4.4.2
> For the purposes of communicating Polkadot messages, the dailer of the connection opens a unique substream. Optionally, the node can keep a unique substream alive for this purpose.
```
go test ./p2p --run TestExistingStream -v
```
closes #437
=> p2p: send messages with existing stream

consensus/babe/babe.go, consensus/babe/babe_test.go, core/blocktree/blocktree.go, core/blocktree/blocktree_test.go, core/blocktree/node.go, core/rawdb/rawdb.go, core/rawdb/rawdb_test.go, core/types/types.go, state/block.go, state/interface.go
- remove types.BlockHeaderWithHash and types.BlockWithHash finally >:|
- add internal hash field that has a getter/setter. note we probably only want to use `Hash()` (and `GetHash()` once Hash() has been called) in most circumstances, however we need `Set()` for the blocktree.
- update other packages accordingly
```
go test ./...
```
closes #506
=> core/blocktree, core/rawdb, core/types, state: change types.BlockHeader to unexport hash field and add getter/setter

consensus/babe/babe_test.go, runtime/imports.go
This is a fix for an issue I introduced when I was doing storage refactoring.  In ext_blake2_256_enumerated_trie_root I inadvertently changed the reference for the trie to the storge trie.  But in this function we need to use a fresh trie to calculate root hash.  This fix corrects this so that a fresh trie is used.
```
cd runtime/
go test -v -run TestExt_blake2_256_enumerated_trie_root
```
=> runtime: fix enumerated trie root

cmd/gossamer/account.go, cmd/gossamer/main.go
This pull request adds the missing `secp256k1` account option to `gossamer`.
```
./build/bin/gossamer account --generate --secp256k1
```
=> cmd: add account secp256k1 flag option

trie/trie_test.go
The random number generator was producing an empty value and when that test was being  written to the failing trie tests, the empty value would cause all tests to be offset and therefore we would received a very large number of errors caused by a single generated test with an empty value.
This pull request also reduces the number of delete tests generated to `100`.
```
go test ./trie -v
```
closes #201, related to #547
=> trie: fix failing trie tests

consensus/babe/babe.go, consensus/babe/babe_test.go, core/service.go, runtime/imports.go
- add done channel between babe and core, when epoch complete, done is signalled and core creates the next epoch's babe session
- slightly modify build block logic to conform to spec (we are supposed to pass in a new header to initialize_block, not the parent header)
```
go test ./consensus/...
```
running a 1-node block producer:
```
make gossamer
./build/bin/gossamer init
./build/bin/gossamer --verbosity debug
```
closes #565
=> consensus/babe, core: initialize new babe session for each epoch

codec/decode.go, codec/decode_ptr.go, codec/decode_test.go, consensus/babe/babe.go, consensus/babe/runtime.go, core/service_test.go, p2p/message_test.go, trie/trie_test.go
- update DecodeArray to allocate a slice instead of assigning to the interface that's passed in, allows for arrays to be decoded without knowing how many elements are in it
- update DecodeTuple to handle [][]byte
```
go test ./codec/...
```
closes #584
=> scale: allocate slice elements when decoding

crypto/sr25519/sr25519.go
- NewKeypairFromSeed previously wasn't using seed, now it is
```
go test ./crypto/...
```
=> crypto/sr25519: fix NewKeypairFromSeed

cmd/gossamer/account.go, cmd/gossamer/configcmd.go, cmd/gossamer/configcmd_test.go, cmd/gossamer/flags.go, cmd/gossamer/genesis.go, cmd/gossamer/main.go, cmd/gossamer/unlock.go
This pull request update `p2pport` flag to `port` and migrates `cmd/utils/flags.go` to `cmd/flags.go`.
```
```
closes #531
=> cmd: update port flag and migrate utils

codec/decode_ptr_test.go, codec/decode_test.go
- I was occassionally getting out of memory errors when running tests due to the large byte arrays being initialized, so I moved them inside the block that's executed when not -short
```
```
=> scale: move initialization of large byte arrays

cmd/gossamer/account.go, cmd/gossamer/configcmd.go, cmd/gossamer/configcmd_test.go, cmd/gossamer/genesis.go, cmd/gossamer/genesis_test.go, dot/config.go, dot/dot.go, dot/dot_test.go, dot/network/config.go, dot/network/utils.go, node/defaults.go, node/gssmr/defaults.go, node/gssmr/genesis.json, node/ksmcc/config.toml, node/node_test.go
This pull request updates the default datadir to account for multiple node implementation.
```
./bin/gossamer init --datadir ~/.gossamer/ksmcc
```
```
./bin/gossamer --datadir ~/.gossamer/ksmcc
```
=> cmd, dot, node: use subdirectories for each node

cmd/gossamer/genesis.go, dot/core/service_test.go, dot/state/block.go, dot/state/block_race_test.go, dot/state/block_test.go, dot/state/network.go, dot/state/service.go, dot/state/storage.go, scripts/ci.sh
- update state service to use one db for block, state, and network
- update core tests accordingly
mem performance before:
```
Showing nodes accounting for 11687.57MB, 99.76% of 11715.21MB total
Dropped 84 nodes (cum <= 58.58MB)
flat  flat%   sum%        cum   cum%
0     0%     0% 11705.17MB 99.91%  testing.tRunner
0     0%     0% 11693.12MB 99.81%  github.com/ChainSafe/gossamer/lib/database.NewBadgerDB
0.50MB 0.0043% 0.0043% 11692.62MB 99.81%  github.com/dgraph-io/badger/v2.Open
0     0% 0.0043% 11233.88MB 95.89%  github.com/ChainSafe/gossamer/dot/core.newTestService
6.99MB  0.06% 0.064%  9608.99MB 82.02%  github.com/dgraph-io/ristretto.NewCache
0     0% 0.064%  9600.50MB 81.95%  github.com/dgraph-io/ristretto.newDefaultPolicy
0     0% 0.064%  9600.50MB 81.95% …
```
=> state: update state to use one db

dot/network/config_test.go, dot/network/gossip_test.go, dot/network/host_test.go, dot/network/mdns_test.go, dot/network/service_test.go, dot/network/status_test.go, dot/network/syncer_test.go, dot/network/utils_test.go, dot/state/service_test.go, lib/keystore/keystore_test.go, lib/utils/test_utils.go, lib/utils/test_utils_test.go, lib/utils/utils.go, lib/utils/utils_test.go, tests/wasmer_test_util.go
- implements the same test directory utility methods used by `dot` and `cmd`
- adds a test directory utility method that adds a directory within the test directory
```
go test lib/utils -v
```
closes #689
=> utils, network, state: add / implement test utils

dot/state/block.go, dot/state/block_test.go, dot/state/service_test.go, lib/blocktree/blocktree.go, lib/blocktree/blocktree_test.go, lib/blocktree/leaves.go
- addisBlockOnCurrentChain function to block state to check if block we are adding is on our current chain, if so, update number->hash mapping in db, otherwise don't 
- fix blocktree deepestLeaf function, wasn't correct before
```
```
closes #717
=> dot/state, lib/blocktree: set block number->hash mapping for current chain only

dot/core/service.go, lib/blocktree/blocktree.go, lib/blocktree/blocktree_test.go, lib/blocktree/database.go, lib/blocktree/database_test.go, lib/blocktree/leaves.go
- update blocktree leafMap to sync.Map to prevent concurrent writes panic
```
go test ./lib/blocktree
```
closes #730
=> lib/blocktree: update leafmap to sync.Map

dot/core/errors.go, dot/core/runtime.go, dot/core/service.go, dot/core/sync.go, lib/blocktree/blocktree.go, lib/blocktree/database.go, lib/blocktree/errors.go, lib/blocktree/node.go, lib/database/errors.go, lib/database/memoryDB.go
- use defined errors in core, blocktree, database (I just did these ones for now since these are the ones that were doing error comparisons)
```
```
partially closes #305
=> dot/core, lib/blocktree, lib/database: create error definitions

dot/core/babe.go, dot/core/babe_test.go, dot/core/digest.go, dot/core/digest_test.go, dot/core/messages.go, dot/core/messages_test.go, dot/core/runtime_test.go, dot/core/service.go, dot/core/service_test.go, dot/core/syncer.go, dot/core/syncer_test.go, dot/state/service_test.go
- determine what epoch a block was produced at with `(slot - GENESIS_SLOT) / epoch_len`
all tests should pass:
```
go test dot/core -v
```
running the gossamer node...
```
make gossamer
./bin/gossamer --key alice
```
should produce the following error related to #662:
```
EROR[03-27|10:32:22] [core] failed to verify first block error="failed to verify first block: first block never set"
```
closes #599
=> dot/core: first block in epoch and core refactor

cmd/gossamer/config.go, cmd/gossamer/config_test.go, cmd/gossamer/flags.go, dot/config.go, dot/config_test.go, dot/utils.go, node/gssmr/config.toml, node/gssmr/defaults.go, node/ksmcc/config.toml, node/ksmcc/defaults.go
- load genesis configuration values (`Name`, `ID`, `Bootnodes`, `ProtocolID`) from genesis file while setting the node configuration and overwrite configuration if configuration values do not match.
- add `name` flag for telemetry
```
go test ./cmd/gossamer
go test ./dot
```
related to #713, no longer closes - ***updated***
=> cmd, dot: overwrite config with genesis

.gitignore, cmd/gossamer/config.go, cmd/gossamer/config_test.go, cmd/gossamer/main.go, dot/node.go, dot/utils.go
- load genesis data from database if node already initialized
run tests...
```
go test ./cmd/...
```
run gossamer command...
```
make gossamer
./bin/gossamer --key alice --datadir tmp/alice --name TESTNODE --verbosity trace init
./bin/gossamer --key alice --datadir tmp/alice --name TESTNODE --verbosity trace
```
...then update name in `gssmr/genesis.config` to `ANOTHERNODE` and rerun commands.
(1) you should see a warning that the name within the genesis file and the config file do not match and the config name value is being overwritten with the genesis name value
(2) you should see that we load and update using the genesis data for an initialized node and the config is overwritten a second time using the genesis data before being passed to `NewNode`
closes #713
=> cmd, dot: load genesis data for initialized node

cmd/gossamer/main.go, cmd/gossamer/utils.go, cmd/gossamer/utils_test.go
- prompt user to confirm with `Y` when attempting to initialize an already initialized node
```
make gossamer
./bin/gossamer --datadir tmp/alice --key alice init
./bin/gossamer --datadir tmp/alice --key alice init
```
closes #760
=> cmd/gossamer: confirm reinitializing a node

dot/rpc/http_test.go, scripts/integration-test-all.sh, tests/rpc/common.go, tests/rpc/system_integration_test.go
- add test for system_networkState
- rename integration_test.go to system_integration_test.go
- refactor common test logic to common.go
- add option on integration-test-all.sh -z (Quantity of nodes to run tests against eg: 3) in order to 
- have local tests less strict asserting one node instead of 3 (default)
- update rpcmods node init param to start chain (for future tests)
```
./scripts/integration-test-all.sh -q 3 -z 1 -s 5
```
-
=> scripts, tests, rpc: add test for system_networkState

cmd/gossamer/flags.go, cmd/gossamer/flags_test.go
- fix `FixFlagOrder` to allow the formats listed below and update comment to explain use of non-global flag after the subcommand (before or after global flags or mixed between is ok)
```
make gossamer
mkdir tmp
./bin/gossamer export --config tmp/config.toml
./bin/gossamer --config tmp/config.toml export
./bin/gossamer export --config tmp/config.toml --force
./bin/gossamer export --force --config tmp/config.toml
```
The following does not work because `force` is not a global flag and, therefore, must be placed after the `export` subcommand. The help menu is appropriately displayed with global options.
```
./bin/gossamer --force --config tmp/config.toml export
./bin/gossamer --config tmp/config.toml --force export
```
- closes #782
=> cmd/gossamer: fix and update FixFlagOrder method

dot/state/block.go
- set number to hash mapping for genesis block
```
make gossamer
./bin/gossamer --key alice --rpc
```
in another terminal:
```
curl -X POST --data '{"jsonrpc":"2.0","method":"chain_getBlockHash","params":["0"],"id":1}' -H "Content-Type: application/json" http://localhost:8545
```
=> dot/state: set number to hash mapping for genesis

lib/crypto/keypair.go, lib/crypto/keypair_test.go
- fix PubkeyToAddress to conform to ss58
- add test case
- https://github.com/paritytech/substrate/wiki/External-Address-Format-(SS58) 42 is substrate wildcard
```
go test ./lib/crypto
```
- closes #845
=> lib/crypto: fix PubkeyToAddress to conform to ss58

dot/core/service.go, dot/rpc/modules/api.go, dot/rpc/modules/state.go, dot/rpc/modules/state_test.go, lib/runtime/runtime_test.go, lib/runtime/types.go
- Implement RPC call state_getMetadata which returns the runtime metadata
- The current runtime has not implemented Metadata_metadata yet, so this will handle the error that is returned.
-
```
```
-
=> dot/rpc Implement RPC call state_getMetadata 

cmd/gossamer/config.go, cmd/gossamer/config_test.go, cmd/gossamer/flags.go, dot/config.go, dot/rpc/http.go, dot/rpc/websocket_test.go, dot/services.go
- add `--wsport` flag for specifying websockets port
- add `--ws flag` for enabling/disabling ws, ws is now off by default, can be turned on with `--ws`. let me know what you guys think, if you prefer to keep it on by default as long as `--rpc` is provided
```
make gossamer
./bin/gossamer --key alice --rpc --ws
./bin/gossamer --key alice --rpc --wsport=7777 --ws
```
- closes #850
=> cmd/gossamer, dot: add --ws, --wsport flags; add tests

dot/node_test.go, dot/types/babe_test.go, lib/crypto/ed25519/ed25519.go, lib/keystore/helpers.go, lib/keystore/keyring.go, lib/keystore/keyring_test.go, lib/runtime/extrinsic/extrinsic_test.go, lib/runtime/helpers_test.go
- add Ed25519Keyring since GRANDPA uses ed25519 keys
- rename existing keyring to Sr25519Keyring
- add 9th key to keyring
```
```
- closes #873
=> lib/keystore: add Ed25519Keyring; rename existing to Sr25519Keyring

lib/blocktree/blocktree.go, lib/blocktree/blocktree_test.go, lib/blocktree/database_test.go, lib/blocktree/errors.go, lib/blocktree/node.go
- implement HighestCommonPrecessor which for blocks a, b, gets the block with the highest number that's a predecessor of both
- possibly rename to HighestCommonAncestor?? what does everyone think
```
go test ./lib/blocktree
```
- closes #878
=> lib/blocktree: implement HighestCommonAncestor

dot/core/service.go, dot/core/service_test.go, dot/rpc/modules/api.go, dot/rpc/modules/author.go, dot/rpc/modules/author_test.go, dot/rpc/service_test.go, lib/keystore/helpers.go, lib/keystore/helpers_test.go
- Implement RPC method author_hasKey see: https://github.com/w3f/PSPs/blob/psp-rpc-api/psp-002.md#author_hasKey
-
-
```
go test ./dot/rpc/... 
```
- related to #312
=> dot/rpc: Implement RPC method author_hasKey

dot/network/service.go, dot/network/service_test.go, dot/rpc/modules/api.go, dot/rpc/modules/system.go, dot/rpc/modules/system_test.go, dot/rpc/service_test.go
- Implement RPC function for system_nodeRoles see: https://github.com/w3f/PSPs/blob/psp-rpc-api/psp-002.md#system_nodeRoles
- Added function NodeRoles to network service
```
go test ./dot/network/...
```
- related to #731
=> dot/rpc, dot/network: Implement RPC system_nodeRoles 

dot/rpc/modules/state_test.go, lib/runtime/helpers_test.go
- add sort.Slice to TestStateModule_GetPairs_All to prevent failures
- add retries around calls to finalize_block in runtime tests
```
```
- closes #858
=> dot/rpc/modules, lib/runtime: fix failing tests

Makefile, cmd/gossamer/export_test.go, cmd/gossamer/flags.go, cmd/gossamer/flags_test.go, cmd/gossamer/main.go, cmd/gossamer/utils.go, cmd/gossamer/utils_test.go
- rename `verbosity` to `log`
- rename `--verbosity` to `--log`
- rename `VerbosityFlag` to `LogFlag`
- some minor cli formatting / cleanup
```
```
- related to #772 and #857
=> cmd/gossamer: rename verbosity to log

.travis.yml
- fix travis configuration warning messages (ie, `matrix`, `cleanup`, `token`)
- build site with travis using updated bundler and specific ruby environment needed for build (GitHub failed to build on second attempt because environment was not properly set up)
- then deploy to GitHub using the full `docs` directory as the `local_dir` (GitHub stalled on build the first attempt when I used `docs/_site` (only the built site directory))
- GitHub should recognize the `docs` directory as a jekyll project (it did so with the second attempt) and the `_site` directory as the built site (GitHub _should_ use the site built by travis rather than trying to build without the proper environment settings)
=> fix github pages deployment - third attempt

dot/core/service.go, dot/state/db.go, dot/state/service.go, lib/babe/build_test.go
- load latest state root instead of latest block storage root
```
make gossamer 
./bin/gossamer --key alice init
./bin/gossamer --key alice 
(stop node)
./bin/gossamer --key alice
```
- closes #920
=> fix state root loading

dot/core/interface.go, dot/state/block.go, dot/types/block.go, dot/types/block_test.go, dot/types/digest.go, dot/types/header.go, dot/types/header_test.go, lib/blocktree/blocktree_test.go, lib/common/common.go, lib/common/hash.go, lib/crypto/ed25519/ed25519.go, lib/grandpa/errors.go, lib/grandpa/grandpa.go, lib/grandpa/message.go, lib/grandpa/message_test.go, lib/grandpa/round_test.go, lib/grandpa/types.go, lib/grandpa/vote_message.go, lib/grandpa/vote_message_test.go, lib/runtime/test_helpers.go, lib/scale/decode.go, lib/scale/decode_ptr.go, lib/scale/enc_dec_test.go, lib/scale/encode.go
- implement core.FinalityGadget and core.FinalityMessage interfaces
- update grandpa service to fulfil core.FinalityGadget
- update grandpa VoteMessage and FinalizationMessage to implement core.FinalityMessage
```
```
- closes #933 closes #934
=> dot/core, lib/grandpa, lib/scale: implement FinalityGadget interface, implement ability to convert grandpa messages to network messages

lib/grandpa/grandpa.go, lib/grandpa/message.go, lib/grandpa/message_test.go, lib/grandpa/round_test.go, lib/grandpa/types.go, lib/grandpa/vote_message.go, lib/scale/decode_ptr.go, lib/scale/encode.go, lib/scale/encode_test.go
- add justification maps to grandpa for keeping track of justifications for that round
- add justifications to `FinalizationMessage`
- implement encode, decode for `Justification`
- update scale to use `EncodeCustom`
```
```
- closes #945
=> lib/grandpa, lib/scale: add justification handling to grandpa, add to FinalizationMessage

dot/state/block.go, dot/state/block_race_test.go, dot/state/block_test.go, dot/state/service.go, dot/state/storage.go
- for some reason, go doesn't allow for `chaindb.Database` to be used as `database.Database` when we alias the package as `database`. so, I got rid of the chaindb import alias in `state`
```
go test ./dot/state
```
=> dot/state: rename import database -> chaindb

dot/core/messages_test.go, dot/core/service.go, dot/core/service_test.go, dot/core/syncer.go, dot/core/test_helpers.go, dot/node.go, dot/node_test.go
- replace uint32 with atomic.Value in dot/core
- clean up dot by removing atomic usage
```
go test ./dot/...
```
- closes #893
=> dot, dot/core: use atomic.Value 

lib/runtime/imports.go
- add addition ext_ functions required here: https://github.com/w3f/polkadot-spec/tree/master/test
- they are not implemented yet, just stubbed
```
go test ./lib/runtime
```
=> lib/runtime: add ext_ functions required by host api tests

dot/core/digest.go, dot/core/digest_test.go, dot/core/errors.go, dot/core/interface.go, dot/core/service.go, dot/core/syncer.go, dot/core/test_helpers.go, dot/types/consensus_digest.go, dot/types/digest.go, lib/grandpa/grandpa.go, lib/grandpa/grandpa_test.go, lib/grandpa/message.go, lib/grandpa/message_test.go, lib/grandpa/vote_message.go, lib/grandpa/vote_message_test.go
- add digestHandler which is called when a block is imported to handle any consensus digests (see spec 5.1.2) and update grandpa authorities accordingly
- add functionality to update authority set and increment setID at end of current round
- switch setID and round in VoteMessage to conform to spec
- some testing cleanup
```
```
- closes #972
=> lib/grandpa: handle runtime-to-consensus engine digests, add ability to update authorities and setID to grandpa

dot/rpc/http.go, dot/rpc/modules/api.go, dot/rpc/websocket.go, dot/state/block.go, dot/state/block_notify.go, dot/state/block_notify_test.go, dot/state/block_test.go, dot/state/service.go, lib/grandpa/grandpa.go, lib/grandpa/message_tracker.go, lib/grandpa/message_tracker_test.go, lib/grandpa/round_test.go, lib/grandpa/state.go, lib/grandpa/vote_message_test.go
- add functionality to register/unregister notification channels for imported and finalized blocks in BlockState
- update rpc and grandpa accordingly
```
```
- closes #973
=> dot/state: implement ability to register channels for block import, finalization 

chain/gssmr/config.toml, chain/gssmr/defaults.go, chain/ksmcc/config.toml, cmd/gossamer/config.go, cmd/gossamer/config_test.go, dot/config.go, dot/core/digest.go, dot/core/digest_test.go, dot/core/errors.go, dot/core/service.go, dot/node.go, dot/node_test.go, dot/services.go, dot/services_test.go
- add BabeAuthority and GrandpaAuthority config options so that the node can run only one or the other if specified
- update default package log settings in config so that they match the `log` option instead of defaulting to `info`
```
```
also running gossamer with `authority = true` and `babe-authority = false` in the config to turn off babe, or `grandpa-authority = false` to turn off grandpa
- clsoes #979
=> cmd, dot, dot/core: add BabeAuthority and GrandpaAuthority config options

dot/core/errors.go, dot/core/finality.go, dot/core/finality_test.go, dot/core/interface.go, dot/core/service.go, dot/core/syncer.go, dot/core/test_helpers.go, dot/services.go, lib/grandpa/message.go, lib/grandpa/message_handler.go, lib/grandpa/message_handler_test.go, lib/grandpa/message_test.go
- implement grandpa message handler so that nodes that don't run grandpa can still process grandpa messages (FinalizationMessage)
- add interface to core, cleanup existing core interfaces
- initialize message handler in startup and pass to core
```
go test ./lib/grandpa ./dot/core
```
- closes #981
=> dot/core, lib/grandpa: implement MessageHandler for grandpa messages

chain/gssmr/config.toml, chain/ksmcc/config.toml, cmd/gossamer/config.go, cmd/gossamer/config_test.go, dot/config.go, dot/config_test.go, dot/services.go, dot/utils.go, lib/babe/babe.go
- add `BabeThreshold` configuration value, can be "max", "min", or nil
- set `BabeThreshold` when starting BABE service
```
go test ./...
```
also, can run gossamer with `BabeThreshold` in config set to "max", should not allow blocks to be built
- related to #854
=> cmd, dot: add BabeThreshold config option

dot/core/syncer_test.go, lib/babe/babe.go, lib/babe/babe_test.go, lib/babe/build_test.go, lib/babe/median_test.go, lib/babe/verify_test.go, tests/rpc/rpc_03-chain_test.go, tests/stress/stress_test.go, tests/utils/config_babe_max_threshold.toml, tests/utils/gossamer_utils.go
- see spec 6.2.2
- equation no longer uses authority weights, only len(authorities)
- also update lottery such that node can author block if *under* threshold (see Algorithm 6.3)
```
go test ./lib/babe/
```
-
=> lib/babe: update threshold calculation to match spec

lib/runtime/imports.go, lib/runtime/imports_old.go, lib/runtime/imports_old_test.go, lib/runtime/imports_test.go, lib/runtime/test_helpers.go
- implement ext_twox_256
```
go test ./lib/runtime
```
- related to #905
=> lib/runtime: implement ext_twox_256

dot/state/block.go, dot/state/block_test.go, lib/babe/babe.go, lib/common/db_keys.go
- add `GetRound` and `SetRound` funcs in BlockState to allow for saving latest round
- check for latest round in `GetFinalizedHash`, return empty hash if round hasn't finalized yet
- add AuthorityData type alias in BABE to allow for string formatting of authorities
```
```
-
=> dot/state: save current round to database

dot/core/messages_test.go, dot/core/service.go, dot/core/service_test.go, dot/core/syncer.go, dot/core/syncer_test.go, dot/rpc/modules/author_test.go, dot/rpc/modules/dev_test.go, dot/utils.go, lib/babe/babe.go, lib/babe/babe_test.go, lib/babe/verify.go, lib/babe/verify_test.go, lib/runtime/helpers_test.go, lib/runtime/test_helpers.go
- change `NextEpochDesciptor` in verifier to `EpochDescriptor` which contains threshold information
- use this in verification to check that block vrf output is under threshold when verifying
- remove `NextEpochDescriptor` usages since it's not used 
```
go test ./...
```
- closes #998
=> lib/babe: add threshold check to verifier

dot/core/syncer_test.go, lib/babe/babe.go, lib/babe/build.go, lib/babe/errors.go
- move check for vrf proof to handleSlot, remove from buildBlockBabeDigest
- cleanup `invokeBlockAuthoriting` by moving slot setup in `initiate` instead
```
go test ./lib/babe
```
- closes #670
=> lib/babe: move vrf proof check to handleSlot, cleanup invokeBlockAuthoring

dot/core/service.go, dot/services.go, dot/state/block.go, lib/babe/babe.go, lib/babe/babe_test.go, tests/stress/stress_test.go, tests/utils/config_nobabe.toml, tests/utils/gossamer_utils.go
- in core.NewService, set babe verifier threshold from config if set, otherwise set it using `babe.CalculateThreshold`
- update stress sync test config to set threshold to max if block producer threshold is also max
```
make gossamer
make it-stress
```
- closes #998
=> dot, dot/core: set verifier threshold from config or babe.CalculateThreshold

dot/core/syncer.go, dot/core/syncer_benchmark.go
- add `benchmarker` to syncer which keeps track of duration of each sync and how many blocks were synced and logs the average time
```
make gossamer
```
run alice as a block producer with `babe-threshold = "max"` in the config, then run bob as a non-authority node and see logs
- related to #990
=> dot/core: add benchmarker to syncer

dot/state/block.go, lib/blocktree/blocktree.go, lib/blocktree/leaves.go, lib/grandpa/grandpa.go, lib/grandpa/message_tracker.go, lib/grandpa/round_test.go, lib/grandpa/state.go
- fix grandpa SIGABRT on shutdown, was coming from call to `s.blockState.BestBlockHeader()` for some reason
- add some safety checks in block state, blocktree
- update grandpa message tracker to use select case to determine when stopped
```
```
also, `make gossamer`, `./bin/gossamer --key alice`, ctrl+c and make sure there is no SIGABRT
-
=> lib/grandpa: fix grandpa SIGABRT on shutdown

dot/config.go, dot/services.go, lib/babe/babe.go, lib/runtime/imports_old.go
- add SlotDuration option to config, check if this is set (ie. non-zero) when initializing BABE
```
make gossamer
```
add `slot-duration = 100` under `[core]` in the config, and run ` ./bin/gossamer --key alice --config chain/gssmr/config.toml ` you should see blocks being produced more quickly (can also set `babe-threshold = "max"`)
- closes #1005
=> dot, lib/babe: add SlotDuration config option

cmd/gossamer/config.go
- Added check to see if cli flag has been set, otherwise the code used toml setting.
-
-
- Create toml config file with [rpc] ws-enabled = true
- Start node with toml config file, and no cli --ws flag and confim websocket server has started.
```
```
-
=> fix: WebSocket enabled setting in toml not working

dot/rpc/modules/api.go, dot/rpc/modules/chain.go, dot/rpc/modules/dev.go, dot/rpc/websocket_test.go, tests/stress/stress_test.go, tests/utils/chain.go, tests/utils/config_babe_max_threshold_bench.toml, tests/utils/dev.go, tests/utils/gossamer_utils.go
- add sync test that randomly restarts nodes (both block producers and non-producers)
- add a test for many producers syncing, however it currently fails since nodes panic with `runtime: out of memory`. it seems like each node can't be connected to >=8 peers at once, we need to either put a cap on the # of peers a node can have or optimize the node more
```
make it-stress
```
- closes #854
=> tests: add sync test that restarts nodes

cmd/gossamer/main.go, dot/core/interface.go, dot/core/service.go, dot/core/service_test.go, dot/core/test_helpers.go, dot/node.go, dot/services.go, dot/services_test.go, lib/babe/babe.go, lib/babe/state.go, lib/babe/verify.go, lib/babe/verify_test.go
- update `VerificationManager` to track changes in verification data via block (ie. by hash, so when verifying a block, it uses the data from the most recent descendant it has)
- update `core.checkForRuntimeChanges` to notify `VerificationManager` if there is a runtime change
- update dot startup as needed
```
go test ./lib/babe ./dot/... 
```
- closes #762 closes #1023
=> dot/core, lib/babe: refactor VerificationManager to track changes by block, update verifier with runtime changes

dot/rpc/modules/api.go, dot/rpc/modules/dev.go, dot/rpc/modules/dev_test.go
- Implement development rpc endpoint `dev_setAuthorities` used to update authorities set for block producer.  The params for this endpoint is an array containing public addresses and weight in the form:
```
[
["5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY", 1],
["5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty", 1]
]
``` 
-
-
```
```
- related to #1022, still to complete handling for BABE Randomness, and BABE epoch.
=> dot/rpc: dev rpc endpoint setAuthoities

dot/core/digest.go, dot/core/digest_test.go, dot/core/interface.go, dot/core/test_helpers.go, dot/services.go, lib/babe/verify.go, lib/babe/verify_test.go
- add `SetAuthorityChangeAtBlock` to verifier
- update `digestHandler` to call verifier on authority change
- update service initialization
```
```
- closes #997
=> dot/core, lib/babe: add SetAuthorityChangeAtBlock to verifier, set change through digestHandler

dot/core/interface.go, dot/core/test_helpers.go, dot/interface.go, dot/rpc/modules/api.go, dot/rpc/modules/dev.go, dot/rpc/modules/dev_test.go, lib/babe/babe.go, lib/babe/babe_test.go
- Implemented development rpc endpoint `dev_setBABEEpochThreshold` to set Epoch Threshold value for BABE producer.
-
-
```
go test ./lib/babe/...
```
Or interact directly with rpc endpoint with call as follows:
```
{
"jsonrpc": "2.0",
"method": "dev_setBABEEpochThreshold",
"params": ["123"],
"id": 1
}
```
- closes #1022
=> lib/babe, dot/rpc Implement dev rpc endpoint dev_set BABEEpochThreshold

dot/core/digest.go, dot/core/digest_test.go, dot/node.go, dot/services.go, dot/services_test.go, lib/grandpa/errors.go, lib/grandpa/grandpa.go, lib/grandpa/grandpa_test.go, lib/grandpa/message_handler_test.go, lib/grandpa/message_test.go, lib/grandpa/round_test.go, lib/grandpa/state.go, lib/grandpa/vote_message_test.go
- add `DigestHandler` interface to grandpa 
- implement `NextGrandpaAuthorityChange` for `DigestHandler` which returns the block number of the next grandpa authority change
- update `determinePreVote` and `determinePreCommit` to use this
```
```
- closes #1054
=> lib/grandpa, dot/core: update grandpa not to vote on block higher than next scheduled authority change

dot/core/finality.go, dot/core/interface.go, dot/core/test_helpers.go, lib/grandpa/message.go, lib/grandpa/message_handler.go, lib/grandpa/message_handler_test.go
- update `grandpa.MessageHandler.HandleMessage` to return a `*ConsensusMessage` if one needs to be sent out, currently will return a `catchUpRequest` if needed
- update `core.Service.processConsensusMessage` to send out message returned from `HandleMessage` if there is one
```
```
- closes #1069
=> lib/grandpa: return catch-up request from grandpa MessageHandler.HandleMessage if needed

dot/core/interface.go, dot/core/test_helpers.go, lib/grandpa/errors.go, lib/grandpa/message.go, lib/grandpa/message_handler.go, lib/grandpa/message_handler_test.go
- implement `handleCatchUpRequest` which validates the request and returns a response if valid
- update `decodeMessage` to handle all grandpa msg types
```
```
- closes #1070
=> lib/grandpa: handle catch up requests

Makefile, dot/core/digest.go, dot/core/finality.go, dot/core/finality_test.go, dot/core/service.go, dot/core/service_test.go, dot/network/service.go, dot/node.go, lib/grandpa/grandpa.go, lib/grandpa/round_test.go, lib/grandpa/vote_message.go, scripts/ci.go, tests/stress/grandpa_test.go, tests/stress/stress_test.go, tests/utils/gossamer_utils.go
- update `core.Service`, `network.Service`, `grandpa.Service` to use `context.WithCancel` to stop goroutines
```
```
- related to #1001
=> dot/core, lib/grandpa: refactor services to use context to stop goroutines

lib/grandpa/errors.go, lib/grandpa/message_handler.go, lib/grandpa/message_handler_test.go
- added function `verifyJustification` which check given FinalizationMessage and confirms:
- Verifies signature is valid for singed FullVote.
- Authority was in the set indicated by setID
- The total number of signatures is >= 2/3 the number of voters is the list.
-
```
go test ./lib/grandpa/...
```
- closes #1051
=> lib/grandpa: verify block justification when handling FinalizationMessage

lib/grandpa/errors.go, lib/grandpa/grandpa.go, lib/grandpa/message.go, lib/grandpa/message_handler.go, lib/grandpa/message_handler_test.go
- implement `handleCatchUpResponse` for grandpa message handler which checks pre-vote and pre-commit justifications
```
go test ./lib/grandpa -short
```
- closes #1071
=> lib/grandpa: implement catch up response handling

cmd/gossamer/config.go
- added check in `setDotGlabalConfig` to confirm cfg.BasePath has been set, if not it sets it to default gossamer basepath (~/.gossamer/gssmr)
-
-
```
```
- closes #1037
=> cmd/gossamer: add check for cfg.BasePath

dot/state/block.go, dot/state/block_notify_test.go, dot/state/block_race_test.go, dot/state/block_test.go, dot/state/epoch.go, dot/state/storage.go
- replace blockDB, storageDB, epochDB with chaindb.table which adds a prefix
- update block notify tests to not stall
```
go test ./dot/state
```
- closes #1091
=> dot/state: replace blockDB, storageDB, epochDB with chaindb.table

dot/core/service.go, dot/network/service.go, dot/node.go, dot/rpc/modules/system.go, dot/rpc/modules/system_test.go, dot/services.go, dot/services_test.go, lib/common/network.go, lib/runtime/imports_old.go, lib/runtime/imports_old_test.go, lib/runtime/interface.go, lib/runtime/runtime.go, lib/runtime/test_helpers.go, tests/rpc/rpc_01-system_test.go, tests/rpc/system_integration_test.go
- Implement function `ext_network_state`
-
-
```
```
-
=> lib/runtime: implement ext_network_state

dot/state/trie.go, lib/runtime/imports.go, lib/runtime/imports_test.go, lib/runtime/interface.go, lib/runtime/test_helpers.go, lib/trie/child_storage.go
- Implement `ext_kill_child_storage` as defined in spec F.1.14
- Implement `ext_get_allocated_child_storage` as defined in spec F.1,12
- Update child storage prefix to `:child_storage:default:` as defined in spec F.1.9
```
```
-
=> lib/runtime: implement ext_kill_child_storage and ext_get_allocated_child_storage

dot/core/interface.go, dot/core/service.go, dot/core/service_test.go, dot/core/test_helpers.go
- implement `handleChainReorg` function which is called upon a block import
- it checks if there is a chain re-org and if so, validates then readds the transactions included on that chain back into the pool
```
go test ./dot/core
```
- closes #764
=> dot/core: handle chain re-orgs by re-adding transactions into pool

dot/state/trie.go, lib/runtime/imports.go, lib/runtime/imports_test.go, lib/runtime/interface.go, lib/runtime/test_helpers.go, lib/trie/child_storage.go
- implement `ext_clear_child_storage` and tests
-
-
```
```
-
=> lib/runtime: implement ext_clear_child_storage and tests

lib/runtime/allocator.go, lib/runtime/allocator_test.go, lib/runtime/runtime.go
-  update allocator to take []byte instead of *wasm.Memory, allows for more generic usage
```
go test ./lib/runtime
```
-
=> lib/runtime: update allocator to take []byte instead of *wasm.Memory

lib/common/hasher.go, lib/common/hasher_test.go, lib/runtime/wasmer/imports_old.go, lib/runtime/wasmtime/imports.go
- Fixes `Blake2b128` by passing input to the hasher
- Fixes `Keccak256` by passing input to the hasher 
- Enables all `Blake2b128` and `Keccak256` test again
- Clean up `Blake2b256` to go with other code
Now passes previously failing tests in w3f/polkadot-spec/pull/295.
- Bug was introduced in #291, 
- Part of it was fixed in #1127
- w3f/polkadot-spec#295
- closes #989
=> lib/runtime: fix Blake2b128 and Keccak256

dot/rpc/modules/chain.go, dot/rpc/modules/system.go, dot/rpc/websocket.go
- The `subscription` parameter in the JSON response in RPC subscription calls was in wrong place, so polkadot.js api was not responding to websocket messages.
-
-
```
```
- Fixes #1137
=> dot/rpc: fix rpc subscription parameter

.travis.yml
Travis doesn't expose environment data to PRs sent from a forked repo.
https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
- Disable docker for PRs sent from a forked repo.
-
=>  Disable docker for external PRs

dot/state/block.go, dot/state/service.go, dot/state/service_test.go, dot/state/storage.go, dot/state/test_helpers.go
- Start a background goroutine to GC prune keys from Storage state.
- Implement prune key API in Storage state.
- #1125
=> Remove pruned keys from Storage state.

dot/network/block_announce.go, dot/network/block_announce_test.go, dot/network/gossip.go, dot/network/host.go, dot/network/mdns.go, dot/network/message.go, dot/network/message_test.go, dot/network/service.go, dot/network/service_test.go, dot/network/status.go
- add support for `/<protocol-id>/block-announces/1` sub-protocol
- implement handling, creation of `BlockAnnounceHandshake`
- implement sending `BlockAnnounceMessage`s via notifications protocol (see https://crates.parity.io/sc_network/index.html#notifications-protocols)
```
go test ./dot/network
```
- closes #1159
=> dot/network: implement block announce protocol

.github/workflows/tests.yml, README.md, tests/stress/stress_test.go
Seems to be an issue with running [paambaati/codeclimate-action](https://github.com/paambaati/codeclimate-action/issues/275) on ubuntu-latest. This pr uses macos-latest to publish coverage to code climate and places it in its own job which is not a requirement. 
- Moves code coverage into its own job
- Uses macos-latest instead of ubuntu for code cov
- Fixes readme badge
-
```
```
- closes #1255
=> Move code coverage into own job + fix ci

.github/workflows/build.yml, .github/workflows/tests.yml
- Removes reporter ID secret 
- Moves docker build and push check to an on push development job. 
-
Rational here is that we probably do not want to push a latest docker image every pull request but rather once it has been reviewed and merged in. This eliminates the issue with docker secrets not being available to external contributors. Lastly, since the `reporter-id` is just for code coverage I don't see an issue having it within the file itself. 
```
```
-
=> Update CI to have docker-push run on dev branch only

cmd/gossamer/config.go
This patch parses the `[init]` section of the supplied config when the node is started normally, so it is no longer overridden by the default.
Test scenario is running the node with a config that sets a custom genesis file (without calling `gossamer init...` with it first).
Before the patch:
```
INFO[01-05|22:36:26] loading default configuration...         pkg=cmd id=gssmr caller=config.go:88
INFO[01-05|22:36:26] loading toml configuration...            pkg=cmd config path=/home/florian/Projects/Web3/polkadot-spec-tests/test/helpers/../runtimes/tester/gossamer.config.toml caller=config.go:48
WARN[01-05|22:36:26] overwriting default configuration with toml configuration values pkg=cmd id=gssmr config path=/home/florian/Projects/Web3/polkadot-spec-tests/test/helpers/../runtimes/tester/gossam …
```
=> config: always parse init section

lib/runtime/wasmer/imports.go
- Unify used log level (debug, like substrate) for `ext_print_..._version_1` functions
- Log unknown log level as error for `ext_logging_log_version_1`
- Cleanup code to be more DRY
Calling host api tested with custom runtime
No issues, just some cleanup to simplify our testsuite.
=> wasmer: cleanup misc print and logging log

lib/common/hasher.go, lib/runtime/wasmer/imports.go, lib/runtime/wasmer/imports_test.go
- implement ext_hashing_sha2_256_version_1
```
go test ./lib/runtime/wasmer -run Test_ext_hashing_sha2_256_version_1
```
- #1105
=> lib/runtime: implement ext_hashing_sha2_256_version_1

tests/utils/dev.go
- This fixes issue that caused TestSync_MultipleEpoch to fail.
-
-
```
make it-stress
```
-
=> add decodeRPC to SlotDuration and EpochLength

lib/common/optional/types.go, lib/runtime/wasmer/imports.go, lib/runtime/wasmer/imports_test.go
- update `ext_storage_read` to return correct optional
```
go test ./lib/runtime/wasmer
```
- closes #1105
=> lib/runtime: fix ext_storage_read

dot/network/block_announce.go, dot/network/connmgr.go, dot/network/connmgr_test.go, dot/network/service.go, dot/network/service_test.go, dot/network/sync.go, go.sum
Added protected peers functionality and prevent syncing peers from pruning when the maximum amount of connecting peers is exceeded.
- Updated `ConnManager` so it can protect and unprotect peers
- Updated `ConnManager` so it will not prune protected peers
- Updated `Service` so it will use the `ConnManager` to flag and unflag syncing peers.
```
```
- Add test that checks if peers are flagged protected from the `Service`
- closes #1275
=> Added protected peers functionality

dot/rpc/modules/chain.go
- Update RPC chain_getBlock to return encoded extrinsics (was previously sending raw extrinsics). Polkadot.js expects extrinsics to be scale encoded, which is why it was complaining.
-
-
```
```
- fixes #1315
=> [dot/rpc] use encoded extrinsics in RPC getBlock

tests/polkadotjs_test/package.json, tests/polkadotjs_test/test.js
- This adds Node.js javascript test script for testing polkadot.js/api.  It calls polkadot.js/api functions and displays output to console.
-
-
Install polkadot.js/api package (assuming you already have node.js and npm installed).
```
cd tests/polkadotjs_test/
npm install
```
Start building blocks with gossamer node.  Then run script (from within tests/polkadotjs_test/).
```
node test.js
```
Observe the console output for results or errors.
- closes: #1198
=> script to test polkadot.js/api functions

dot/sync/syncer_test.go, lib/runtime/storage/trie.go, lib/trie/trie.go, lib/trie/trie_test.go
- fix `ClearPrefix` and `GetKeysWithPrefix`, now `ClearPrefix` creates a correctly structured trie after clearing
kusama block 595 can sync now :)
```
go test ./lib/trie
```
=> lib/trie: fix ClearPrefix again

chain/ksmcc/genesis-raw.json, dot/build_spec.go, dot/rpc/websocket.go, dot/state/db.go, dot/system/service.go, go.mod, lib/genesis/genesis.go, lib/runtime/wasmer/exports.go
- update chain type in ksmcc genesis
- fix getting version for kusama
- load/store genesis properties from db
- (all of these help polkadot.js ui to work)
```
./bin/gossamer --key alice --config chain/gssmr/config.toml --basepath /tmp/goss_dev --rpc --ws 
```
open https://polkadot.js.org/apps/#/explorer , navigate to development -> custom endpoint -> `ws://localhost:8546` 
- closes #1248 
- closes #865
- related to #1366
=> fixes for polkadot.js UI

lib/blocktree/blocktree.go
- low hanging fruit type optimization based on some profiling, improves sync speed when blocktree is large
- when we add a block to the blocktree it's most likely adding it to a leaf of the tree, so check the leaves first in `getNode`
- previously was searching from the genesis or root node, very slow when tree is large 
- improved sync speed at block ~480k from 4blocks/s to 10blocks/s on my machine
```
go test ./lib/blocktree
```
=> lib/blocktree: update blocktree.getNode to check leaves first

dot/network/sync.go, dot/node.go, dot/services.go, dot/services_test.go, lib/keystore/keystore.go, lib/runtime/types.go, lib/runtime/wasmer/imports.go, lib/runtime/wasmer/imports_test.go, lib/runtime/wasmer/legacy_imports.go, lib/runtime/wasmer/legacy_imports_test.go, lib/runtime/wasmer/test_helpers.go, lib/runtime/wasmtime/legacy_imports.go, lib/runtime/wasmtime/test_helpers.go
- update runtime to use `GlobalKeystore`
- update ext_crypto funcs accordingly to use `id` parameter
```
```
- closes #1279
=> lib/runtime: use GlobalKeystore

dot/network/connmgr.go, dot/network/host.go, dot/network/service.go, dot/network/sync.go, dot/state/block.go, dot/state/block_data_test.go, dot/state/service.go, dot/sync/interface.go, dot/sync/message_test.go, dot/sync/syncer.go, dot/sync/syncer_test.go, lib/blocktree/blocktree.go, lib/blocktree/blocktree_test.go, lib/blocktree/database_test.go
- handle justifications provided in block responses by setting latest finalized hash (will use grandpa to verify justification in a follow-up PR, wanted to get this in first since it allows the blocktree to be pruned, improving sync times)
- on node restart, if there was an "abnormal shutdown" ie the blocktree wasn't stored properly because the node panicked or was killed forcefully, then restore the state from the latest finalized hash
- update logging to log blocks imported every 5s (if you liked the previous logs, you can turn on `sync` package debug logs):
```
INFO[03-02|03:10:06] 🔨 finalized block                     pkg=sync number=1094832 hash=0xb7d4a3c8a51dd5e189c2aec82dffec97f91f2f09ce1736878aa985ec108eb41f caller=syncer.go:353
INFO[03-02|03:10:11] 🔗 imported blocks …
```
=> dot/sync: handle block response justification 

lib/runtime/version.go, lib/runtime/version_test.go, lib/runtime/wasmer/exports_test.go, lib/runtime/wasmer/imports.go
- fix `ext_misc_runtime_version_version_1` to return the correct encoding of the `runtime.Version`
- fixes execution of kusama block 901442
```
go test ./lib/runtime/wasmer -run TestInstance_ExecuteBlock_KusamaRuntime_KusamaBlock901442
```
- realted to #1134
=> lib/runtime: fix execution of kusama block 901442

lib/common/optional/types.go, lib/runtime/life/instance.go, lib/runtime/wasmer/imports.go, lib/runtime/wasmer/imports_test.go
- update sign_ functs to return fixed size byte optional
- update `life` not to error if `core_version` doesn't exist (needed for host API tester)
```
go test ./lib/runtime/wasmer/ -run Test_ext_crypto_ed25519_sign_version_1
go test ./lib/runtime/wasmer/ -run Test_ext_crypto_sr25519_sign_version_1
go test ./lib/runtime/life
```
related to #1105
=> fix: lib/runtime: update sign_ funcs to return fixed size byte optional

lib/runtime/wasmer/imports.go, lib/runtime/wasmer/imports_test.go
- allow generic keystore type in public_keys ext functions (since it may contain any type of key)
```
go test ./lib/runtime/wasmer/ -run Test_ext_crypto_ed25519_public_keys_version_1
go test ./lib/runtime/wasmer/ -run Test_ext_crypto_sr25519_public_keys_version_1
```
- closes #1279
=> fix: lib/runtime: allow generic keystore type in public_keys ext functions

dot/core/messages_test.go, dot/core/service.go, dot/network/block_announce.go, dot/network/message_test.go
- added `BestBlock bool` to `BlockAnnounceMessage`
```
```
- closes #1401
=> fix: dot/network: added BestBlock bool to BlockAnnounceMessage

cmd/gossamer/import_runtime.go, cmd/gossamer/import_runtime_test.go, cmd/gossamer/main.go, lib/genesis/genesis.go, lib/genesis/helpers.go
- implement import-runtime subcommand which accepts a compiled runtime binary file and outputs a human-readable genesis file with `"system"` `"code"` set to the given runtime
```
go test ./cmd/gossamer -run TestCreateGenesisWithRuntime
./bin/gossamer import-runtime sometestfile.wasm > test_genesis.json
```
see also https://hackmd.io/@a8cEJX4mTauOvGcMRTUE7g/BJGfrhV7u
- closes #869
=> feat: cmd: implement import-runtime subcommand

lib/crypto/ed25519/ed25519.go, lib/crypto/ed25519/ed25519_test.go, lib/runtime/wasmer/imports.go, lib/runtime/wasmer/imports_test.go
- update ed25519 to use go-schnorrkel bip39 derivation, should fix `ext_crypto_ed25519_generate_version_1`
```
go test ./lib/crypto/ed25519 -run TestNewKeypairFromMnenomic
```
- closes #1418
=> fix(lib/crypto/ed25519): update ed25519 to use go-schnorrkel bip39 derivation

dot/state/storage.go, dot/state/storage_test.go, lib/trie/child_storage.go, lib/trie/trie.go
- Update `StorageState` to load storage from the database.
```
```
- #1354
=> fix(state) : Update StorageState to load storage from database.

dot/network/block_announce.go, dot/network/block_announce_test.go, dot/network/host_test.go, dot/network/notifications.go, dot/network/notifications_test.go, dot/network/service.go, dot/network/service_test.go
- update notificationsProtocol handshakeData to sync.Map since there was a concurrent map read and write panic w/ the map
```
```
=> fix(dot/network): update notificationsProtocol handshakeData to sync.Map

dot/network/block_announce.go, dot/network/host.go, dot/network/host_test.go, dot/network/notifications.go, dot/network/service.go, dot/network/state.go, dot/network/state_test.go, dot/network/sync.go, dot/network/sync_justification.go, dot/network/sync_justification_test.go, dot/network/transaction.go, dot/network/transaction_test.go, dot/network/utils.go, dot/rpc/modules/system_test.go, dot/state/block.go, dot/state/block_test.go, dot/sync/syncer.go, lib/grandpa/message_handler.go, lib/grandpa/network.go
- add functionality to request block justifications when near head if nothing new has been marked finalized for a while
- remove `Roles` field from `transactionHandshake` as the handshake is actually empty
```
```
- closes #1481
=> feat(dot/network): request block justifications when near head

Makefile, docs/mkdocs.yml
- Corrects the edit uri path
- Removes Make file commands for the time being
```
```
-
=> Fixed edit link

dot/network/host.go, dot/network/host_test.go, dot/network/message_cache.go, dot/network/message_cache_test.go, dot/network/notifications.go, dot/network/service_test.go, dot/network/test_helpers.go, go.mod, go.sum
- Add cache to store network messages to prevent sending duplicate messages.
```
TestMessageCache
TestBroadcastDuplicateMessage
```
- #738
=> feat(dot/network): Add cache for network message.

go.mod, lib/babe/babe.go, tests/polkadotjs_test/test_transaction.js
- fix BABE state storing after building block, resolves "state root mismatch" panic after submitting tx
- update polkadot.js transaction submission test
in chain/gssmr/config.toml, set `babe = "debug"` for logging and add
```
babe-threshold-numerator = 1
babe-threshold-denominator = 1
``` 
in the `[core]` section.
then:
```
make gossamer 
./bin/gossamer --chain gssmr init --force
./bin/gossamer --key alice --chain gssmr --rpc --ws
```
in another terminal:
```
node tests/polkadotjs_test/test_transaction.js
```
you should see gossamer build a block that includes the extrinsic w/o error
```
DBUG[04-21|15:53:26] built block                              pkg=babe header="ParentHash=0x1ea298faf569949d1220ed6a1c686231fa2fca01f9463cddccabf3d945b3ed3d Number=7 …
```
=> fix(lib/babe): fix BABE state storing after building block

go.mod, lib/grandpa/errors.go, lib/grandpa/grandpa.go, lib/grandpa/message.go, lib/grandpa/message_handler.go, lib/grandpa/message_handler_test.go, lib/grandpa/message_test.go, lib/grandpa/network_test.go, lib/grandpa/round_test.go, lib/grandpa/types.go, lib/grandpa/vote_message.go
- rename `FinalizationMessage` -> `CommitMessage`, update format to match spec/substrate
- update message type IDs
- update `VoteMessage` to have `Stage` in `SignedMessage`
```
go test ./lib/grandpa -short
```
- closes #1521
=> chore(lib/grandpa): update grandpa message types to match substrate

dot/network/block_announce.go, dot/network/block_announce_test.go, dot/network/host_test.go, dot/network/light_test.go, dot/network/notifications.go, dot/network/notifications_test.go, dot/network/service.go, dot/network/service_test.go, dot/network/sync.go, dot/network/sync_test.go, dot/network/test_helpers.go
- split `handshakeData` into `inbound` and `outbound`, since after further research into the networking, if we receive an inbound stream, the only message we send over it is the handshake. we only send messages (that aren't a handshake) over outbound streams that we initiate
- previously the code assumed that we would need to read from the outbound stream after the handshake (this was incorrect, sorry for the fake news @arijitAD ) 
- also previously we were only storing 1 stream but we actually needed to differentiate between inbound and outbound
- remove `noGossip` so we now actually gossip messages
```
```
also works w/ polkadot, kusama, if you try it (and turn on trace logs) you should be some logs like:
```
TRCE[04-30|17:28:06] sending outbound handshake …
```
=> fix(dot/network): split stored streams and handshakeData into inbound and outbound

go.mod, go.sum
Updated `github.com/ChainSafe/go-schnorrkel` in go.mod to use the latest release
Closes #1556
=> fix(build): go-schnorrkel version

dot/node.go
I have found if the func `dot.NodeInitialized` fails when trying to execute the func `LoadGenesisData` then the database was not closed, so I've added a `defer` to closes de database when the function is exited.
I have not implemented unit tests but I collect some evidences:
1. When a execute the init for the first time the process will be successful, then I went to the `gssmr` (basepath) dir and remove all the stuff except the `KEYREGISTRY` file and when I try to reinitialize the node I got the error:
2. After the inclusion of `defer` to close database anyways, then the node was capable to reinitialize without troubles:
- no issues open
=> fix(dot): Closes db if node initialized check fails

dot/network/block_announce.go, dot/network/block_announce_test.go, dot/network/notifications.go, dot/network/transaction.go, lib/grandpa/message_handler.go, lib/grandpa/message_handler_test.go, lib/grandpa/network.go, lib/grandpa/network_test.go
- add `propagate` return bool to `messageHandler` func type to determine whether to propagate message or not
- update `messageHandler` funcs and test accordingly
- update grandpa `messageHandler` to return `propagate=false` for `NeighbourMessage` and `catchUpResponse` types
```
go test ./lib/grandpa -short
```
- closes #1532
=> feat(dot/network): add propagate return bool to messageHandler func type to determine whether to propagate message or not

dot/core/digest.go, dot/core/interface.go, dot/rpc/modules/api.go, dot/rpc/subscription/listeners.go, dot/rpc/subscription/listeners_test.go, dot/rpc/subscription/websocket.go, dot/rpc/subscription/websocket_test.go, dot/rpc/websocket_test.go, dot/state/block.go, dot/state/block_notify.go, dot/state/block_notify_test.go, dot/types/grandpa.go, lib/grandpa/grandpa.go, lib/grandpa/network.go, lib/grandpa/network_test.go, lib/grandpa/state.go
- update `grandpa.Service` to send neighbour message to peers either every 5 minutes or whenever a new block is finalized
- update `blockState` finalized chans to have type `types.FinalisationInfo` which contains the round and set ID as well as the block number, needed for neighbour message
```
go test ./lib/grandpa -short
go test ./dot/core
go test ./dot/state
```
- closes #1525
=> feat(lib/grandpa): send NeighbourMessage to peers

chain/dev/config.toml, chain/dev/defaults.go, cmd/gossamer/config.go, cmd/gossamer/config_test.go, cmd/gossamer/export.go, cmd/gossamer/main_test.go, dot/config.go, dot/config/toml/config.go, dot/node.go, dot/node_test.go, dot/services.go, dot/services_test.go, go.sum, lib/babe/babe.go, lib/babe/babe_test.go, lib/babe/epoch.go, lib/babe/epoch_test.go, lib/grandpa/network.go, lib/runtime/constants.go, lib/runtime/test_helpers.go, lib/runtime/wasmer/exports_test.go, lib/runtime/wasmer/imports.go, lib/utils/utils.go, tests/polkadotjs_test/start_polkadotjs_test.go, tests/rpc/rpc_02-author_test.go, tests/rpc/rpc_03-chain_test.go, tests/rpc/rpc_05-state_test.go, tests/stress/grandpa_test.go, tests/stress/stress_test.go, tests/utils/gossamer_utils.go
- add --chain dev option which creates a development chain that has 1 authority and authors a block every slot (babe threshold c parameter was configured to be (1, 1) in the runtime)
- turn on RPC and WS servers by default for dev chain
- fix issues with BABE slot calculation that was causing the node not to author due to incorrect slot number/epoch calculations
- remove babe threshold numerator and denominator from configuration as now the dev runtime can be used to "force" block authoring
- update integration tests to use dev genesis file
see modified runtime here:
https://github.com/noot/substrate/blob/noot/v0.8-dev-runtime/bin/node/runtime/src/lib.rs#L107
https://github.com/noot/substrate/blob/noot/v0.8-dev-runtime/bin/node/runtime/src/lib.rs#L1071
```
make gossamer
./bin/gossamer …
```
=> feat: add --chain dev option

dot/types/digest.go, lib/babe/build.go, lib/babe/build_test.go, lib/runtime/wasmer/exports.go, lib/runtime/wasmer/exports_test.go
- fix creation of `NextEpochData` digest by adding pre-runtime digest to block before calling `initialize_block`
```
go test ./lib/babe
```
- related to #1479
=> fix(lib/babe): add pre-runtime digest before calling initialize_block

.github/workflows/build.yml, .github/workflows/checks.yml, .github/workflows/tests.yml
-  Improved ci caching for mod and build
- Added if-ci-failed success attribute  
- Updated ci packages to v2
```
```
-
=> chore(workflow): improved ci caching for mod and build

cmd/gossamer/utils.go, go.mod
- use `golang.org/x/term` package instead of `golang.org/x/crypto/ssh/terminal`
```
make gossamer
./bin/gossamer account --generate
```
This command should shows up a password promp
- Closes #1599
=> fix(cmd): update deprecated package

.github/workflows/build.yml, .github/workflows/tests.yml, dot/core/messages.go, dot/core/messages_test.go, go.mod, go.sum, lib/grandpa/round_test.go
- Fix handle transaction message test
```
TestService_HandleTransactionMessage
```
-
=> fix(dot/core): Fix handle transaction message test.

dot/network/host.go, dot/network/host_test.go, dot/network/notifications.go
- Encapsulate `peerstore.SupportsProtocols` function
- Check if the peer supports protocol before handshake on `sendData` function
```
go run go test ^Test_PeerSupportsProtocol$ github.com/ChainSafe/gossamer/dot/network
```
- closes #1571
=> fix(dot/network): check if peer supports protocol

dot/core/messages.go, dot/core/service.go, dot/core/service_test.go, dot/sync/message_test.go, dot/sync/syncer_test.go, dot/sync/test_helpers.go, dot/types/extrinsic.go, lib/babe/build.go, lib/babe/build_test.go
- Add only extrinsic during chain reorg.
```
TestHandleChainReorg_WithReorg_Trans
```
- closes: #1426
=> fix(dot/core): Add only extrinsic during chain reorg.

dot/core/test_helpers.go, dot/network/block_announce_test.go, dot/network/config.go, dot/network/connmgr.go, dot/network/connmgr_test.go, dot/network/discovery_test.go, dot/network/gossip_test.go, dot/network/host.go, dot/network/host_test.go, dot/network/light_test.go, dot/network/mdns_test.go, dot/network/notifications.go, dot/network/notifications_test.go, dot/network/service_test.go, dot/network/sync_justification_test.go, dot/network/sync_test.go, dot/network/transaction_test.go, dot/rpc/modules/system_test.go
- sleep after stopping network service so give it time to shut down, increase `host.connect` timeout
- remove `RandSeed` usage in tests
```
```
-
=> maintainence: attempt to fix network tests on CI 

dot/sync/test_helpers.go, dot/types/babe.go, dot/types/inherents.go, lib/babe/build.go, lib/babe/epoch.go, lib/runtime/life/exports_test.go, lib/runtime/wasmer/exports_test.go
- remove finalnum inherent (no longer used)
- clear babe `slotToProof` map data from previous epoch as it's no longer needed
```
go test ./lib/babe -short
```
- n/a
=> chore: remove finalnum inherent, clear babe `slotToProof` map

dot/network/utils.go, dot/network/utils_test.go
- Check for size when decoding leb128
```
TestInvalidLeb128
```
-
=> fix(dot/network): Check for size when decoding leb128.

pkg/scale/README.md, pkg/scale/comparison_test.go, pkg/scale/decode.go, pkg/scale/decode_test.go, pkg/scale/encode.go, pkg/scale/encode_test.go, pkg/scale/result.go, pkg/scale/result_example_test.go, pkg/scale/result_test.go, pkg/scale/uint128.go, pkg/scale/varying_data_type.go, pkg/scale/varying_data_type_example_test.go, pkg/scale/varying_data_type_test.go
- Revise `VaryingDataType` public interface
- Introduce `VaryingDataTypeSlice` to handle array of enums currently used in `dot/types/digest.go`
```
go test ./pkg/scale
```
- #1548
=> refactor(lib/scale): Revise VaryingDataType interfaces, and introduce VaryingDataTypeSlice

Makefile, chain/dev/config.toml, chain/dev/defaults.go, chain/gssmr/config.toml, chain/gssmr/defaults.go
- update dev, gssmr to use `genesis-spec.json` by default, it's nicer this way for testing since the spec file can easily be read/modified/# of authorities changed, without needing to change it then do `build-spec` etc
```
make gossamer
./bin/gossamer --chain gssmr init --force
./bin/gossamer --chain gssmr --key alice
./bin/gossamer --chain dev init --force
./bin/gossamer --chain dev
```
- n/a
=> chore: update dev, gssmr to use genesis-spec by default

dot/digest/digest.go, go.sum, lib/grandpa/grandpa.go
- Fix max value for digest.
- `2^64` does bitwise xor. Hence `2^64 = 66`
```
```
- #592
- closes #1680
=> fix(lib/grandpa): Fix max value for digest.

dot/core/service.go, dot/state/block.go, lib/blocktree/blocktree.go, lib/runtime/wasmer/instance.go
- runtime was being stopped when it was pruned; however valid blocks might be pruned from the blocktree if they're past the most recent finalized head, causing the runtime referenced by newer blocks also to be stopped
- don't stop runtime in blocktree prune anymore since unpruned blocks might reference it
run a dev node before/after and see that this no longer panics
- related to #592
=> fix(dot/state): fix runtime panic due to stopped runtime

docs/docs/usage/import-runtime.md
- Update the [Import Runtime usage documentation](https://chainsafe.github.io/gossamer/usage/import-runtime/#2-create-raw-genesis-file-from-genesis-spec) the right flag is `--genesis-spec`, and add an alternative command using the `--output` flag
```
N/A
```
- N/A
=> fix(docs): improve build-spec usage docs

dot/core/service.go, dot/rpc/http.go, dot/rpc/modules/api.go, dot/rpc/modules/author.go, dot/rpc/modules/author_test.go, dot/rpc/modules/mocks/core_api.go, dot/rpc/service_test.go, dot/rpc/subscription/listeners.go, dot/rpc/subscription/listeners_test.go, dot/rpc/subscription/messages.go, dot/rpc/subscription/subscription.go, dot/rpc/subscription/websocket.go, dot/rpc/subscription/websocket_test.go, go.sum, lib/crypto/sr25519/sr25519.go, lib/keystore/helpers.go, lib/runtime/constants.go, lib/runtime/interface.go, lib/runtime/life/exports.go, lib/runtime/wasmer/exports.go, lib/runtime/wasmtime/exports.go
We noticed the PR #1704  merged code related to PR #1672. Then this revert is needed to remove those changes from `development` and a new PR will be made removing all the changes related to **PR-1672** and keeping just the ones related to the `author_hasSessionKeys` RPC call
=> Revert "feat(dot/rpc) implement `author_hasSessionKeys` RPC call"

lib/runtime/constants.go, lib/runtime/test_helpers.go, lib/runtime/wasmer/exports_test.go, lib/runtime/wasmer/imports.go, lib/runtime/wasmer/test_helpers.go
- stub v0.9.8 runtime funcs
- partially implement `ext_storage_clear_prefix_version_2`, `ext_default_child_storage_storage_kill_version_2`, `ext_default_child_storage_storage_kill_version_3`- need to update trie functions to accept `limit` parameter
- updated original issue with new `ext_`s to be implemented
```
go test ./lib/runtime/wasmer
```
- related to #1688
=> chore(lib/runtime): stub v0.9.8 runtime funcs, partially implement storage ext_ funcs

dot/rpc/dot_up_codec.go, dot/rpc/dot_up_codec_test.go, dot/rpc/modules/chain.go, dot/rpc/modules/rpc.go, dot/rpc/subscription/subscription.go
- Add `rpc/modules.AliasesMethods` that is a `map[string]string` which links the alias to the original method, both in the snake case.
- Inside the `dot_up_coded.go` file I've added the code to check if the method is an alias and get the original method name
```
go test  -run ^TestAliasesMethodReplace$ github.com/ChainSafe/gossamer/dot/rpc
```
- Closes #1391
- @edwardmack
=> feat(dot/rpc) implement RPC aliases

dot/rpc/subscription/listeners.go, dot/rpc/subscription/subscription.go, dot/rpc/subscription/websocket.go, dot/rpc/subscription/websocket_test.go
- Implement `chain_subscribeAllHeads` and `chain_unsubscribeAllHeads`
- Create channels and register them into `BlockAPI` and notify the websocket every new block or finalization
```
go test -run ^TestSubscribeAllHeads$ github.com/ChainSafe/gossamer/dot/rpc/subscription
```
- Closes to #1741 
- @timwu20
=> feat(dot/rpc) implement `chain_subscribeAllHeads` RPC

dot/network/block_announce.go, dot/network/gossip_test.go, dot/network/host.go, dot/network/host_test.go, dot/network/notifications.go, dot/network/notifications_test.go, dot/network/service.go, dot/network/service_test.go, lib/grandpa/network.go, lib/grandpa/round_test.go, lib/grandpa/state.go
- Fix deepsource errors.
- https://github.com/ChainSafe/gossamer/pull/1780
```
TestBlockAnnounceHandshakeSize
```
-
=> Fix deepsource errors.

.github/PULL_REQUEST/pull_request.go, .github/workflows/checks.yml, lib/utils/pull_request.go, lib/utils/pull_request_test.go
- Check PR body and title.
```
Test_PR_Checks
```
- None
- @noot
=> chore(CI): Check PR body and title.

.golangci.yml
- Disable shadowing check (disabled by default) with `govet`
- In my opinion:
- these make the code longer since we need to pre-declare things
- you can't have locally-scoped variables in an if or for block for example if the variable name is already used in the upper scope.
Feel free to comment & close it if you disagree with the change 😉 
```
golangci-lint run
```
- No issue
- No-one
=> chore(lint): disable shadowing checks with `govet`

lib/grandpa/errors.go, lib/grandpa/grandpa.go
- recent PR that got merged broke starting with `--chain kusama` and `--chain polkadot`, this fixes it by using the default grandpa interval of 1s if the interval is not set
```
make gossamer
./bin/gossamer --chain polkadot
```
- n/a
=> fix(lib/grandpa): use `defaultGrandpaInterval` if not set, fixes error on startup

lib/utils/pull_request.go, lib/utils/pull_request_test.go
Sorry the previous PR got merged pre-maturely 😅
- Remove `\r` characters (Microsoft, really!??)
- Display new lines as `\\n` in error messages so it's clearer
- Make title regex more flexible
- Allow `-` and `_` in category
- Allow `-`, `_` and ` ` in subcategory (inside parentheses)
- Allow at least one character to be any character at the end of the title (e.g. fullstop `.`)
```
go test -run ^Test_CheckPRDescription$ github.com/ChainSafe/gossamer/lib/utils
```
- @arijitAD
=> chore(pr-check-fix): Fix PR check (again)

.github/workflows/checks.yml, scripts/install-lint.sh
- Update `install-lint.sh` to use v1.43.0
- Pin golangci-lint workflow to use v1.43
=> chore(ci): pin `golangci-lint` version to `v1.43`

.github/CODE_STYLE.md
- Add `String() string` method for new types in code style
=> docs(codestyle): `String() string` methods

.github/workflows/checks.yml
- Only run PR body and description check when actor is not dependabot
=> chore(ci): no PR title and description check for dependabot

.github/ISSUE_TEMPLATE/user_story.yml
- User story issue yml template
- Dropdown `As a`
- Textarea `I want to`
- Textarea `Because`
- Not relevant
- No issue
- @danforbes 
For the curious, [yml github issue template syntax](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)
=> docs(issue): user story issue template

dot/state/block.go, dot/state/block_finalisation.go, dot/state/block_test.go, dot/sync/chain_processor.go, dot/sync/interface.go, dot/sync/mocks/block_state.go
- update `*state.BlockState.AddBlockToBlockTree` to store block in `unfinalisedBlocksMap`, previously it was not storing them in there, resulting in blocks being unable to finalize due to blocks missing from that map in the subchain to be finalized
```
go test ./dot/state
go test ./dot/sync
```
- n/a
- @jimjbrettj
=> fix(dot/state): update `*state.BlockState.AddBlockToBlockTree` to store block in `unfinalisedBlocksMap`

cmd/gossamer/config.go, cmd/gossamer/config_test.go, cmd/gossamer/flags.go
```
go test ^Test_setLogConfig$ github.com/ChainSafe/gossamer/cmd/gossamer
go test ^Test_getLogLevel$ github.com/ChainSafe/gossamer/cmd/gossamer
```
- #1893 
- @noot
=> feat(flags): read log levels from flags

dot/peerset/peerset.go, dot/peerset/peerstate.go, go.mod
- Just migrates to use `internal/log` instead of `log15` in `dot/peerset`. My bad, I merged development in the log package PR before merging it in dev, but didn't notice the log15 sneaking back in.
=> chore(dot/peerset): remove `log15` usage

cmd/gossamer/config.go, dot/config.go
- Earlier, babe lead value was read only from "babe-lead" cli flag.
cfg.BABELead was being set to false in case this flag was not provided.
This commit sets cfg.BABELead from toml config and uses "babe-lead" cli
flag only when it is set.
Run 
```
./bin/gossamer --chain dev
```
If we are lead not, we would not wait for first block, otherwise babe service would fail throwing a timeout error.
-
- @arijitAD
=> fix(cmd/cfg): Use  Babe Lead value from toml config

dot/network/notifications.go, dot/network/pool.go, dot/network/pool_test.go, dot/network/service.go
- Use a slice instead of an array, since returning the array was effectively copying it
```
go test -benchmem -run=Benchmark_sizedBufferPool github.com/ChainSafe/gossamer/dot/network
```
- Related to #1936 and found by reviewing PR #1913 
- Anyone is welcome
=> fix(dot/network): fix memory allocations with `sizedBufferPool`

cmd/gossamer/config.go, cmd/gossamer/flags.go, cmd/gossamer/utils.go, cmd/gossamer/utils_test.go
- Fix config log levels being ignored (remove default flag values)
- Use `parseLogLevelString` in other places to reduce code duplication
- Rename `cfg` to `tomlConfig` in `setLogConfig` since I got confused by my own code
@noot
=> fix(log-levels): do not ignore configuration file log levels

lib/trie/test_utils.go, lib/trie/trie_test.go
- Why?
- This must be slowing down the CI quite badly
- This makes my CPU melt when running them and forgetting to `t.Skip()` them
- These are really benchmarks, and not unit testing anything really as far as i know
- Change unit tests to a merged Go benchmark (you can run them with `go test -bench`)
- Use deepcopy to copy the trie instead of re-generating one, which takes time
- Use math/rand instead of crypto/rand to generate trie values faster. I don't think we care about crypto secured randomness in most unit tests, and especially not in a benchmark
```
go test -bench -run ^Benchmark_Trie_Hash$ github.com/ChainSafe/gossamer/lib/trie
```
- @arijitAD
=> testing(lib/trie): change `lib/trie` slow and intensive benchmark-oriented tests to benchmarks

.github/workflows/build.yml
- See title
CI passing on development branch
- Anyone, this is trivial
=> fix(ci): add missing go-version matrix to fix development branch CI

go.mod, lib/trie/hash.go, lib/trie/hash_test.go, lib/trie/node.go, lib/trie/node_test.go, lib/trie/print.go, lib/trie/trie.go
- Buffer and pool usage fixed and improved 
- Fix buffers not put back in pool
- Write to buffer passed as arguments
- Decouple pools for encoding, digests and hashers
- Improve `sync.Pool` usage generally
- Improve parallel encoding of branches and remove dependency on `sync/x`
- Do not copy when not needed
```
go test -race github.com/ChainSafe/gossamer/lib/trie
```
- #1973
=> fix(trie): memory leak fix in `lib/trie`

.githooks/pre-push, .github/CONTRIBUTING.md, Makefile
- Rename `repo-init` target to `githooks`
- Simplify lint part of the pre-push git hook
- Remove script go mod diff part since Go 1.17 works differently
- Only trigger lint if a go file is staged
- Resource: https://tutorialedge.net/golang/improving-go-workflow-with-git-hooks/
Modify a .go file and run
```sh
./.githooks/pre-push
```
- @jimjbrettj
=> chore(githooks): Makefile `githooks` target and document it

.github/workflows/build.yml, .github/workflows/code-cov.yml, .github/workflows/unit-tests.yml
- Set 60min timeout on CI jobs that often get canceled after 360minutes.
- @timwu20
=> chore(ci): set 60 minutes timeout on some jobs

dot/network/connmgr.go
- add nil checks for `connectHandler` and `disconnectHandler`
- saw this error:
```
nohup: ignoring input
2021-11-23T16:41:55Z INFO loaded package log configuration: {INFO INFO INFO INFO INFO INFO INFO INFO}	config.go:L124	pkg=cmd
2021-11-23T16:41:55Z INFO 🕸️ initialising node services with global configuration name step-enroll-54633, id gssmr and base path /home/ubuntu/.gossamer/gssmr...	node.go:L189	pkg=dot
2021-11-23T16:41:56Z INFO created state service with head 0xa1f12cdab91ed4c6693fda20c8485c1c53be2f2af18dc87c9943b4bdc282fc11, highest number 9854 and genesis hash 0x4a72cc0b6687ad404e1ba7388d0411fbf3545eb278aab044110767d3f14b57fa	service.go:L161	pkg=state
2021-11-23T16:41:59Z INFO creating runtime with interpreter wasmer...	services.go:L84	pkg=dot
panic: runtime error: invalid memory …
```
=> fix(dot/network): add nil checks in `connManager`

devnet/cmd/update-dd-agent-confd/main.go, dot/node_test.go, lib/grandpa/grandpa_test.go
- Sets the `BABELead` attribute to true which should avoid waiting for the first block.
```
go test ./dot -v -run TestStartNode   
```
-
- @noot
=> fix(dot): fix `TestNewNode`

internal/httpserver/option_test.go, internal/httpserver/options.go, internal/httpserver/run.go, internal/httpserver/run_test.go, internal/httpserver/server.go, internal/httpserver/server_test.go, internal/pprof/server.go, internal/pprof/server_test.go
- Why: test failed [here](https://github.com/ChainSafe/gossamer/runs/4299295549?check_suite_focus=true) due to the shutdown period of 3 seconds being too short for a slow/overloaded test worker
- Add an option to set the shutdown period (defaults to 3s)
- Set the shutdown period to 10s for all http server related tests (in `internal/httpserver` and `internal/pprof`)
```
go test -race github.com/ChainSafe/gossamer/internal/httpserver github.com/ChainSafe/gossamer/internal/pprof
```
=> chore(httpserver): option to set shutdown timeout for unit tests

dot/node.go
- Only add pprof service to services list if it is enabled
- @noot
=> fix(pprof): only run pprof service if enabled

tests/stress/stress_test.go
- Load test submit extrinsic
- Added the logs in this branch https://github.com/ChainSafe/gossamer/commit/782fb1731acf2b9169ad14fa5eef9bf4e154f19d#diff-5076a1f78c8a695913cc20ec45b8751f2fdfad72bc68acbbe7b22761a0d1f0e3
Start 3 nodes and fix the authority as Alice, Bob and Charlie in genesis
Genesis:
```
"Babe": {
"Authorities": [
[
"5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY",
1
],
[
"5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty",
1
],
[
"5FLSigC9HGRKVhB9FiEo4Y3koPsNmBmLJbpXg2mp1hXcS59Y",
1
]
]
},
"Grandpa": {
"Authorities": [
[
"5DFNv4Txc4b88qHqQ6GG4D646QcT4fN3jjS2G3r1PyZkfDut",
1
],
[
"5FRbF5E5xpBxaCdjuVkCAtoLgvvoL6wJoE7kAVTUdZBwpgi7",
1
],
[
"5DYo8CvjQcBQFdehVhansDiZCPebpgqvNC8PQPi6K9cL9giT",
1
]
]
},
```
Command:
```
Alice
./bin/gossamer --chain gssmr init --force …
```
=> chore(dot/rpc): Load test submit extrinsic

lib/grandpa/vote_message.go
- primaryProposal were not being counted as valid vote messages although they are, they are simply a pre-vote message issued by the round's primary 
```
go test ./lib/grandpa 
```
- n/a
- @timwu20
=> fix(lib/grandpa): fix vote message switch 

dot/network/message.go
- Fix missing digest in header
```
```
- closes #2014 
- @noot
=> fix(dot/network): Fix missing digest in header

dot/sync/chain_sync.go
- fix SIGABORT introduced by recent commit to development, add nil checks for now until the reason this is happening is fixed
-
-
```
go test ./dot/sync
```
- n/a
- @timwu20
=> fix(dot/sync): add nil header checks

lib/blocktree/blocktree_test.go, lib/blocktree/leaves.go
Given the following block tree representation
```
/-> d -> f
a -> b -> c -> d
\-> c -> d -> f
```
considering the upper `f` and lower `f` have the same number and arrival time, the function `blocktree.leaves. deepestLeaf()` can return inconsistent output since `sync.Map` doesn't guarantee the same sequence every time.
So this inconsistency causes the problem in the test `TestBlockTree_GetHashByNumber` for the following reasons:
1. If the function `blocktree.GetHashByNumber` needs to find the block with number `c` and takes the upper `f` as its deepest leaf then the output will be the middle `c` block
2. However, the function `blocktree.IsDescendantOf` receives the lower `f` and middle `c` as parameters to check if `f` is descendant of `c` which is false because lower `f` is descendant of …
=> fix(lib/blocktree): removes the inconsistency to choose a deepest leaf

lib/runtime/life/resolver.go, lib/runtime/wasmer/imports.go
- Removes the imports prefix logs from `wasmer` and `life`
_logs before_
_logs after_
- Closes #2052
- @jimjbrettj
=> chore(runtime): remove runtime imports prefix logs

dot/network/README.md
Added README to `network` package.  [Rendered docs here](https://github.com/ChainSafe/gossamer/blob/dfo/doc/net/dot/network/README.md).
N/A
Closes #2036
@noot
=> docs(network): README

.github/workflows/staging/kusama-taskdef.json, .github/workflows/staging/polkadot-taskdef.json
- Increases memory usage to 16GB and to 4096 CPU units of the staging validator nodes.
- Upgrade cluster to larger size instances manually.
Push to `staging` branch and ensure task definitions reflect new CPU and memory requirements.
-
- @noot
=> chore(ci): Update staging Kusama and Polkadot validator task definitions

internal/log/logger.go
- This looks like it's fixing the trace logs appearing when the runtime changes
- Credits to @EclesioMeloJunior who found it using the race detector
=> fix(internal/log): fix logger mutex locking in `.New` method

dot/utils_test.go
=> chore(dot): remove trie related memory test

dot/state/offline_pruner.go, lib/trie/database.go, lib/trie/proof.go
This is a simple 'linear' refactor in order to see diffs in a clearer way.
- Explicit variable names
- Less indentation (avoid type switches)
- More return early
- Add named returns
- Clarify comments
- Wrap errors
```
go test github.com/ChainSafe/gossamer/lib/trie/... github.com/ChainSafe/gossamer/internal/trie/...
```
- #2085
=> chore(lib/trie): refactor `lib/trie/database.go`

internal/trie/node/branch.go, internal/trie/node/branch_test.go, internal/trie/node/decode.go, internal/trie/node/header.go, internal/trie/node/leaf.go, internal/trie/node/leaf_test.go, internal/trie/node/node.go, lib/trie/database.go, lib/trie/lookup.go, lib/trie/trie.go
```
go test -race ./lib/trie/...
```
- #2085
=> chore(lib/trie): node `Type() Type` method

dot/state/pruner/pruner.go, dot/state/storage.go, lib/runtime/storage/trie.go, lib/trie/database.go, lib/trie/trie.go, lib/trie/trie_test.go
- avoid confusion about the order of hashes
- improve performance and avoid copying the map back to a slice
```
```
-
=> chore(lib/trie): use map for `trie.getInsertedNodeHashes` to reduce memory pressure

internal/trie/node/branch_encode.go, internal/trie/node/branch_encode_test.go
Benchmarks:
```
// Opportunistic parallel:	13781602 ns/op	14419488 B/op	  323575 allocs/op
// Sequentially:		24269268 ns/op	20126525 B/op	  327668 allocs/op
```
```
go test -race ./internal/trie/...
```
- #1973 
- @timwu20
=> chore(lib/trie): opportunist parallel hashing

tests/polkadotjs_test/start_polkadotjs_test.go, tests/rpc/rpc_00_test.go, tests/rpc/rpc_01-system_test.go, tests/rpc/rpc_02-author_test.go, tests/rpc/rpc_03-chain_test.go, tests/rpc/rpc_04-offchain_test.go, tests/rpc/rpc_05-state_test.go, tests/rpc/rpc_06-engine_test.go, tests/rpc/rpc_07-payment_test.go, tests/rpc/rpc_08-contracts_test.go, tests/rpc/rpc_09-babe_test.go, tests/stress/stress_test.go, tests/sync/sync_test.go
- Replace (just why) `_, _ = fmt.Fprintln(os.Stdout` with `t.Log(` or `fmt.Println(` (for TestMain) for test skipping logs
=> chore(test-skip-logs): Use `t.Log` + `fmt.Println` instead of `_, _ = fmt.Fprintln`

dot/sync/chain_sync.go, dot/sync/chain_sync_test.go, dot/sync/tip_syncer.go, dot/sync/tip_syncer_test.go
- fix "block with unknown header is ready" error which was caused by already having the block in the ready queue or processed, so it was deleted from the pending set already (which is why we couldn't find the header in the pending set)
```
go test ./dot/sync
```
- closes #2189
=> fix(dot/sync): fix "block with unknown header is ready" error

dot/sync/chain_processor.go
- don't log case where we fail to get parent while processing (except as a trace log)
- this doesn't explicitly track the first block that fails (and its whole descendant chain), but I think it's ok as the processing of the block will fail almost immediately if we don't have the parent (ie line 214)
```
./bin/gossamer --chain polkadot
```
ensure that logs don't get spammed anymore
- closes #2154
- @qdm12
=> fix(dot/sync): cleanup logs; don't log case where we fail to get parent while processing

dot/network/helpers_test.go, dot/network/notifications.go, dot/network/notifications_test.go, dot/network/service.go, dot/network/service_test.go, dot/state/block_finalisation.go, dot/state/storage.go, lib/blocktree/blocktree.go
- fix removal of tries older than current finalized from memory
- exchange `BlockAnnounceHandshake` with peer on connect, previously it would sometimes take many minutes for the node to start bootstrap syncing. this makes it start basically as soon as we get peers.
```
run gossamer for many hours and see better memory usage (hopefully)?
```
- #1973 
- @qdm12
=> fix(dot/state): actually prune finalized tries from memory

go.mod, lib/runtime/wasmer/instance.go, lib/runtime/wasmer/instance_test.go
https://github.com/paritytech/substrate/blob/master/primitives/maybe-compressed-blob/src/lib.rs
- Support [Substrate Wasm compression](https://github.com/paritytech/substrate/blob/master/primitives/maybe-compressed-blob/src/lib.rs)
- None
- N/A
- @timwu20
=> feat(lib/runtime): support Substrate WASM compression

go.mod, go.sum, internal/trie/node/branch.go, internal/trie/node/branch_test.go, internal/trie/node/leaf.go, internal/trie/node/leaf_test.go, internal/trie/node/node.go, lib/trie/print.go, lib/trie/print_test.go
Why? Because I'm going crazy trying to print a nice trie or nodes when debugging tests
- Use github.com/qdm12/gotree to have a tree string structure
- Add `StringNode` methods to node implementations
- Update node's `String` methods and `Trie`'s `String` method
```
```
=> chore(trie): improve `String()` methods for `trie.Trie` and `node.Node`

dot/sync/benchmark.go, dot/sync/benchmark_test.go, dot/sync/chain_sync.go
=> fix(dot/sync): sync benchmark

dot/network/discovery.go
- Remove unnecessary context creation inside a infinity for loop
```
go test ./dot/network/... -v -short -timeout 5m
```
- Closes #2247
- @noot
=> fix(dot/network): remove `defer cancel()` inside loop

dot/sync/chain_sync.go, dot/sync/chain_sync_test.go
- remove `max` size limit on ascending block requests we send out, it isn't really needed as if there aren't any more blocks to return, the remote node just won't send them (eg. if we're at the head)
- there was also a case where we send the request with some limit, but the remote node actually had another block just past the limit (just built for example), then we'd have to send out another request after for that block
```
go test ./dot/sync
```
- #1356 
- @jimjbrettj
=> fix(dot/sync): remove max size limit from ascending block requests

lib/trie/trie.go, lib/trie/trie_test.go
- Production code fixes: do not update generation when no change is done
- Production code fix/safety: force new value node to have the current trie generation
- Modify existing test cases to check generation values
```
```
- #2209 
- @noot
=> chore(lib/trie): fix generation issues and add more generation test cases 

lib/trie/database.go, lib/trie/proof_test.go
- Remove `delete(proofHashesMap, hash)` from the `loadProof` function, this was creating problems when nodes were in different paths however with the same hash not being loaded into the trie.
I added two more test inside `./lib/trie/proof_test.go`
- Test leaf nodes in different paths with the same hash
```
go test -run ^TestLeafNodes_SameHash_DifferentPaths_GenerateAndVerifyProof$ github.com/ChainSafe/gossamer/lib/trie
```
- Test branch nodes in different paths with the same hash
```
go test -run ^TestBranchNodes_SameHash_DiferentPaths_GenerateAndVerifyProof$ github.com/ChainSafe/gossamer/lib/trie
```
- Closes #2240
- @noot
=> fix(lib/trie): remove map deletion at `loadProof`

.github/workflows/mocks.yml
- Use `integration` build tag to take integration test files into account
- Verify mocks part of the gossamer/devnet module
Mocks workflow passing
=> fix(ci): mocks checking fixes

.github/workflows/checks.yml, Makefile
- Use `Makefile` lint target
- Add `--build-tags integration` to Makefile lint command
- Add ` --timeout 10m` to Makefile lint command.
checks workflow passing
=> fix(ci): run golangci-lint with integration build tag

dot/rpc/modules/dev_integration_test.go, dot/state/block.go, dot/state/block_data_test.go, dot/state/block_finalisation.go, dot/state/block_finalisation_test.go, dot/state/block_notify_test.go, dot/state/block_race_test.go, dot/state/block_test.go, dot/state/epoch_test.go, dot/state/helpers_test.go, dot/state/initialize.go, dot/state/offline_pruner.go, dot/state/service.go, dot/state/service_test.go, dot/state/storage.go, dot/state/storage_test.go, dot/state/tries.go, dot/state/tries_test.go, lib/grandpa/grandpa_test.go
Previously after each finalized block, a trie would not be found from memory and would be loaded from the database.
You can print it out at [this code line](https://github.com/ChainSafe/gossamer/blob/3ae34011ee4d00bc0c439d21e93c121ba7701294/dot/state/storage.go#L131). This caused some memory bloat in the long run.
I initially tried to refactor a bit by injecting the tries (mutex protected already) instead of relying on channels and a goroutine to send hashes to the state, and this has been fixed. I think it was a race condition introduced by the buffered channel + goroutine, where `TrieState` was called too late after the trie got deleted from memory.
- #1973 
- @timwu20
=> fix(dot/state): inject mutex protected tries to states

dot/network/helpers_test.go, dot/network/inbound.go, dot/network/notifications.go, dot/network/service.go, dot/network/sync.go, dot/network/utils.go
- See why in #2288 
- Related to #2288
- @noot
=> fix(dot/network): resize bytes slice buffer if needed

.github/workflows/staging/kusama-taskdef.json, .github/workflows/staging/openmetrics.d/kusama-conf.yaml, .github/workflows/staging/openmetrics.d/polkadot-conf.yaml, .github/workflows/staging/polkadot-taskdef.json, Dockerfile.staging, devnet/cmd/update-dd-agent-confd/confd.yml
- Modify staging container sizes to use 12GB instead of the full 16GB per instance.
- Update datadog metrics harvester to include new metrics from #2220 
```
go test ./...
```
- #1973 
- @qdm12
=> chore(staging): update staging task definitions, and expose pprof server

cmd/gossamer/import_runtime.go, cmd/gossamer/import_runtime_test.go, cmd/gossamer/main_test.go, cmd/gossamer/toml_config_test.go, dot/build_spec_integration_test.go, dot/rpc/modules/sync_state_integration_test.go, dot/sync/syncer_test.go, dot/utils.go, lib/genesis/test_utils.go, lib/runtime/life/exports_test.go, lib/runtime/wasmer/exports_test.go, lib/utils/utils.go, tests/stress/grandpa_test.go, tests/utils/gossamer_utils.go
💁 as the branch name suggests, that was me having some friday night fun and killing the 2022 new year PR #2139 to move everything to `internal/` for now.
- Detect project root based on `chain` directory (and its subdirectories)
- Better detection of chain directory location for tests and production code
- Allow to move source files more easily
- Note this is just a takeaway from now defunct #2139 
- Helping for #1527
=> feat(all): detect chain directory dynamically

internal/trie/node/branch.go, internal/trie/node/copy.go, internal/trie/node/hash.go, internal/trie/node/leaf.go, internal/trie/node/leaf_encode.go
- Remove leaf's `encodingMu` since it was a temporary fix I forgot to remove in #2009 as far as I recall
- Remove leaf and branch rw mutex since it's not needed (all code is pretty much synchronous and called synchronously through mutexes etc.)
```
go test -count 1 -race ./internal/trie/... ./lib/trie/...
```
Done to test a comment after discussion with sigmap on Slack
=> chore(internal/trie/node): remove all mutexes

internal/trie/node/dirty.go, internal/trie/node/dirty_test.go, internal/trie/node/leaf.go, lib/trie/trie.go
```
```
- #1973 
- Not anyone in particular
=> feat(lib/trie): clear fields when node is dirty

lib/trie/trie.go, lib/trie/trie_test.go
- Pass limit and return values deleted count, do not pass limit as pointer downstream
- Simpler code more appropriate for end goal (return number of deleted values)
- Helps #2229 
```
```
- #2229
=> chore(lib/trie): refactor `ClearPrefixLimit`

dot/core/errors.go, dot/core/messages_integration_test.go, dot/core/service.go, dot/core/service_integration_test.go, dot/core/service_test.go, tests/stress/helpers.go, tests/stress/stress_test.go
- Test half of dot/core/service.go (second half will be in separate PR). This PR includes the functions: StorageRoot, HandleBlockProduced, handleBlock, handleCodeSubstitution, handleBlockAsync, and maintainTransactionPool
- Uncommented necessary code and removed TODO from maintainTransactionPool
```
go test ./dot/core -v -coverprofile coverage.out
go tool cover -func coverage.out
```
- #2184
- @noot
=> testing(dot/core): rewrite dot/core service tests (part 1)

dot/core/service.go, dot/state/grandpa.go, dot/state/pruner/pruner.go, dot/types/body.go, lib/grandpa/grandpa.go, tests/stress/helpers.go
Dumb replacement of `err == someSentinelError` by `errors.Is(err, someSentinelError)`
Found whilst doing #2330 and took under 3 minutes.
=> chore(all): use `errors.Is` instead of `err ==`

Makefile, dot/network/utils.go, dot/rpc/websocket_test.go, dot/telemetry/mailer.go
(Got sick of these 3 errors always showing up on my linter v1.44.x and that took under 5 minutes 😉)
```
go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.44
golangci-lint run
```
=> chore(lint): upgrade `golangci-lint` to `v1.44.x`

lib/babe/epoch_test.go, lib/babe/verify_test.go
Dumb `gomock.Eq` removal since it's not needed.
Found whilst doing #2330 and took under 1 minute.
=> chore(tests): remove unneeded `gomock.Eq` in tests

dot/network/block_announce.go, dot/network/block_announce_test.go, dot/network/errors.go, dot/network/host_test.go, dot/network/inbound.go, dot/network/notifications.go, dot/network/notifications_test.go, dot/network/peersdata.go, dot/network/service.go, dot/network/service_test.go
- Add `peersData` struct holding 3 mutex protected maps:
- inbound
- outbound
- mutexes
- Add helping methods on `peersData`:
- `countOutboundStreams`
- `countInboundStreams`
- #2281
=> chore(dot/network): replace `sync.Map` with map+mutex

internal/trie/node/branch.go, internal/trie/node/branch_test.go, internal/trie/node/copy.go, internal/trie/node/decode.go, internal/trie/node/decode_test.go, internal/trie/node/encode_decode_test.go, internal/trie/node/stats.go, internal/trie/node/stats_test.go, lib/trie/print_test.go, lib/trie/trie.go, lib/trie/trie_endtoend_test.go, lib/trie/trie_test.go
💁 descendants are stored in **every node** since we have a delete operation that cuts of an entire branch, so it's more performant to have it get the count of descendants to remove from the branch being removed, rather than iterating over this branch and all its children.
Next PR will be to publish the count of descendants of the root node to the Prometheus server
```
```
- #2229 
- @timwu20
=> feat(lib/trie): add descendants count to branches

tests/stress/empty.go, tests/stress/errors.go, tests/stress/helpers.go, tests/stress/stress_test.go
*First in a serie of `tests/` refactor PRs*
The end goal is to move timeouts responsibility to the test instead of hidden in helpers.
- Takes in context
- Retry as long as context is not canceled
- Assert errors and common values
```
make it-stress
```
- #2326 
- Anyone it's just a single function changed.
=> chore(tests/stress): refactor `compareBlocksByNumber`

lib/trie/trie.go, lib/trie/trie_test.go
- Only copy nodes when mutation is certain
- Should alleviate memory operations and garbage collection load
- Trie snapshot helper methods `prepLeafForMutation` and `prepBranchForMutation`
- Call `SetDirty(true)` in snapshot trie helper methods
- Add test case to reach back full coverage of trie.go
- Note there is still full unit test coverage (from `trie_test.go`) making these changes possible/safe.
```
go test ./lib/trie
```
- #2351 
- ~Unblocks #2310 (based off this one)~ historical reason of this PR
- @noot
=> feat(lib/trie): only copy nodes when mutation is certain

dot/network/notifications.go
- Re-add nil mutex check
- Fixes the SIGABRT ugly nil pointer issue
- @kishansagathiya
=> fix(dot/network): re-add nil mutex check for disconnected peer

lib/runtime/life/exports.go, lib/runtime/life/exports_test.go, lib/runtime/life/instance.go, lib/runtime/wasmer/exports.go, lib/runtime/wasmer/imports.go, lib/runtime/wasmer/instance.go
- No longer provide workaround for runtimes with old babe implementation
- Stop caching runtime version inside life and wasmer instance
-> The runtime environment no longer expect the `Version()` Runtime API to be present in all runtimes.
I have not tested this well yet, beyond checking if it fixes w3f/polkadot-tests#19.
- w3f/polkadot-tests#19
Anyone
=> fix(lib/runtime): avoid caching version in runtime instance

.github/dependabot.yml
It looks like some of our "weird" labels were coming from Dependabot as some people had suggested. At the moment, this PR configures Dependabot to only use the `dependabot` label, but I'm happy to hear suggestions for other approaches.
Ref: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#labels
Primary reviewers: @qdm12 & @timwu20 🙏🏻
=> Dependabot should only use `dependencies` label

.golangci.yml, Makefile, dot/rpc/modules/grandpa.go, internal/pprof/server_test.go, lib/runtime/life/resolver.go, lib/runtime/life/test_helpers.go, lib/runtime/wasmer/imports.go, tests/stress/helpers.go
- In order to check golang 1.18 generic code we should upgrade golangci-lint to version `v1.45`
- Fixes PR https://github.com/ChainSafe/gossamer/pull/2339 CI
```
N/A
```
- N/A
- @qdm12
=> chore(golang-ci): upgrade `golangci-lint` to `v1.45`

internal/trie/node/copy.go, internal/trie/node/copy_test.go, internal/trie/node/node.go, lib/trie/trie.go, lib/trie/trie_test.go
- Do not copy cached fields when not needed
- Do not copy key field when not needed
- Do not copy value field when not needed
```
go test -race ./internal/trie/... ./lib/trie/...
```
- #2351 - already done but this is finer to save a few extra operations
- Anyone :tada:
=> feat(trie): finer deep copy of nodes

cmd/gossamer/README.md
- Fix Gossamer server metrics port from `9090` to `9876`
- @danforbes
=> docs(cmd/gossamer): Metrics port `9090` -> `9876`

tests/rpc/rpc_00_test.go, tests/rpc/rpc_01-system_test.go, tests/rpc/rpc_02-author_test.go, tests/rpc/rpc_03-chain_test.go, tests/rpc/rpc_04-offchain_test.go, tests/rpc/rpc_05-state_test.go, tests/rpc/rpc_06-engine_test.go, tests/rpc/rpc_07-payment_test.go, tests/rpc/rpc_08-contracts_test.go, tests/rpc/rpc_09-babe_test.go, tests/rpc/system_integration_test.go, tests/stress/grandpa_test.go, tests/stress/helpers.go, tests/stress/network_test.go, tests/stress/stress_test.go, tests/sync/sync_test.go, tests/utils/chain.go, tests/utils/common.go, tests/utils/dev.go, tests/utils/framework.go, tests/utils/gossamer_utils.go, tests/utils/request_utils.go, tests/utils/system.go
- Inject context to `PostRPC` and `PostRPCWithRetry`
- Swap method and url arguments for `PostRPC` and `PostRPCWithRetry`
- Remove some global variables
- Wrap all possible errors
- `PostRPCWithRetry` retries until context is canceled
- Keep 1s timeout for RPC calls
Existing tests suites passing
- #2386
=> chore(tests): refactor tests/utils/request_utils.go

.github/workflows/build.yml, .github/workflows/code-cov.yml, .github/workflows/integration-tests.yml, .github/workflows/unit-tests.yml
- `go env` was called before `go` was setup
- Simplify/fix bad comments and names
=> fix(ci): caching of Go caches

lib/trie/database.go, lib/trie/proof.go, lib/trie/proof_test.go
- Review comment
- Change argument name `rawProof` to `proofEncodedNodes`
```
```
As requested by Polymer Labs
=> feat(trie): export `LoadFromProof`

tests/rpc/rpc_05-state_test.go, tests/stress/helpers.go, tests/stress/network_test.go, tests/stress/stress_test.go, tests/utils/chain.go, tests/utils/dev.go, tests/utils/framework.go, tests/utils/gossamer_utils.go, tests/utils/system.go
- Change all functions to use `Node` instead of `*Node` since there is no reason to use a pointer really
- Change RPC functions to take in RPC port string only
- This unblocks a refactor in a next PR
All end to end tests to pass
- #2388 
- @edwardmack
=> chore(end-to-end): handle `Node` structure without pointer

.github/workflows/checks.yml, .github/workflows/docker-grandpa.yml, .github/workflows/docker-js.yml, .github/workflows/docker-rpc.yml, .github/workflows/docker-stable.yml, .github/workflows/docker-stress.yml, .github/workflows/staging.yml, .github/workflows/unit-tests.yml, Dockerfile.staging
- GO111MODULE is enabled by default since Go 1.16, and we use Go 1.18, so it's removed
All test suites passing
- @timwu20
=> chore(ci): remove `GO111MODULE: on`

cmd/gossamer/config_test.go, cmd/gossamer/export.go, cmd/gossamer/export_test.go, cmd/gossamer/flags_test.go, cmd/gossamer/toml_config.go, cmd/gossamer/toml_config_test.go, cmd/gossamer/utils.go
Following a conversation on #2112 this simply refactors `exportConfig` to not call `os.Exit(1)` but return an error instead.
It's also a bit changed to only return an error, since the file handler that was returned wasn't used except to get the file name string.
- Anyone
=> chore(cmd/gossamer): `exportConfig` returns an error instead of calling `os.Exit(1)`

Dockerfile.staging
- Use `go install` instead of `go build`.  Something must have changed for default target path of `go build` in 1.18.
Ensure staging workflow is able to build the container and deploy to staging
=> fix(ci): fix staging workflow

.github/workflows/copyright.yml
- Copyright workflow got broken a week ago with https://github.com/ChainSafe/gossamer/pull/2467 so this fixes it by using `git diff --exit-code`
@danforbes
=> fix(ci): copyright workflow to exit if different files

dot/state/epoch.go, lib/babe/babe.go, lib/babe/epoch.go
I just saw this ugliest error logged out on Dan's test runtime run, so I had to fix it:
- Error is returned only if it's not nil and not `chaindb.ErrKeyNotFound` in `HasEpochData` (it was logged as `%w (nil)` previously)
- Only `HasEpochData` wraps the epoch number context, not all above callers, to avoid repeating information
=> chore(lib/babe): epoch error wrapping fixed up

lib/grandpa/message.go, lib/grandpa/message_handler_test.go, lib/grandpa/message_test.go, lib/grandpa/message_tracker.go, lib/grandpa/message_tracker_test.go, lib/grandpa/vote_message.go
Just rename `SignedMessage` `Hash` field to `BlockHash` to avoid any confusion
```sh
go test -tags integration github.com/ChainSafe/gossamer/lib/grandpa
```
Created following a discussion from #2485 
@jimjbrettj
=> chore(lib/grandpa): SignedMessage `Hash` to `BlockHash`

.golangci.yml, Makefile
- Set timeout to 10min, remove timeout flag from Makefile
- Remove copy pasted comments from example .golangci.yml
- Add URL at the top to the .golangci.yml configuration documentation webpage
- Remove linter settings for linters not enabled `dupl` and `gocritic`
- Remove default `fast: false`
- Limit to default 50 errors per linter, instead of no limit
- Limit to default 3 same issues, instead of no limit
- Remove `megacheck` linter which is no longer available
- Remove copyright notice (not really anything to protect)
```sh
golangci-lint run
```
For context, this was done whilst adding linting documentation to Chainsafe's engineering Wiki on Go.
@jimjbrettj
=> chore(lint): simplify .golangci.yml

.github/workflows/build.yml, .github/workflows/docker-grandpa.yml, .github/workflows/docker-js.yml, .github/workflows/docker-rpc.yml, .github/workflows/docker-stable.yml, .github/workflows/docker-stress.yml
- Use built-in `DOCKER_BUILDKIT=1`
- Remove QEMU setup (no emulation)
- Remove Buildx setup (no emulation)
- Remove default values: `file: ./Dockerfile`, `platforms: linux/amd64`, `push: false`
- Remove unneeded `name` and `id` of Docker steps
CI suite passing
=> chore(ci): simplify Docker setup

dot/rpc/http.go, dot/rpc/subscription/websocket.go, dot/rpc/subscription/websocket_test.go
- Created a struct with the required fields: `ID float64`, `Method string` and `Params any` to ensure the types and avoid conversions over `interface{}`
- Created a condition to don't allow an empty `Method` field
```sh
go test github.com/ChainSafe/gossamer/dot/rpc/subscription
```
- Closes #2413
@jimjbrettj
=> fix(dot/subscription): check websocket message from untrusted data

chain/dev/config.toml, dot/rpc/subscription/websocket.go, dot/rpc/subscription/websocket_test.go
- Add checks in methods `initExtrinsicWatch` and `initStorageChangeListener` to safely casting types from untrusted inputs
```sh
go test github.com/ChainSafe/gossamer/dot/rpc/subscription
```
- Closes #2412
@edwardmack
=> fix(dot/subscription): unsafe type casting from untrusted input

cmd/gossamer/config.go, cmd/gossamer/main.go, cmd/gossamer/toml_config.go
- Check if a pointer is `nil` before accessing its value
- Change the description of `build-spec` command to use `build-spec --output file.json` rather than `build-spec > file.json` to avoid inserting logs outputs in the file
```sh
gossamer build-spec --raw --output ./genesis.json
```
- Closes #2246
=> fix(cmd): avoid nil pointer dereference

dot/state/epoch.go
- The genesis block does not contain any BABE digest since this information is already persisted using the information in the `spec.json`
When you start the gossamer node you should not see 
```
2022-06-08T17:52:16+05:30 EROR failed to persist babe next epoch data: cannot get epoch for block 0 (0xee87cc7ac5e87460094ec4ba29bbf8f28fb7741b69e7edb142233c3dd990b365): header does not contain pre-runtime digest	digest.go:L244	pkg=digest
2022-06-08T17:52:16+05:30 EROR failed to persist babe next epoch config: cannot get epoch for block 0 (0xee87cc7ac5e87460094ec4ba29bbf8f28fb7741b69e7edb142233c3dd990b365): header does not contain pre-runtime digest	digest.go:L249	pkg=digest
```
- Related #2591
=> fix(state/epoch): assign epoch 1 when block number is 0

cmd/gossamer/config_test.go, dot/core/service_integration_test.go, dot/node_integration_test.go, dot/rpc/modules/author_integration_test.go, dot/rpc/subscription/listeners_test.go, dot/sync/syncer_integeration_test.go, lib/babe/babe_integration_test.go, lib/runtime/constants.go, lib/runtime/life/test_helpers.go, lib/runtime/test_helpers.go, lib/runtime/wasmer/imports_test.go, lib/runtime/wasmer/instance_test.go, lib/runtime/wasmer/test_helpers.go
**Why**: because without network I couldn't run integration tests yesterday and that drove me mad
- Download runtimes to ${TMP}/gossamer/runtimes/ depending on environment
- Do not remove runtime files and re-use them if found
- Merge `GetRuntimeVars` and `GetRuntimeBlob` into `GetRuntime`
- Improve HTTP fetching code for runtime wasms
- Remove `TestMain`-used `GetRuntimes` since we already have calls to `GetRuntime` wherever a runtime blob is needed.
All tests passing
Done since I couldn't work without it offline
=> chore(tests): cache runtimes to work offline

.github/workflows/integration-tests.yml, .github/workflows/unit-tests.yml, dot/peerset/peerset.go
- sets channel to nil on close
- nil check before producing to channel
```sh
go test ./dot/network
```
#2567
=> fix(dot/peerset): fix sending on closed channel race condition when dropping peer

dot/sync/block_queue_test.go
The test was running 3 operations in parallel for 50ms.
The `push` method writes to a buffered queue channel, and so would block at the end of the test (when the context would be canceled) since the channel would sometimes be full.
To fix this, an additional goroutine takes care of draining the channel when the context is canceled, so that push can write one last time to the queue channel and exit.
```sh
go test -timeout 10s -race -run ^Test_lockQueue_threadSafety$ github.com/ChainSafe/gossamer/dot/sync
```
@edwardmack
=> fix(dot/sync): fix `Test_lockQueue_threadSafety`

lib/runtime/wasmer/imports_test.go
Fix flaky sort in `Test_ext_crypto_sr25519_public_keys_version_1` so it doesn't fail occasionally anymore.
```sh
go test -run ^Test_ext_crypto_sr25519_public_keys_version_1$ github.com/ChainSafe/gossamer/lib/runtime/wasmer
```
Found in https://github.com/ChainSafe/gossamer/runs/6905658052?check_suite_focus=true
Fixes #2164
Fixes #2355
@timwu20
=> fix(wasmer): fix flaky sort in `Test_ext_crypto_sr25519_public_keys_version_1`

dot/sync/chain_sync.go, dot/sync/chain_sync_test.go
- Production code had to be refactored to be event driven
- Fix `Test_chainSync_logSyncSpeed` to be fully event driven
- Fix `Test_chainSync_start` to be fully event driven
```sh
go test -tags integration github.com/ChainSafe/gossamer/dot/sync/...
```
@timwu20
=> fix(dot/sync): Fix flaky tests `Test_chainSync_logSyncSpeed` and `Test_chainSync_start`

lib/trie/trie.go, lib/trie/trie_test.go
- Implement check to handle condition when deleting a nonexistent key K_x when the trie contains valid key K_y for which K_x is a prefix.  i.e. where `bytes.HasPrefix(k_y, k_x)` holds will no longer cause panic
```sh
go test -run ^Test_Trie_delete$ github.com/ChainSafe/gossamer/lib/trie -v
```
closes: #2404 
@timwu20
=> fix(trie): Panic when deleting nonexistent keys from trie (GSR-10)

lib/trie/trie.go
Fix removing descendants for the ClearPrefix operation.
That was found with a sometimes flaky trie test in the CI.
```sh
go test -count 1 ./internal/trie/... ./lib/trie/...  
```
=> fix(trie): descendants count for clear prefix

tests/polkadotjs_test/start_polkadotjs_test.go, tests/rpc/rpc_00_test.go, tests/rpc/rpc_01-system_test.go, tests/rpc/rpc_02-author_test.go, tests/rpc/rpc_03-chain_test.go, tests/rpc/rpc_04-offchain_test.go, tests/rpc/rpc_05-state_test.go, tests/rpc/rpc_06-engine_test.go, tests/rpc/rpc_07-payment_test.go, tests/rpc/rpc_08-contracts_test.go, tests/rpc/rpc_09-babe_test.go, tests/stress/stress_test.go, tests/sync/sync_test.go, tests/utils/build.go
This happened one too many times, us developers forgetting to re-build Gossamer before running an e2e test locally.
This changes e2e to build the binary every time a test is run. The first build takes 10s, but it only takes about 1.5s on rebuilds, which is well worth the avoided trouble of dev time wasted.
End-to-end suites passing
Fixes #2458 
@edwardmack
=> feat(e2e): build Gossamer on any test run

dot/state/epoch.go
- `nextEpochMap` type which uses generics
```sh
```
=> create nextEpochMap type

internal/trie/node/decode.go, internal/trie/node/decode_test.go, lib/trie/database.go
Extend from previously limited-to-leaf inlined decoding to all node variants.
```sh
go test -count 1 ./internal/trie/... ./lib/trie/...
```
One step towards #2418 
=> feat(trie): decode all inlined node variants

.github/workflows/fuzz.yml
> By default, all other tests in that package will run before fuzzing begins. This is to ensure that fuzzing won’t report any issues that would already be caught by an existing test.
Source: https://go.dev/doc/fuzz/
But in our case, we run unit tests in another required workflow, so this limits it to run the fuzz test only.
@timwu20
=> chore(ci): only run Fuzz test in fuzz workflow

lib/grandpa/errors.go, lib/grandpa/message_handler.go, lib/grandpa/message_handler_test.go
- Implement fix to `getEquivocatoryVoters` that does not include duplicate votes as equivocatory votes, addressing Sigma Prime - Gossamer Audit issue 11 (GSR-11)
- Add unit tests for testing duplicate votes condition.
```sh
go test -run ^Test_getEquivocatoryVoters$ github.com/ChainSafe/gossamer/lib/grandpa -v
```
closes: #2410 
=> fix(lib/grandpa): Duplicate votes is GRANDPA are counted as equivocatory votes (GSR-11)

lib/babe/epoch_handler.go
- Replace `time.Until` by `startTime.Sub(time.Now())`
- Use `time.Sleep` to correct the time if there is a negative difference between the current time (when the channel is triggered) and the time defined in the slot
It is possible to see the time being adjusted after the modifications
- Closes #2634
@qdm12
=> fix(lib/babe): ensure the slot time is correct before build a block

dot/sync/message.go
A block request contain start block, end block, direction and max size.
It could be the case that block between start and end are less than max
size. In such cases, so far we were pruning block from the end while
preparing a block response.
The correct way however would be to prune from the start, if the direction
is descending and prune from the end if the direction is ascending.
Since, we were pruning blocks the wrong way, we were preparing a
response which substrate was not expecting. And that used to result in
substrate dropping us.
This commit fixes that issue.
```sh
```
Fixes #2595
@timwu20
=> If the direction in block request is descending, prune blocks from start.

tests/stress/stress_test.go
Otherwise it sometimes hangs forever retrying (i.e. when a node simply won't sync).
In that case, the test should just fail and move to the next one.
Quick-fix added after seeing https://github.com/ChainSafe/gossamer/runs/7281642432?check_suite_focus=true#step:3:32
```sh
go test -run ^TestSync_Basic$ github.com/ChainSafe/gossamer/tests/stress
```
@timwu20
=> chore(ci): limit `TestSync_Basic` to 1 minute

tests/rpc/rpc_03-chain_test.go
`TestChainRPC` broke on our development branch.
```
Expect "0x280403000bbbb895028201" to match "^0x280403000b[0-9a-z]{8}8101$"
```
I wrote that regex, and it was consistently ending with 8101, now it's 8201 out of the blue.
This PR updates the regex to use `8201` instead.
But ideally, someone can point why this changed? 🤔 
```sh
MODE=rpc go test -run ^TestChainRPC$ github.com/ChainSafe/gossamer/tests/rpc
```
@timwu20
=> fix(tests): fix block body regex in `TestChainRPC`

lib/trie/proof/verify.go, lib/trie/proof/verify_test.go
- Merkle value for all encoded proof nodes is their encoding hash digest
- Add comments
- Update error wrapping strings
This is done following comments on https://substrate.stackexchange.com/questions/2892/proof-order-of-proof-encoded-nodes
```sh
go test github.com/ChainSafe/gossamer/lib/trie/proof
```
@timwu20
=> chore(trie): simplify Verify proof function

dot/rpc/websocket_test.go, lib/runtime/errors.go, lib/runtime/wasmer/exports.go, lib/runtime/wasmer/exports_test.go, lib/runtime/wasmer/imports_test.go, lib/runtime/wasmer/instance.go, lib/runtime/wasmer/instance_test.go
Simple refactor to adapt `exec` to be more independent, in order to have an instance-independent check runtime function.
- Remove nil storage check for temporary instances (some calls don't need it, and anyway we should panic if this happens imo)
- Fix for bigger than max int32 pointer and data length (before > int32 pointers/data length would crash it)
- Minor simplifications
- Only use `Exec` instead of both directly wrapping `exec`
- Inline single/2-lines functions content in `exec`: `malloc`, `clear`, `store`, `load`
- Add sentinel errors and error wrappings
- Add named returns
#2418 
=> chore(lib/runtime/wasmer): refactor `Exec` and `exec` methods

cmd/gossamer/main.go, go.mod, go.sum
Valid CAs are built-in the Go binary and used if they are not found in the operating system.
So the Docker image doesn't need ca-certificates installed (whether it's Debian or Alpine or scratch).
Related #2693 
=> feat(build): add `github.com/breml/rootcerts`

dot/telemetry/mailer.go
Encountered the problem due to bad CAs in the Docker image, making it stall foreeever (and adding Prometheus/Grafana and all that)
- Time bound dialing (otherwise blocks for 30s+)
- Remove timer after failure
- Lower max retries from 5 to 3
Related to #2693
@timwu20
=> chore(telemetry): faster fail in case of dial error

dot/state/initialize.go, lib/runtime/wasmer/instance.go
The main goal (not yet achieved) is to get the runtime version from the wasm code byte slice **only**.
This moves one step closer, by having a shared `setupVM` function taking in only the wasm code.
- Fix: decompress WASM when checking runtime version
- Fix: clear allocator when closing instance
- Fix: add mutex protection for the entire `UpdateRuntimeCode` body
- Add and use new `close` method on `Instance` (without mutex)
- Use `close` method in `Stop` method
- `setupVM` only takes in the WASM code bytes and returns an instance+allocator
- WASM instance context data is set outside setupVM
- Minor changes
- Sentinel error for 'code is empty'
- Remove useless debug log (just logs pointer addresses)
- `Instance` named field `mutex` to find references easily
- Explicit runtime `Stop` call …
=> chore(lib/runtime/wasmer): common `setupVM` function

lib/runtime/interface.go, lib/runtime/storage/trie.go, lib/runtime/wasmer/imports.go
- Remove remaining function name prefixes in logs since the logger logs it already
- Remove returned error value from `ClearPrefix` which is always nil
#2052 
=> chore(wasmer): remove duplicate logged functions

internal/trie/node/header.go, internal/trie/node/header_test.go
Notable mentions:
- @timwu20 was right, a global scoped slice is faster, but for > 4 variants. V1 state trie will have 7.
- @EclesioMeloJunior thanks for suggesting the fixed size array which is also faster
Changes:
- Performance increases as number of variants increases
- Changed from slice to fixed size array (thanks Eclesio)
- Update comments
- Add test verifying slice is sorted by bit mask
- Update relevant benchmark for 7 variants
```sh
go test -tags integration github.com/ChainSafe/gossamer/internal/trie/node/...
```
@timwu20
=> feat(trie): faster header decoding with global scoped array of variants

dot/core/helpers_test.go, dot/core/service_integration_test.go, dot/core/service_test.go, dot/rpc/http_test.go, dot/rpc/modules/chain_integration_test.go, dot/rpc/modules/childstate_test.go, dot/services_integration_test.go, dot/services_test.go, dot/state/initialize.go, dot/state/storage.go, dot/state/storage_test.go, dot/sync/chain_processor_test.go, dot/sync/syncer_integration_test.go, lib/babe/babe_integration_test.go, lib/grandpa/grandpa_test.go, lib/runtime/storage/trie.go, lib/runtime/storage/trie_test.go, lib/runtime/wasmer/exports_test.go, lib/runtime/wasmer/imports.go, lib/runtime/wasmer/test_helpers.go
- Remove unneeded `newTestTrieState` helpers
- Remove several test no error assertions
- Remove some error checks for this function returns
Quick refactored whilst versioning the state trie all over the place
@edwardmack
=> chore(lib/runtime/storage): `NewTrieState` not returning an error

.golangci.yml, dot/import_test.go, dot/node_test.go, dot/services_test.go, dot/state/grandpa_test.go, dot/sync/chain_processor_test.go, dot/sync/chain_sync.go, internal/pprof/server_test.go, internal/trie/node/header_test.go, lib/grandpa/message_handler_test.go, lib/runtime/wasmer/imports.go, tests/rpc/rpc_01-system_test.go, tests/rpc/rpc_02-author_test.go, tests/rpc/rpc_03-chain_test.go, tests/rpc/rpc_04-offchain_test.go, tests/rpc/rpc_05-state_test.go, tests/rpc/rpc_06-engine_test.go, tests/rpc/rpc_07-payment_test.go, tests/rpc/rpc_08-contracts_test.go, tests/rpc/rpc_09-babe_test.go, tests/rpc/system_integration_test.go
- Fix issues caused by fixed `tparallel`
- Fix issues caused by fixed `lll`
- Add exclude rules for `lll` for C imports
=> fix(lint): fix issues found by golangcilint 1.47.3

tests/utils/node/nodes.go
Move code block waiting for nodes after setting up watchers for runtime errors.
Otherwise we end up with a deadlock as seen at https://github.com/ChainSafe/gossamer/runs/7469835105?check_suite_focus=true when one of the nodes crash (I don't know why one of the nodes crash for now, this should log why)
@timwu20
=> fix(tests): handle node crash during waiting

go.mod, go.sum
- upgrade chaindb to last master commit
- removes trace logs from badgerdb in tests 
```sh
```
@qdm12
=> fix(deps): upgrade chaindb to remove badger logs

codecov.yml
This is changed such that changing a single line without covering it won't make the CI 🔴 (note the codecov patch is not a required workflow though).
@timwu20
=> chore(ci): disable Codecov patch status

dot/core/mocks_runtime_test.go, dot/rpc/subscription/listeners_test.go, dot/state/block.go, dot/sync/mock_instance_test.go, lib/blocktree/mock_instance_test.go, lib/runtime/interface.go, lib/runtime/mocks/instance.go, lib/runtime/wasmer/imports.go, lib/runtime/wasmer/instance.go, lib/runtime/wasmer/instance_test.go
Blocked by #2686 and #2685
- `CheckRuntimeVersion` as function instead of instance method
- No dependency on existing instance
- Fix: do not modify parent instance allocator
- Fix: close temporary instance on exit
- Remove `CheckRuntimeVersion` from Instance interface
- `ext_misc_runtime_version_version_1` uses `CheckRuntimeVersion`
#2418 
@timwu20
=> chore(lib/runtime): `CheckRuntimeVersion` independent from existing runtime instance

dot/core/helpers_test.go, dot/core/service.go, dot/core/service_integration_test.go, dot/rpc/http_test.go, dot/rpc/modules/author_integration_test.go, dot/rpc/modules/chain_integration_test.go, dot/services.go, dot/services_integration_test.go, dot/services_test.go, dot/state/block.go, dot/state/initialize.go, dot/sync/syncer_integration_test.go, lib/babe/babe_integration_test.go, lib/grandpa/grandpa_test.go, lib/runtime/types.go, lib/runtime/wasmer/config.go, lib/runtime/wasmer/exports_test.go, lib/runtime/wasmer/instance.go, lib/runtime/wasmer/test_helpers.go
Move `InstanceConfig` from `lib/runtime` to `Config` in `lib/runtime/wasmer`
This is so private fields can be added for test-only in the wasmer package (blocks #2747)
#2418 
@timwu20
=> chore(runtime): move `InstanceConfig` to `lib/runtime/wasmer`

pkg/scale/encode.go, pkg/scale/encode_test.go, pkg/scale/varying_data_type_test.go
- Change `encodeState` to use `io.Writer` instead of `bytes.Buffer`
- Define `Encoder` with `Encode(value interface{}) error` method
- Define constructor `NewEncoder(writer io.Writer) *Encoder`
- Add unit tests for encoder
```sh
go test github.com/ChainSafe/gossamer/pkg/scale
```
Fixes #1897
~Blocks PR #2673 which (long shot) blocks #2418~
@timwu20
=> feat(pkg/scale): add `Encoder` with `Encode` method

cmd/gossamer/config.go, cmd/gossamer/config_test.go, cmd/gossamer/flags.go, cmd/gossamer/main.go, dot/config_test.go, internal/log/level.go, internal/log/level_test.go, internal/log/log.go, internal/log/log_test.go
There were spelling errors in the log levels to maintain a constant string length for all the levels. I have fixed spelling and added padding to make it cleaner and maintain consistency.
```sh
go test ./internal/log
```
@qdm12
=> chore(log): fix spelling and add padding for logger

dot/rpc/modules/state.go, dot/rpc/subscription/listeners.go, dot/rpc/subscription/listeners_test.go
- Add new conversion function `NewStateRuntimeVersionResponse`
- Inline `modules.ConvertAPIs` content in `NewStateRuntimeVersionResponse`
- Replace all conversions with `NewStateRuntimeVersionResponse`
- Update tests to have explicit expected API items to remove `modules.ConvertAPIs`
```sh
```
Created from a comment in #2673 
@timwu20
=> chore(dot/rpc): `NewStateRuntimeVersionResponse`

.github/workflows/unit-tests.yml, devnet/cmd/update-dd-agent-confd/main_test.go
Devnet tests were not run previously.
@timwu20
=> fix(ci): run devnet unit tests in workflow

chain/dev/config.toml, chain/dev/defaults.go, chain/gssmr/config.toml, chain/gssmr/defaults.go, dot/config_test.go, dot/utils_test.go
- Change the default values to always use the raw genesis instead of the human-readable genesis file
Execute `./bin/gossamer init --force` and you should be able to initialize the node
- Closes #2770
@danforbes
=> feat(chain): use always the raw genesis file

dot/core/messages_integration_test.go, dot/core/mocks_runtime_test.go, dot/core/service.go, dot/core/service_integration_test.go, dot/state/block.go, dot/sync/mock_instance_test.go, lib/babe/build_integration_test.go, lib/blocktree/mock_instance_test.go, lib/runtime/interface.go, lib/runtime/mocks/instance.go, lib/runtime/test_helpers.go, lib/runtime/types.go, lib/runtime/version.go, lib/runtime/version_test.go, lib/runtime/wasmer/config.go, lib/runtime/wasmer/exports.go, lib/runtime/wasmer/exports_test.go, lib/runtime/wasmer/instance.go, lib/runtime/wasmer/test_helpers.go
Note this caches the state version for usages in several import functions (see #2664)
- Set when creating instance
- Update when updating runtime code
```sh
go test -tags integration github.com/ChainSafe/gossamer/lib/runtime/...
```
One more step towards #2418
@timwu20
=> feat(wasmer): get and cache state version in instance context

dot/network/helpers_test.go, dot/network/light.go, dot/network/notifications.go, dot/network/notifications_test.go, dot/network/stream_manager.go, dot/network/sync.go
added the log of the errors returned from `stream.Close()`.
```sh
```
Fixed #2376
@timwu20
=> chore(dot/network): log the errors from `stream.Close()`

dot/core/interface.go, dot/core/mocks_test.go
Problem caused by merging #2747 on top of #2777 without rebasing (and there were no file conflicts)
@jimjbrettj
=> fix(dot/core): `RuntimeInstance` interface `Version` signature

dot/rpc/modules/dev_integration_test.go, dot/state/initialize.go, dot/state/offline_pruner.go, dot/state/service.go, dot/state/tries.go, dot/state/tries_test.go, lib/grandpa/grandpa_test.go
- `NewTries` does not return an error (always nil)
- `NewTries` does not take an initial as argument (which won't get versioned)
- Add `(*Tries) SetEmptyTrie()` method (which won't get versioned)
- Add `(*Tries) SetTrie(*trie.Trie)` method (which **will** get versioned)
This PR is because the empty trie is the same for v0 and v1 state versions.
So we want a method `SetEmptyTrie` on Tries which doesn't require a state version, and another method `SetTrie` which does.
This allows to have way less code changes in the next chunky PR versioning trie calls.
```sh
```
#2418 
=> chore(dot/state): refactor `NewTries`

dot/core/errors.go, dot/core/helpers_test.go, dot/core/service.go, dot/core/service_test.go, dot/mock_node_builder_test.go, dot/node.go, dot/node_test.go, dot/services.go, dot/services_integration_test.go, dot/services_test.go, dot/sync/errors.go, dot/sync/syncer.go, dot/sync/syncer_test.go, lib/babe/babe.go, lib/babe/build.go, lib/babe/build_integration_test.go, lib/babe/errors.go, lib/babe/verify.go, lib/babe/verify_integration_test.go, lib/babe/verify_test.go, lib/blocktree/errors.go, lib/grandpa/errors.go, lib/grandpa/grandpa.go, lib/grandpa/vote_message_test.go
The main reason is that adding empty fields all over in tests to pass those constructors is just plain annoying. And our production code doesn't need them at all since all of these are programming errors only.
Now if for some reason someone would use our go api and leave one of the field to nil, it would panic which is better than an error since it's really a programming error. See https://engineering-handbook.onrender.com/development/tech-stack/go#panic
Added side benefits are:
- a lot of red in this PR
- a few function signatures simplified/not returning an error anymore
This helps simplify some of the changes in tests for #2774
=> chore(all): remove nil checks for constructors

dot/core/errors.go, dot/sync/errors.go
=> chore(dot): remove unneeded error functions

cmd/gossamer/config.go, cmd/gossamer/flags.go, dot/config.go, dot/config/toml/config.go
Really just a tiny small thing I worked on as part of the trie versioning somewhere sometime.
- Change rewind flag to be `uint` instead of `int`
- Add `setStateConfig` with toml precedence over flags
- Add String() method to dot `StateConfig`
- Add `StateConfig` to `dot/config/toml`
=> chore(config): improve `StateConfig`

dot/state/storage.go, lib/trie/database.go, lib/trie/database_test.go
- lib/trie: remove unused trie method `PutInDB`
- lib/trie: remove test-only trie methods `DeleteFromDB` and `ClearPrefixFromDB` and move them inline in trie tests
- dot/state: do not do type assertion on pruner every time
=> chore(lib/trie): database.go small simplifications

lib/runtime/wasmer/config.go, lib/runtime/wasmer/config_test.go
> It seems the latest update to the testsuite breaks support for runtimes without Core_version and the [workaround](https://github.com/ChainSafe/gossamer/blob/78a1dbd88907d91662dffbfa35c5c00afdb26cb4/lib/runtime/wasmer/test_helpers.go#L55) is only available to your testsuite. Is there any way we could access to this or to only cache the version the first time it is requested?
Adds an exported method for external test suites to fiddle with the test version
Fixes #2816 
@timwu20
=> feat(wasmer): Add `SetTestVersion` method to `Config` struct

lib/trie/trie.go, lib/trie/trie_test.go
Why:
- Prefix is always inject as `nil`
- Working of `deleteNodesLimit` given a `prefix` was wrong
Also because I'm reviewing trie node snapshotting and found this which was troublesome in another branch. I prefer to keep it simpler and remove the prefix functionality than fixing it since there is no use for it.
```sh
```
=> chore(lib/trie): `deleteNodesLimit` takes no `prefix`

dot/state/block_data_test.go, dot/state/block_finalisation_test.go, dot/state/block_notify_test.go, dot/state/block_test.go, dot/state/epoch_test.go, dot/state/storage_notify_test.go, dot/state/storage_test.go
Tiny simplification for test helper always taking `newEmptyTries()` argument
=> chore(dot/state): `newTestStorageState` does not take `tries` argument

chain/dev/config.toml, chain/dev/defaults.go, chain/gssmr/config.toml, chain/gssmr/defaults.go, chain/kusama/config.toml, chain/kusama/defaults.go, chain/polkadot/config.toml, chain/polkadot/defaults.go, cmd/gossamer/config.go, dot/config.go, dot/config_test.go
- Flag value is used first
- TOML config value is then used
- Default value is ignored (always `false`)
- Remove default pprof enabled values
=> fix(config): temporary fix for pprof enabled setting precedence

dot/state/offline_pruner.go, dot/state/pruner/pruner.go, dot/state/storage.go, lib/runtime/storage/trie.go, lib/trie/database.go, lib/trie/trie.go, lib/trie/trie_endtoend_test.go, lib/trie/trie_test.go
The problem is as follows in this example.
For a node `A` encoding to `{1, 2}`, its database key is `{0, 0, 0, ..., 1, 2}`. Another node `B` with > 32B encoding could (unlikely but still) hash to the same value `{0, 0, 0, ..., 1, 2}` as for `A` and that would conflict in the database.
The solution is to NOT force the database key to be 32B always, and to keep it plainly as the Merkle value of the node (32B or less). This should also occupy less space in the database eventually.
- Storage KV database node key has now the length of the Merkle value and is no longer forced to 32B
- Renaming `XXXHashesSet` to `XXXMerkleValues` since it's not just hashes
- Renaming `deletedKeys` to `deletedMerkleValueToBlockNumber` in `dot/state`
- Renaming methods `XXXNodeHashes` to `XXXMerkleValues`
```sh
go …
```
=> fix(trie): use direct Merkle value for database keys

dot/sync/chain_processor.go, dot/sync/chain_processor_integration_test.go, dot/sync/chain_processor_test.go
- Remove nil check on header and justification (unused, see caller checks - and caller should be the ones checking what they pass down)
- Return wrapped errors to callers
- Change callers to handle non-nil errors and return them up the call stack
- Adapt tests
```sh
go test -tags integration github.com/ChainSafe/gossamer/dot/sync/...
```
@noot
=> chore(dot/sync): `handleJustification` returns errors

internal/trie/node/subvalue.go, internal/trie/node/subvalue_test.go, lib/trie/trie.go, lib/trie/trie_test.go
Done whilst working on the online pruning / lazy loading stuff.
EDIT: actually rather needed for the lazy loading
- Only prepare nodes for mutation if mutation is guaranteed
- **Fixes 'reported deleted hashes' when no mutation is done**, indirectly fixing the online pruning that would previously prune database keys that may still be in use.
- Add comment on `deletedKeys` trie struct field
- Update tests to maintain full test coverage on trie code
```sh
```
#2836 which blocks #2838 
@timwu20
=> fix(lib/trie): prepare trie nodes for mutation only when needed

dot/digest/digest.go
This is not an error. We are iterating over all digests and picking consensus digests. It is completely fine to see other types of digests.
```sh
```
@timwu20
=> remove `digest type not supported` error

.github/workflows/fuzz.yml, dot/state/helpers_test.go, lib/trie/helpers_test.go, lib/trie/trie_endtoend_test.go
- Change trie put/get fuzz test to create a new trie per fuzz run, instead of using the same trie (to avoid OOM)
- Add unit test to test put/get with the same trie and 60000 key value pairs
```sh
go test -fuzz=Fuzz_Trie_PutAndGet_Single -fuzztime=1m github.com/ChainSafe/gossamer/lib/trie
```
=> chore(lib/trie): split fuzz testing of the trie

dot/import.go, dot/node_integration_test.go, lib/runtime/wasmer/exports_test.go, lib/runtime/wasmer/genesis.go, lib/trie/trie.go, lib/trie/trie_test.go
- Trie mutation should be transactional/atomic as a method, in case an error occurs
- Changed from method to function to avoid leaving a trie in a bad state
- Function returns a new empty trie with all the key and value pairs given
This will become important for lazy loading where a disk write operation could fail for real.
```sh
go test -tags integration github.com/ChainSafe/gossamer/lib/trie/...
```
Related to #2838 
@jimjbrettj
=> chore(lib/trie): `LoadFromMap` as function for transactional trie mutation

pkg/scale/encode.go, pkg/scale/encode_test.go
- Removed sorting logic for map keys in encodeMap method as @timwu20 suggested over [here](https://github.com/ChainSafe/gossamer/pull/2894#discussion_r1005921855) in PR #2894 .
```sh
```
@timwu20
=> enhancement(pkg/scale): remove sorting logic from encodeMap method

dot/state/offline_pruner.go, lib/trie/database.go, lib/trie/database_test.go
- Include Merkle value of the parent node passed as argument
- Update comment all nodes are expected to have their Merkle value computed
- Enforce all nodes to have their Merkle value computed with a `panic` (this will be thrown out with lazy loading)
- Add unit test
For now this only affects the offline pruning, but this function is to be used in another PR to fix the tracking of deleted Merkle values and add cached tracking of inserted Merkle values
```sh
go test github.com/ChainSafe/gossamer/lib/trie/...
```
Related to #2854 
=> fix(trie): `PopulateMerkleValues` behavior

internal/trie/node/branch_encode.go, internal/trie/node/hash.go, internal/trie/pools/pools.go, lib/trie/trie.go
Removes the encoding sync pool of buffers and use simple inlined GC'ed buffers instead.
Until now encoding of nodes was using a `sync.Pool` of memory buffers.
The first obvious problem was that (shame on my past self) each buffer would take 1.9MB to have enough room for the larger encoding seen in production. That means that if encoding is fast CPU wise, a lot of 1.9MB buffers would be created and held by the pool for a period at least longer than a GC cycle. Even if these are re-used, this might still represent a lot of memory, which could be the reason of the 35% memory usage due to `encodeIfNeeded` from heap profiles.
The first solution which came to my mind was to reduce the encoding buffer size to, say, 32B. But in the end there is no known-in-advance size for the encoding. It could …
=> fix(trie): remove encoding buffers pool

dot/core/helpers_test.go, dot/core/interface.go, dot/core/messages.go, dot/core/messages_integration_test.go, dot/core/mocks_test.go, dot/core/service.go, dot/core/service_integration_test.go, dot/core/service_test.go, dot/rpc/modules/api.go, dot/rpc/modules/mocks/block_api.go, dot/rpc/modules/mocks_test.go, dot/rpc/modules/payment.go, dot/rpc/modules/payment_integration_test.go, dot/rpc/modules/payment_test.go, dot/rpc/modules/state_integration_test.go, dot/services.go, dot/state/block.go, dot/state/test_helpers.go, dot/sync/chain_processor.go, dot/sync/chain_processor_integration_test.go, dot/sync/chain_processor_test.go, dot/sync/interface.go, dot/sync/mocks_test.go, lib/babe/babe.go, lib/babe/babe_integration_test.go, lib/babe/build_integration_test.go, lib/babe/mock_state_test.go, lib/babe/state.go, lib/babe/verify_integration_test.go, lib/grandpa/grandpa_test.go
The aim was to better see the use of the blockstate `GetRuntime` method.
There is no hurry to merge this, but it could be a nice addition imo.
- No longer a mix of passing best block hashes and nils
- Force the caller to get the best block hash (also to reduce getting the best block hash N times in loops)
- Rename some hash variable names
- Deduplicate copied-pasted code in dot/core.
=> chore(blockstate): change `GetRuntime` to take `common.Hash` as argument

dot/state/storage.go, lib/runtime/storage/trie.go, lib/trie/database.go
5 minutes work related to #2831
=> chore(trie): `GetChangedNodeHashes` returns both inserted and deleted node hashes

Dockerfile.staging
- move `datadog-agent start` to beginning on entrypoint 
- this is how we do it in the devnet folder
- push to staging and ensure docker builds image successfully
- ensure nodes are updated on staging
@qdm12
=> fix(staging): revise datadog-agent start process

copyright.txt
A bit late, but oh well better than 2021 -> 2023!
@danforbes
=> chore: bump copyright notice year to 2022

internal/trie/node/branch_encode.go, internal/trie/node/branch_encode_test.go, internal/trie/node/encode.go, internal/trie/node/encode_test.go, lib/trie/trie_test.go
Use the `pkg/scale`'s `Encoder` to write directly to the target buffer instead of copying around.
Proposed by Tim at https://github.com/ChainSafe/gossamer/pull/2927/files#r1015941438
```sh
go test -tags integration github.com/ChainSafe/gossamer/lib/trie/... github.com/ChainSafe/gossamer/internal/trie/...
```
Fixes #2755 
@timwu20
=> feat(trie): use scale encoder

dot/rpc/modules/author_integration_test.go
```sh
go test -timeout 300s -run ^TestAuthorModule_HasSessionKeys_Integration$ github.com/ChainSafe/gossamer/dot/rpc/modules -v -tags integration
```
=> `TestAuthorModule_HasSessionKeys_Integration` does not data race anymore

dot/state/base_test.go, dot/state/initialize.go, dot/state/service.go, dot/state/service_test.go, lib/runtime/wasmer/imports_test.go, lib/trie/database.go, lib/trie/database_test.go, lib/trie/proof/proof_test.go, lib/trie/trie_endtoend_test.go
- `WriteDirty` is just the clever version of `Store`, where we write only nodes that got changed in-memory from the version we have in the database.
- This also ensures all the nodes are set as dirty correctly
```sh
go test -tags integration github.com/ChainSafe/gossamer/...
```
Trying to fix up strange root hash mismatch panic found in #2919 
@timwu20
=> chore(lib/trie): remove `Store` method

dot/state/storage_test.go, dot/state/tries_test.go, internal/trie/node/branch_encode_test.go, internal/trie/node/copy.go, internal/trie/node/copy_test.go, internal/trie/node/decode.go, internal/trie/node/decode_test.go, internal/trie/node/encode.go, internal/trie/node/encode_decode_test.go, internal/trie/node/encode_test.go, internal/trie/node/hash_test.go, internal/trie/node/header.go, internal/trie/node/header_test.go, internal/trie/node/node.go, internal/trie/node/node_test.go, lib/trie/database.go, lib/trie/database_test.go, lib/trie/genesis_test.go, lib/trie/print_test.go, lib/trie/proof/generate.go, lib/trie/proof/generate_test.go, lib/trie/proof/verify_test.go, lib/trie/trie.go, lib/trie/trie_endtoend_test.go, lib/trie/trie_test.go
See title
```sh
go test -tags integration github.com/ChainSafe/gossamer/lib/trie github.com/ChainSafe/gossamer/internal/trie/...
```
@timwu20
=> chore(trie): `Key` -> `PartialKey` for nodes

dot/sync/block_queue.go, dot/sync/block_queue_test.go, dot/sync/chain_processor.go, dot/sync/chain_processor_integration_test.go, dot/sync/chain_processor_test.go, dot/sync/chain_sync_test.go, dot/sync/errors.go, dot/sync/tip_syncer_integration_test.go
- `processBlockData`:
- Split subblocks into functions:
- `processBlockDataWithHeaderAndBody` function with test
- `processBlockDataWithStateHeaderAndBody` function with test
- takes block data `blockData` as value argument instead of pointer
- Review error wrappings
- Remove block data nil check
- Rename receiver from `s` to `c` for `chainProcessor`
- Remove unneeded unit test cases for `processBlockData` (now covered in subfunctions associated tests)
- Push (possibly unneeded) justification length check up in caller of `handleJustification`.
- Return error on block import error
- Fix position of debug logs
Done whilst fixing tests in #2774 
:new: is kinda blocking me on #2912 (trying to fix the memmm)
```sh
go test -tags integration github.com/ChainSafe/gossamer/dot/sync
```
@edwardmack
=> chore(dot/sync): simplify `processBlockData` and associated tests

lib/runtime/wasmer/imports.go, lib/runtime/wasmer/imports_test.go
- If the value is `[]byte{}`, the key exists (leaf node, branch with value)
- If the value is `[]byte(nil)`, the key does not exist (node not found or branch without value)
- Change unit test to be cases-based and add case
```sh
go test -run ^Test_ext_storage_exists_version_1$ github.com/ChainSafe/gossamer/lib/runtime/wasmer
```
@timwu20
=> fix(wasmer): `ext_storage_exists_version_1` for empty values

dot/core/helpers_test.go, dot/core/service_integration_test.go, dot/rpc/modules/author_integration_test.go, dot/rpc/modules/childstate_integration_test.go, dot/rpc/modules/childstate_test.go, dot/rpc/modules/state_integration_test.go, dot/rpc/modules/system_integration_test.go, dot/state/storage_notify_test.go, dot/state/storage_test.go, dot/state/test_helpers.go, lib/runtime/interface.go, lib/runtime/storage/trie.go, lib/runtime/storage/trie_test.go, lib/runtime/wasmer/exports_test.go, lib/runtime/wasmer/helpers.go, lib/runtime/wasmer/imports.go, lib/runtime/wasmer/imports_test.go, lib/trie/child_storage.go, lib/trie/child_storage_test.go, lib/trie/database_test.go
For consistency with trie method `Put`, this changes `TrieState`'s method name from `Set` to `Put`.
=> chore(dot/state): rename `Set` method to `Put` to match trie method name

pkg/scale/encode.go
- The `encodeArray` comment was describing it wrong
N/A
Closes #2975
@timwu20
=> chore: fix `encodeArray` comment removing wrong explanation

dot/peerset/peerset.go
- Added check for error `ErrIncomingSlotsUnavailable` and logging condition to Info logs, since this happens when the peer set has filled it's incoming slot allowance.
- Fix spelling of `incomming` to `incoming` in log message.
```sh
go test github.com/ChainSafe/gossamer/dot/peerset
```
closes #2914 
@timwu20
=> fix(peerset): check for incoming slot error

pkg/scale/encode.go, pkg/scale/encode_test.go
- Useful for tests
- Useful when input is predictable/fixed
:information_source: Not going to refactor anything, but it's a nice-to-have for new code I'd say.
```sh
go test -run ^Test_MustMarshal$ github.com/ChainSafe/gossamer/pkg/scale
```
@timwu20
=> feat(scale): add `MustMarshal` function

dot/network/discovery.go
It appears the `findPeers` is bugged as far as I have seen (kinda randomly)
Previously it was waiting for the timeout timer to expire OR for a peer to be found. If a peer would be found, it would stop the timer which would lead to an infinite loop waiting on new peers. I think what we want is to collect peers during the timer timeout, especially since `findPeers` is called by `checkPeerCount` with a ticker.
This PR changes it to NOT stop the timer when finding a peer, such that the function `findPeers` returns when the timer expires.
=> fix(dot/network): `findPeers` returns on timeout if a peer is found

dot/network/discovery.go, dot/network/notifications.go, dot/network/transaction.go, internal/metrics/metrics.go, lib/babe/babe.go, lib/babe/epoch_handler.go, lib/babe/epoch_handler_test.go, lib/grandpa/finalisation.go, tests/rpc/system_integration_test.go, tests/stress/helpers.go, tests/stress/stress_test.go
:sob: Sorry I've been wrong and annoying everyone with draining timer channels when stopping them...
Basically (duh) a channel is just like any other pointer, so if it goes out of scope it gets GC'd. There is no need to drain it, even if it's buffered, as long as it goes out of scope, it'll get GC'd. So that means timers don't need to have their channels drained. The only reason to drain them (the timer documentation isn't so clear on that) is to reset them, which we don't use at all in our codebase (except once where the timer already expired and was drained)
=> chore(all): remove unneeded timer channel drains

internal/trie/node/copy.go, lib/trie/trie.go
- `CopyCached` -> `CopyMerkleValue` (since we don't cache the encoding anymore)
- `CopyKey` -> `CopyPartialKey`
- ~`CopyValue` -> `CopyStorageValue`~
- Update comments
@jimjbrettj
=> chore(trie): update copy settings fields and comments

dot/types/grandpa.go, dot/types/grandpa_test.go
- Add an equivocation type to create a wrapper around signed grandpa votes for proper encoding/decoding in runtime calls. This mimicks substrate as seen here https://crates.parity.io/sp_finality_grandpa/enum.Equivocation.html
```sh
go test ./dot/types 
```
#2933
@timwu20
=> dot/types: add equivocation vdt

internal/trie/node/branch_encode.go, internal/trie/node/branch_encode_test.go
Do not get a buffer from the sync pool for each `nil` child of a branch
:question: why? Because this might request the creation of many buffers (allocated as 1.9MB - changing this in #2929) which are not needed, and GC of sync.Pool takes potentially longer than non-pool local buffers.
:question: :question: this would likely reduce memory usage, but #2929 is likely more of a nail in the coffin. Although for clarity and small performance gains, I think it's better we still merge this.
```sh
go test -tags integration github.com/ChainSafe/gossamer/lib/trie/... github.com/ChainSafe/gossamer/internal/trie/...
```
#1936 
@timwu20
=> fix(trie): do not get/create buffer for nil child

dot/state/test_helpers.go, lib/runtime/interfaces.go, lib/runtime/storage/trie.go, lib/runtime/wasmer/helpers.go, lib/runtime/wasmer/helpers_test.go, lib/runtime/wasmer/imports.go, lib/runtime/wasmer/interfaces.go, lib/trie/child_storage.go, lib/trie/helpers_test.go, lib/trie/trie.go, lib/trie/trie_endtoend_test.go, lib/trie/trie_test.go
- Record Merkle values deleted only if they are NOT 'dirty' (the same as in the last trie snapshot)
- Record Merkle values deleted when one or more nodes are deleted from the trie
- Do NOT record Merkle values of inlined nodes in the deleted set of Merkle values
- Lazy calculate Merkle values if they are missing (especially for delete operations)
- Update tests to have full trie.go coverage again (except hashing error due to the buffer sync pools at global scope)
- Fix preparing branch for mutation only once before for loop (instead of N times)
- Check errors from merkle value computation (useful for lazy loading to handle database errors)
Eventually add more test cases to test for correct registration of deleted Merkle values, but meh might not be that useful with incoming lazy loading …
=> fix(lib/trie): record deleted Merkle values fixed

lib/grandpa/grandpa.go
Fix a typo in the `logger.Errorf` message
N/A
N/A
@timwu20
=> fix(lib/grandpa):`logger.Errorf` message format typo

dot/types/babe_digest.go, dot/types/consensus_digest.go, dot/types/digest.go, dot/types/grandpa.go, lib/babe/errors.go, lib/babe/errors_test.go, lib/babe/parachain_inherents.go, lib/grandpa/message.go, lib/runtime/invalid_transaction.go, lib/runtime/unknown_transaction.go, lib/runtime/wasmer/imports.go, pkg/scale/varying_data_type.go, pkg/scale/varying_data_type_example_test.go, pkg/scale/varying_data_type_nested_example_test.go, pkg/scale/varying_data_type_nested_test.go, pkg/scale/varying_data_type_test.go
As proposed by Eclesio in https://github.com/ChainSafe/gossamer/pull/2965#discussion_r1028345455
1. ~`VaryingDataTypeValue` interface is now composed of `fmt.Stringer`~
2. Add missing `String() string` methods to types needing to implement `VaryingDataTypeValue`
3. Add `String() string` method on `VaryingDataType` struct
4. Add `String() string` method on `VaryingDataTypeSlice` struct
A few more steps towards #1945 
=> feat(pkg/scale): `VaryingDataTypeValue` String method

tests/rpc/rpc_03-chain_test.go
- Wait for Gossamer to produce a new block ahead of the finalized one
```sh
MODE=rpc go test -timeout 10m -run ^TestChainRPC$ github.com/ChainSafe/gossamer/tests/rpc --tags=integration -v
```
- Closes #3041
@jimjbrettj
=> fix(tests/rpc): ensure new blocks are created before assert

dot/rpc/modules/state.go, tests/rpc/rpc_05-state_test.go
- Fixes the assertion problems in the `TestStateRPCAPI` test
```sh
MODE=rpc go test -timeout 10m -run ^TestStateRPCAPI$ github.com/ChainSafe/gossamer/tests/rpc --tags=integration -v
```
- Closes #3029
@qdm12
=> fix(test/rpc): use `westend-local` in `TestStateRPCAPI`

tests/polkadotjs_test/start_polkadotjs_test.go, tests/polkadotjs_test/test/test-polkadot.js
- Fix assertion problems in the polkadot.js test suite
```sh
MODE=polkadot go test -timeout 10m -run ^TestStartGossamerAndPolkadotAPI$ github.com/ChainSafe/gossamer/tests/polkadotjs_test --tags=integration -v
```
- Closes #3023
@jimjbrettj
=> fix(tests/polkadot_js): Use `westend-local` to run polkadot js test suite

devnet/cmd/scale-down-ecs-service/mocks_generate_test.go, devnet/cmd/scale-down-ecs-service/service_scaler_test.go, dot/digest/interfaces.go, dot/digest/mocks_generate_test.go, dot/mocks_generate_test.go, dot/network/mocks_generate_test.go, dot/network/transaction_integration_test.go, dot/node.go, dot/node_test.go, dot/rpc/http_test.go, dot/rpc/mocks_generate_test.go, dot/services_test.go, dot/state/mocks_generate_test.go, dot/state/tries_test.go, internal/httpserver/mocks_generate_test.go, internal/httpserver/server_test.go, internal/pprof/mocks_generate_test.go, internal/pprof/server_test.go, internal/pprof/service_test.go, internal/trie/node/buffer.go, internal/trie/node/key_test.go, internal/trie/node/mocks_generate_test.go, lib/babe/mocks_generate_test.go, lib/babe/state.go, lib/services/mocks_generate_test.go, lib/services/services.go
Grouping all `//go:generate mockgen` instructions in `mocks_generate_test.go` files.
This:
- removes ambiguity as to where to place mock generation commands (in test files, above interfaces, duplicate them etc.)
- allow to further refactor mock generation and interfaces re-structuration
@jimjbrettj
=> chore(mocks): move `go:generate mockgen` to `mocks_generate_test.go`

internal/trie/tracking/deltas.go, internal/trie/tracking/deltas_test.go, internal/trie/tracking/helpers_test.go, internal/trie/tracking/interfaces.go, lib/trie/database.go, lib/trie/helpers_test.go, lib/trie/interfaces.go, lib/trie/trie.go, lib/trie/trie_endtoend_test.go, lib/trie/trie_test.go
This is done following Tim's comment https://github.com/ChainSafe/gossamer/pull/2873#discussion_r996237239 ~and (performance) discoveries whilst working on #2881 - this unblocks #2881~
- Define `Deltas` struct in `internal/trie/tracking` (with unit tests)
- Replace passing of a plain Go `map[string]struct{}` by passing `pendingDeltas DeltaRecorder` in the trie code
- Define trie local deltas interfaces
- ~Allows for extending functionality, since it's very much needed in #2881~
```sh
go test -tags integration ./lib/trie/...  ./internal/trie/tracking/... 
```
Unblocks ~#2854~ and #2838 
@timwu20
=> chore(lib/trie): add `Deltas` in `internal/trie/tracking`

cmd/gossamer/main.go, dot/node_integration_test.go, dot/node_test.go, lib/keystore/helpers.go, lib/keystore/helpers_test.go
From Eclesio's suggested changes in #2867 
Change `lib/keystore`'s `LoadKeystore` to be more 'explicit', injecting the keyring as an argument, and moving the empty account key check up in the call stack.
```sh
```
=> chore(lib/keystore): `LoadKeyStore` more explicit

.github/workflows/unit-tests.yml, lib/trie/mem_test.go
- Fix `mutateTrieLeavesAtPrefix` (shame on previous me!)
- Fix `mutateTrieLeavesAtPrefix` to work with empty values
- Tigthen ratio brackets to newer values
- Add trie memory workflow step
@timwu20
=> chore(trie): add trie heap usage workflow step

lib/babe/babe.go, lib/babe/babe_integration_test.go, lib/babe/epoch_handler.go, lib/babe/epoch_handler_test.go
- Pass in slot to slot handler rather than declare it in the function
- Instead of using time.Now() use the slot start time as the start field of Slot
```sh
go test -tags integration lib/babe
```
=> fix(lib/babe): use slot start time in handleSlot

dot/digest/digest_integration_test.go, dot/digest/helpers_test.go, dot/helpers_test.go, dot/rpc/helpers_test.go, dot/rpc/http_test.go, dot/services_integration_test.go, dot/services_test.go, dot/state/helpers_test.go, dot/state/service_integration_test.go, dot/state/storage_test.go, dot/sync/syncer_integration_test.go, lib/grandpa/helpers_integration_test.go
- Rename test helper function `newTestGenesisWithTrieAndHeader` with `newWestendDevGenesisWithTrieAndHeader`
N/A
@jimjbrettj
=> chore(tests): rename test helper function `newTestGenesisWithTrieAndHeader`

dot/state/offline_pruner.go, dot/state/pruner/pruner.go, dot/state/storage.go, lib/runtime/storage/trie.go, lib/trie/database.go, lib/trie/database_test.go, lib/trie/proof/generate.go, lib/trie/proof/verify.go, lib/trie/trie.go, lib/trie/trie_endtoend_test.go, lib/trie/trie_test.go
- Pruners only care about node hashes
- Rename variables, functions and methods only dealing with node hashes
- Do not write or read inlined nodes with a non-hash Merkle value
- Clarify error wrappings and comments
:information_source: this may feel familiar since I made previous PRs to rename node hashes -> merkle value, but it turned out it was not applicable for database related things (but only learnt/realised that recently).
```sh
```
@timwu20
=> fix(state): node hashes vs merkle values

tests/rpc/rpc_03-chain_test.go
- The following test `TestChainSubscriptionRPC/chain_subscribeNewHeads` was supposed to not be flaky due to this PR https://github.com/ChainSafe/gossamer/pull/3092, however, it seems to keep the unstable behavior.
- After a quick investigation the test method `GreaterOrEqual` expects the first argument be greater or equal the second and in the PR https://github.com/ChainSafe/gossamer/pull/3092 I just replace the method name without changing the argument order 😢 
```sh
MODE=rpc go test -timeout 10m -run ^TestChainSubscriptionRPC$ github.com/ChainSafe/gossamer/tests/rpc --tags=integration -v
```
N/A
@timwu20
=> fix(tests/rpc): place `GreaterOrEqual` arguments in the correct order at `chain_subscribeNewHeads` test

internal/mdns/mdns.go
- After this commit: https://github.com/whyrusleeping/mdns/commit/90e1930071ab6e5dc4388b54210152256ba07d37 is possible to disable the default logging in the `whyrusleeping/mdns` library we use
- Run a Gossamer node using the `westend` chain config and then you should not see these logs:
```
2023/02/22 15:43:16 [ERR] mdns: Failed to read packet: read udp4 0.0.0.0:63685: use of closed network connection
2023/02/22 15:43:16 [ERR] mdns: Failed to read packet: read udp4 0.0.0.0:5353: use of closed network connection
2023/02/22 15:43:16 [ERR] mdns: Failed to read packet: read udp6 [::]:60744: use of closed network connection
```
- Closes #3124
@timwu20
=> chore(internal/mdns): disable `mdns` package default logging

Dockerfile.staging
- set `DD_HOSTNAME` env variable
- datadog fails in ECS environment with latest version of datadog-agent
- push to staging workflow and ensure staging nodes start
@jimjbrettj
=> fix(ci): Fix staging metrics collection

lib/babe/babe_integration_test.go, lib/babe/verify_integration_test.go
- Fixed TestService_HandleSlotWithSameSlot and rewrote TestService_HandleSlotWithLaggingSlot
- Removed newVerificationManagerHelper as it was not necessary
```sh
go test ./lib/babe --tags=integration
```
#3060
=> chore(babe): fix skipped integration tests and remove unneeded test helper

cmd/gossamer/README.md, cmd/gossamer/account.go, cmd/gossamer/config.go, cmd/gossamer/config_test.go, cmd/gossamer/export.go, cmd/gossamer/export_test.go, cmd/gossamer/flags.go, cmd/gossamer/flags_test.go, cmd/gossamer/main.go, cmd/gossamer/main_test.go, cmd/gossamer/utils.go, cmd/gossamer/utils_test.go, dot/config.go, dot/config/toml/config.go, dot/network/config.go, dot/network/host.go, dot/network/service.go, dot/services.go, go.mod, go.sum
This PR contains changes to make gossamer more congruent with polkadot CLI commands in order to enable gossamer to work with paritytech zombienet testing framework.  
- Add CLI flag `no-mdns` to alias `nomdns`.
- Add CLI flag `base-path` to alias `basepath`
- Add CLI flag `rpc-port` to alias `rpcport`
- Add CLI flag `ws-port` to alias `wsport`
- Implement new CLI flag `node-key` which overrides the secret Ed25519 key to use for libp2p
- Add unit tests for new flags
```sh
go test github.com/ChainSafe/gossamer/cmd/gossamer -run ^TestGlobalConfigFromFlags$ -v
go test github.com/ChainSafe/gossamer/cmd/gossamer -run ^TestNetworkConfigFromFlags$ -v
go test github.com/ChainSafe/gossamer/cmd/gossamer -run ^TestRPCConfigFromFlags$ -v
```
Work done researching issue #2843 
@timwu20
=> feature(cmd/gossamer): add aliases for cli flags

chain/westend-local/config-alice.toml, cmd/gossamer/config.go, cmd/gossamer/flags.go, devnet/README.md, devnet/alice.Dockerfile, dot/config.go, dot/config/toml/config.go, dot/services.go, dot/utils_test.go, lib/babe/babe.go, lib/babe/babe_integration_test.go, lib/babe/errors.go, tests/polkadotjs_test/start_polkadotjs_test.go, tests/rpc/rpc_02-author_test.go, tests/rpc/rpc_03-chain_test.go, tests/rpc/rpc_04-offchain_test.go, tests/rpc/rpc_05-state_test.go, tests/rpc/rpc_06-engine_test.go, tests/rpc/rpc_07-payment_test.go, tests/rpc/rpc_08-contracts_test.go, tests/rpc/rpc_09-babe_test.go, tests/stress/grandpa_test.go, tests/stress/stress_test.go, tests/utils/config/config.go, tests/utils/node/node_test.go, tests/utils/node/nodes.go
- Removes babe-lead flag that prevents a node to create blocks until it receive the first one
```sh
make tests
```
- manual tests running nodes locally checking that all nodes are producing blocks using the same canonical chain
- also tested using zombienet
#3184 
@timwu20
=> refactor(cli): Remove babe-lead flag

dot/rpc/modules/state.go, dot/rpc/modules/state_test.go
NOTE: This PR replaces PR #3185, which has been replaced because that PR contained code merged from other branches not related to this implementation.  This PR contains all changes related to implementing state_queryStorageAt
- Implement code for RPC method `state_queryStorageAt` which returns storage values for given keys at best block or given block hash if `at` parameter is used.
- This fixes error `rpc: can't find method "state.QueryStorageAt"` that occurs when using polkadot.js/api methods in `api.query` package.
```sh
go test github.com/ChainSafe/gossamer/dot/rpc/modules -run ^TestStateModuleQueryStorageAt$ -v
```
closes: #3182 
@timwu20
=> feat(dot/rpc): implement RPC method state_queryStorageAt

dot/state/grandpa.go, dot/state/grandpa_test.go, dot/state/initialize.go, dot/state/service.go, dot/telemetry/afg_applying_forced_authority_set_change.go, dot/telemetry/afg_applying_scheduled_authority_set_change.go, dot/telemetry/telemetry.go, lib/grandpa/helpers_integration_test.go
Send telemetry metrics for scheduled and forced changes
```sh
make test
```
Closes #3218 
@EclesioMeloJunior @timwu20
=> feat(telemetry): Add scheduled and force changes telemetry metrics

dot/digest/digest.go, dot/digest/digest_integration_test.go, dot/digest/interfaces.go, dot/digest/mock_epoch_state_test.go, dot/state/epoch.go, dot/state/epoch_test.go, dot/types/consensus_digest.go, dot/types/consensus_digest_test.go, lib/babe/verify_integration_test.go
Adds support for NextConfigData versioning following the [substrate implementation](https://github.com/paritytech/substrate/blob/7d6084b5774ee13d0b33810c2830aa5a8506cbae/primitives/consensus/babe/src/digests.rs#L143C1-L152)
- Created `VersionedNextConfigData` to support different `NextConfigData` versions 
- Renamed the old `NextConfigData` as `NextConfigDataV1`
```sh
make test
```
Since I modified a current structure used in different tests 
Closes #3236 
@timwu20 @EclesioMeloJunior
=> fix(babe): Add support for versioned NextConfigData decoding

pkg/scale/decode_test.go, pkg/scale/encode_test.go, pkg/scale/errors.go, pkg/scale/scale.go, pkg/scale/scale_test.go
Changed the type of scaleIndex from `*string` to `*int`.
We have two options to solve the issue of string index comparison.
- Convert the string index to int at the time of comparison
- Store the int index instead of the string index
I decided to go with the latter since it will allow us to validate the scaleIndex before encoding/decoding a struct.
```sh
go test pkg/scale
```
#3268 
@timwu20
=> fix(scale): Use *int for scale index

pkg/scale/bitvec_test.go
Fixed a lint issue and a test in bitvec_test.go
```sh
```
=> Fix(lint): fixes a lint issue in bitvec-test

dot/network/host.go
- Introduce libp2p resource manager + Prometheus metrics to the `network` pkg
A little explanation of this library [go-libp2p/resource-manager](https://github.com/libp2p/go-libp2p/tree/master/p2p/host/resource-manager)
> The Resource Manager doesn't prioritize resource requests at all, it simply checks if the resource being requested is currently below the defined limits and returns an error if the limit is reached. It has no notion of honest vs bad peers.
- Running gossamer with libp2p resource manager + exposing the metrics through Prometheus. It is possible to see the number of streams in use per protocol:
- N/A
@timwu20
=> feat(dot/network): introduce libp2p resource manager + prometheus metrics

lib/parachain/statement.go, lib/parachain/statement_distribution_message.go
=> chore(parachain): improve comments of statement and statement distribution message

lib/utils/utils_test.go
Fixes utils test that was creating a path manually instead of relying on Go `filepath` package to do it based on OS.
On a mac and a windows machine:
```sh
go test -timeout 30s -run ^TestKeystoreDir$ github.com/ChainSafe/gossamer/lib/utils
```
Fixes #3367
@timwu20
=> fix test to pass on all OSs

lib/erasure/erasure_test.go
- Moved assertion that confirms expected chunks to only check when no error is expected since the expected chunks or not consistent when there is an error.
- added t.Parallel to tests
```sh
go test github.com/ChainSafe/gossamer/lib/erasure-coding -v
```
@kanishkatn
=> fix(lib/erasure): Move test assertion to non-error condition

dot/state/block_finalisation.go
Gossamer was taking too much time to load a state trie of the latest finalized block given that it was stored in the database and then pruned from memory. 
Is important for Gossamer to quickly load the state trie from the latest finalized block to keep the sync process at the normal speed, otherwise every finalization we will need to wait for Gossamer to load the entire trie from database which can be a bottleneck
```sh
```
N/A
@timwu20
=> feat(dot/state): keep latest state trie in memory

lib/runtime/allocator.go, lib/runtime/allocator_test.go
- This changes increases the amount of possible allocations from `2 ^ 24` to `2 ^ 25` as it is defined in substrate `primitives/core` 
```rs
pub const MAX_POSSIBLE_ALLOCATION: u32 = 33554432; // 2^25 bytes, 32 MiB
```
ref: https://github.com/paritytech/substrate/blob/2ca66197161b3b5c4e2aafdb7238f3c5af84a0e8/primitives/core/src/lib.rs#L400
- Also increase the `HeadsQty` to 23 as it is in substrate implementation
https://github.com/paritytech/substrate/blob/2ca66197161b3b5c4e2aafdb7238f3c5af84a0e8/client/allocator/src/freeing_bump.rs#L288C1-L288C1
This fixes the following error while syncing
N/A
N/A
@dimartiro
=> fix(lib/runtime): update `MaxPossibleAllocation` to `2^25`

chain/westend/defaults.go, cmd/gossamer/commands/utils.go
Fixes `parseLogLevel` method in the CLI.
closes #3403 
=> fix/cli: use default log values from config

lib/utils/lru-cache/lru_cache.go, lib/utils/lru-cache/lru_cache_test.go
Implements LRUCache. 
It is being used in disputes-subsystem and few other places in the polkadot code. This is the crate polkadot is using https://docs.rs/lru/latest/lru/.
```sh
go test ./...
```
@timwu20
=> feat/utils: lru cache

dot/state/grandpa.go, dot/state/grandpa_test.go, dot/state/service_integration_test.go, dot/state/slot_test.go, dot/state/test_helpers.go, lib/grandpa/grandpa.go, lib/grandpa/grandpa_integration_test.go
- Removes `findParentWithNumber` since it is not being used by the production code
- Unblocks https://github.com/ChainSafe/gossamer/pull/3434
```sh
```
@dimartiro
=> chore(deepsource): address Deepsource suggestions

dot/parachain/dispute/queue_test.go, dot/parachain/dispute/queues.go, go.mod, go.sum
- Implements the queues needed for dispute participation
read the note on `queue.go` for more details.
#3302 
=> parachain/disputes: add participation queue for dispute-coordinator

lib/runtime/wazero/instance.go
Our current implementation fails if we don't export all runtime functions declared in polkadot runtime.
I made this change to add new exported functions and fix failing tests [due our last runtime changes](https://github.com/ChainSafe/polkadot-spec/pull/17) used for tests
This will be fixed with the right implementation after merging #3428 (only for the same functions)
We can discuss what to do to prevent issues in case a new function is added in polkadot runtime and we don't have it exported
```sh
make test
```
=> fix(tests): Export unimplemented runtime fuctions

dot/rpc/modules/state_integration_test.go, lib/runtime/constants.go, lib/runtime/wazero/imports_test.go, lib/trie/child_storage.go
- When the runtime tries to set a key/value in the child trie and it does not exist then it was failing with
```
child trie does not exist at key 0x...
```
- After the fix, if the child trie does not exist Gossamer creates a fresh new empty trie, insert key and value and persists it in the root trie
```sh
go test -timeout 10m -run ^Test_ext_default_child_storage_set_version_1$ github.com/ChainSafe/gossamer/lib/runtime/wazero --tags=integration -v
```
- Closes https://github.com/ChainSafe/gossamer/issues/3458
- Related https://github.com/ChainSafe/gossamer/issues/3409
@kanishkatn
@dimartiro
=> fix(lib/trie): create an empty child trie if not found

dot/node.go, dot/node_integration_test.go
`builder.isNodeInitialised` returns a boolean after checking if the base path is there with important files, meaning that the node is already initialized. However, Gossamer re-initialize the node if `isInitialized == true` which is not the intended behavior
N/A
N/A
@dimartiro
=> chore: only initialize if it is not initialized

lib/runtime/wazero/imports.go, lib/runtime/wazero/imports_test.go, lib/trie/child_storage.go, lib/trie/child_storage_test.go
- This PR fixes the issue `Storage root must match that calculated` described at https://github.com/ChainSafe/gossamer/issues/3478
- Full description https://hackmd.io/@-8f0KkDaSXGl-AgsJkF8Jg/rJy08gWya
```
go test -run ^TestChildTrieHashAfterClear$ github.com/ChainSafe/gossamer/lib/trie --tags=integration -v
```
- Closes https://github.com/ChainSafe/gossamer/issues/3478
@dimartiro
=> fix(lib/trie): `ClearFromChild` should update parent trie

pkg/scale/decode.go, pkg/scale/decode_test.go, pkg/scale/encode.go, pkg/scale/encode_test.go
- Introduces `scale.Marshaler` and `scale.Unmarshaler` interface to enable custom encoding and decoding for provided types.
- Similar to `json/encoding` analogous interfaces, but `scale.Unmarshaler` takes in a `io.Reader` instead of `[]byte` due to the nature of SCALE encoded data and that the shape of the data is unknown until the destination type is known.
```sh
```
closes #3558 
@jimjbrettj
=> feat(pkg/scale): Add `Marshaler` and `Unmarshaler` interfaces and functionality

dot/parachain/overseer/overseer.go, dot/parachain/overseer/overseer_test.go
- If we close overseerToSub1, subsystem2 could still send a message for subsystem1 via subsystemToOverseer, and it will be panic.
- we can close overseerToSubsystem channels only if the subsystemToOverseer channel is closed.
IMO, we should not close either of them.
That is why I removed the code to close overseerToSubsystem channels.
Used a `waitGroup` in the test to wait till we received all the messages in mocked subsystems before we called the stop function of overseer. 
```sh
```
closes #3717
@kishansagathiya @EclesioMeloJunior
=> chore(dot/parachain/overseer): fix `TestHandleBlockEvents` the flaky test

dot/state/storage_notify.go
```sh
```
Fixes #3477
@axaysagathiya @jimjbrettj
=> fix: don't panic if we fail to convert hex to bytes

docs/docs/contributing.md
Changing `Polkadot Runtime Specification` hiperlink  and adding a target so that it opens a new tab with the link instead of refreshing your active one
Current one is not working and it's refreshing the current tab instead of opening a new tab with the link
Click`Polkadot Runtime Specification` hiperlink and see if the link is not broken and it's opening a new tab instead of refreshing the page.
The hiperlink should open a new tab with [this page ](https://spec.polkadot.network/id-polkadot-protocol)
No active issues related to this one.
@jimjbrettj
=> fix(docs): Fixing link to polkadot runtime fundamentals to the right one
