- .circleci/config.yml
- .gitignore
- README.md
- codec/helpers_test.go
-  Added gofmt
-  Added golangci-lint
Run circleci locally to test:
```
circleci local execute
```
- Fixed broken working path
- Fix broken test command
> CircleCI Update

- .circleci/config.yml
Circle CI should work
- Changed to default working_directory
- Set checkout to default working_directory
- Removed redundant attach_workspace
```
circleci local execute
```
- Broken test signal kill
> circleci patch

- trie/codec.go
- trie/codec_test.go
- Implements KeyEncode and tests
```
go test -v ./trie/codec_test.go ./trie/codec.go
```
> Implements KeyEncode and tests

- codec/decode.go
- codec/encode.go
These fields need to be exported so we can pass the underlying reader/writer at initialization
- Exports `Writer` field of `Encoder`
- Exports `Reader` field of `Decoder`
```
go test -v ./codec/...
```
> Export reader and writer

- Makefile
- Swapped out gometalinter install and linter for golangci-lint 
- Added the --enable gofmt and goimports to linter command
- 
```
make lint
```
> Updated makefile to reflect golangci linter

- README.md
- Fixes test coverage badge
```
N/A
```
> Updates test coverage badge

- .github/PULL_REQUEST_TEMPLATE.md
- Clarifies how to tag issues
```
N/A
```
> Updates issue instructions

- cmd/gossamer/configcmd.go
- cmd/gossamer/main.go
Added a `dumpconfig` command to the CLI
- Added `dumpconfig` command to CLI that outputs the configurations set
- Added a `tomlSettings` func  to ensure the TOML keys use the names as Go struct fields to avoid unnecessary errors
- 
```
make gossamer
gossamer dumpconfig 
OR
gossamer --config config.toml dumpconfig
```
> Dump Config Command

- polkadb/database.go
- polkadb/database_test.go
- For tests that are running multiple tests in a single test function added t.Run in `/polkadb`
- 
- 
```
go test ./polkadb 
```
> Test improvement

- cmd/gossamer/configcmd.go
- cmd/gossamer/main.go
- go.mod
- go.sum
- Pass updated config object to dumpConfig command
- Set datadir in config object if exists in cli context
- return config object in `makeNode` func
```
make gossamer
gossamer --config config.toml --datadir chaingang --rpchost localman dumpconfig
```
closes #157
> Dumpconfig Fix closes #157

- .travis.yml
- scripts/ci.sh
- Use latest Go patch version
- Remove failing test data from cache
- Migrate script commands to an actual script
```
See Travis.
```
> Update CI Config

- scripts/ci.sh
The verbosity flag shouldn't be used with Travis, makes the logs far too long and will cause Travis to fail.
`
The job exceeded the maximum log length, and has been terminated.`
- Removes `-v` flag from ci script
- 
- 
```
```
> removes verbosity flag

- .travis.yml
This should hopefully fix the issue with PRs from forks. 
- Adds CodeClimate test coverage reporting key to travis config
```
N/A
```
> Adds CodeClimate Key to Travis Config (removed from repo settings)

- LICENSE
- README.md
See ya later GPL
Ps: Your header files were already LPGL
> “L” + “GPL” Day

- README.md
- Update broken link in Readme for PRE spec
```
N/A
```
N/A
> Update broken link in Readme for PRE spec

- cmd/gossamer/configcmd.go
- cmd/gossamer/configcmd_test.go
- cmd/gossamer/main.go
- cmd/netsim/sim.go
- cmd/utils/flags.go
- config/defaults.go
- go.mod
- p2p/bootstrap.go
- p2p/config.go
- p2p/p2p.go
- polkadb/blockDB.go
- polkadb/database.go
- polkadb/dbService.go
- polkadb/stateDB.go
- Adds `--rpcport`, `--nobootstrap` and `--bootnodes` flags to CLI
- Disables badger logging
- Cleanup level and format of some p2p logs
- Remove excess logs on DB failure
- Moves p2p config to separate file
```
go test -v ./configcmd
```
> cmd,config,p2p: Minor Fixes

- cmd/gossamer/configcmd.go
- common/optional/types.go
- common/transaction/priority_queue.go
- common/transaction/priority_queue_test.go
- common/transaction/types.go
- core/runtime.go
- p2p/config.go
- polkadb/blockDB.go
- polkadb/dbService.go
- polkadb/dbService_test.go
- polkadb/stateDB.go
- polkadb/table.go
- polkadb/table_test.go
- Added missing license header to files
- 
- 
```
```
> Added license header to missing files

- polkadb/database_test.go
- polkadb/table_test.go
Significant speedup on test suite, not really necessary to test this so intensively.
- Reduce batch tests sizes by a factor of 10
```
go test ./polkadb
```
> Reduce DB Test Iterations

- runtime/imports.go
- Reduces general logs to trace level
- `ext_print_*` messages are debug level (only the actual message) 
- Swap return values for `ext_secp256k1_ecdsa_recover` to match rust impl.
```
go test -v ./runtime
```
> runtime: Runtime Logs

- p2p/config.go
- Changes p2p key generation to use default ECDSA keys (seems to match the expected id form)
- Use hex encoding before writing to file to maintain readability
```
go test -v ./p2p
```
> Change P2P Key Type & Encoding

- crypto/ed25519.go
- crypto/ed25519_test.go
- crypto/keypair.go
- crypto/sr25519.go
- crypto/sr25519_test.go
- go.mod
- go.sum
- runtime/imports.go
- add sr25519 key types, key generation/importing, encode, decode, sign and verify 
```
go test ./crypto/...
```
closes #171
> crypto: add sr25519 keypair, sign, verify functions

- p2p/config_test.go
- p2p/p2p_test.go
This pull request refactors and adds checks to the p2p package tests.
```
```
> p2p: refactor and add checks to p2p tests

- scripts/ci.sh
*Note: CI will be skipped for this PR to avoid false positives on other PRs*
- Causes script to exit with non-zero code if a test fails
```
N/A
```
> CI: Exit on failure

- runtime/wasmer_test.go
- scripts/ci.sh
- Removed race condition test for runtime in ci.sh
```
```
#438
> scripts: Daniel/remove runtime race detection

- runtime/allocator/allocator.go
- runtime/allocator/allocator_test.go
- Removed not needed logging in allocator_test.go 
- Changed logging in allocator.go to Trace level
- 
```
go test -v ./runtime/allocator/
```
closes #361
> allocator: Update alloctator logs

- go.mod
- go.sum
- p2p/config.go
- p2p/connmgr.go
- p2p/host.go
- p2p/p2p.go
- p2p/p2p_test.go
This pull request adds the foundation for the status message exchange between host and connected peer that will determine if the two nodes are compatible or if the peer should be dropped.
This pull request also includes some formatting, updated comments, and some added logging.
```
```
closes #325
> p2p: add foundation for status message exchange

- cmd/gossamer/configcmd.go
- consensus/babe/babe_test.go
- core/service_test.go
- runtime/imports.go
- runtime/interface.go
- runtime/wasmer.go
- runtime/wasmer_test.go
- state/service.go
- state/storage.go
- Refactor to update references to `trie.Trie` to `state.StorageState`
```
go test -v ./...
```
closes #458
> runtime, state, core, consensus, cmd: Migrate runtime calls

- core/service.go
- p2p/discovery.go
- p2p/host.go
- p2p/p2p.go
- p2p/status.go
- p2p/status_test.go
- p2p/types.go
This pull request adds status message validation and status message expiration.
```
```
closes #444
> core, p2p: status validation and expiration

- go.sum
- p2p/config.go
- p2p/config_test.go
- p2p/gossip.go
- p2p/gossip_test.go
- p2p/host.go
- p2p/host_test.go
- p2p/mdns.go
- p2p/mdns_test.go
- p2p/service.go
- p2p/service_test.go
- p2p/status.go
- p2p/status_test.go
- p2p/types.go
- p2p/utils.go
- p2p/utils_test.go
This pull request updates the p2p service configuration and updates host startup and methods.
```
```
> p2p: update configuration and host

- dot/core/state.go
- dot/state/block.go
- lib/babe/babe.go
- lib/babe/state.go
- persistence was broken probably by updating the DB, this fixes it by storing the latest block hash at a known key in the db
```
make gossamer
./bin/gossamer
```
stop and restart the node, block production should start off where it left off
> state: fix persistence

- cmd/gossamer/genesis.go
- cmd/gossamer/main.go
- initialize node if the node has not been initialized
- refactor node initialization method (break up into smaller parts and add comments)
```
make gossamer
```
```
./bin/gossamer --datadir tmp/alice --key alice
```
> cmd: initialize node if not initialized

- cmd/gossamer/configcmd.go
- cmd/gossamer/configcmd_test.go
- cmd/gossamer/flags.go
- dot/config.go
- dot/config_test.go
- dot/network/config.go
- dot/network/config_test.go
- dot/network/gossip_test.go
- dot/network/host_test.go
- dot/network/mdns.go
- dot/network/mdns_test.go
- dot/network/service.go
- dot/network/service_test.go
- dot/network/status_test.go
- dot/network/sync_test.go
- node/gssmr/defaults.go
- node/ksmcc/defaults.go
- update all uses of `Mdns` to `MDNS`
> network: update mdns format

- dot/network/service_test.go
- dot/state/service.go
- fix db error upon node startup
- fix hanging network tests
```
```
> network, state: fixes

- dot/network/service.go
- dot/network/state.go
- dot/network/state_test.go
- dot/rpc/modules/api.go
- dot/rpc/modules/system.go
- dot/rpc/modules/system_test.go
- dot/state/network.go
- dot/state/network_test.go
- dot/state/service.go
- remove use of database from network state
- update network state every minute (or other set time)
```
go test dot/network -v
```
closes #619
> network, state: remove network state db

- README.md
- fix assets path in README after merging #734
> docs: fix assets path in README

- cmd/gossamer/main.go
- dot/node.go
- dot/node_test.go
- lib/database/database.go
- lib/database/table.go
- check if gensis data has been loaded when checking if node has been initialized
- minor cleanup including the removal of the database log for successfully closed
```
```
closes #688, closes #418
> dot, lib/database: improve node initialized check

- lib/babe/build_test.go
- retry if unsuccessful in createTestBlock, should fix test errs
```
go test ./lib/babe
```
> lib/babe: fix createTestBlock err

- .travis.yml
- fix travis to deploy to `gh-pages` on successful `development` branch build
> deploy gossamer docs with github pages

- .travis.yml
- GitHub will build the docs site for us, this pull request removes the build steps from the travis configuration letting GitHub handle the build process
- See https://docs.travis-ci.com/user/deployment/pages/
> fix gossamer docs deploy configuration

- lib/grandpa/errors.go
- lib/grandpa/grandpa.go
- lib/grandpa/grandpa_test.go
- lib/grandpa/round_test.go
- lib/grandpa/types.go
- lib/grandpa/vote_message_test.go
- implement `initiate`, `determinePreVote`, `determinePreCommit`, `isFinalizable`, `finalize` 
- these are the non-timing/message based components from play-grandpa-round
```
```
- closes #911
> grandpa: implement round logic

- lib/grandpa/grandpa.go
- lib/grandpa/round_test.go
- lib/grandpa/vote_message.go
- add channel buffer to tests to fix stalling
- update comments
-
```
```
-
> grandpa: add channel buffer to tests, update comments

- lib/scale/enc_dec_test.go
- lib/scale/encode.go
- lib/scale/encode_test.go
- fix big.Int encoding issue
- add test cases
```
go test ./lib/scale -short
```
- closes #931
> lib/scale: fix big.Int encoding, add tests

- dot/core/syncer.go
- lib/babe/babe.go
- lib/grandpa/vote_message.go
- lib/runtime/imports_old.go
- cleanup some logs
- increase syncer timeout
```
go test ./...
```
-
> cleanup logs

- dot/config_test.go
- remove tests that overwrite config since they should be covered by `TestExportConfig`
```
go test ./...
```
- closes #987
> dot: remove tests that overwrite config

- .travis.yml
- Dockerfile.dev
- tests/stress/grandpa_test.go
- tests/stress/stress_test.go
- tests/utils/config_babe_max_threshold.toml
- tests/utils/config_log_grandpa.toml
- tests/utils/gossamer_utils.go
- update test node basepaths to be placed in <gossamer-dir>/tests/test_data/<test-name>/<node-name>
- update node stdout to be saved in `<basepath>/log.out` and stderr to be saved in `<basepath>/error.out`
```
make it-stress 
```
-
> tests: improve logging, basepath directories

- Makefile
- rename `install` -> `deps` since it installs dependencies
- update `init` and `start` to work with node
- add `install` to install binary in `/usr/local/bin`
```
make init
make start
make install
```
- closes #995
> update Makefile, add install command

- dot/network/gossip_test.go
- dot/network/host.go
- go.mod
- go.sum
- add noise support to network (still supports secio)
```
go test ./dot/network
```
- closes #1009
> dot/network: add noise support

- .travis.yml
- Makefile
- cmd/gossamer/main.go
- tests/stress/grandpa_test.go
- tests/stress/stress_test.go
- separate `TestSync_*` and `TestStress_Grandpa_*` into separate jobs
```
make it-stress
make it-grandpa
```
-
> separate grandpa and sync tests in CI

- dot/core/service.go
- dot/core/service_test.go
- lib/grandpa/round_test.go
- lib/grandpa/vote_message_test.go
- add channel for added blocks to core
- watch this channel for new blocks, check for runtime changes using that
```
go test ./dot/core
```
- closes #1014
> dot/core: check for runtime changes used block added channel

- .travis.yml
- bump travis to go1.15
```
```
-
> bump travis to go1.15

- dot/interface.go
- dot/rpc/modules/api.go
- dot/rpc/modules/dev.go
- dot/rpc/modules/dev_test.go
- dot/services.go
- dot/sync/syncer_test.go
- lib/babe/babe.go
- lib/babe/babe_test.go
- lib/babe/build_test.go
- lib/babe/epoch.go
- lib/babe/inherents_test.go
- lib/babe/median_test.go
- lib/babe/verify_test.go
-  rename EpochThreshold to Threshold
-  check for threshold changes on BABE runtime change
```
```
- closes #1057
> lib/babe: rename EpochThreshold to Threshold, check for threshold changes on runtime change

- dot/sync/syncer_test.go
- go.sum
- lib/transaction/priority_queue.go
- Implement priority queue using a heap.
```
Unit tests
```
- [] I have reviewed my own pull request before requesting a review
- [] All integration tests and required coverage checks are passing
- closes #302 
- closes #674
> Implement priority queue using heap.

- README.md
- Update readme as requested by @GregTheGreek 
```
```
-
> Update README.md with security policy

- dot/network/light.go
- dot/network/message.go
- dot/network/service.go
- dot/network/service_test.go
- lib/scale/encode.go
- Add a handler for light request and response and surrounding APIs
```
```
- closes #1157
> Add handler for light request and response.

- dot/core/test_helpers.go
- dot/network/service.go
- dot/network/service_test.go
- dot/network/state.go
- dot/network/test_helpers.go
- dot/rpc/modules/system_test.go
- dot/sync/syncer.go
- Added a `GetSyncedState` to the Syncer interface
- Updated `Health()` to call `GetSyncedState`
`dot/network/service_test.go: TestService_Health`
closes #700
> Implement IsSyncing in Health check function

- dot/services.go
- lib/runtime/wasmtime/imports.go
- lib/runtime/wasmtime/instance.go
- lib/runtime/wasmtime/legacy_imports.go
- lib/runtime/wasmtime/test_helpers.go
- Match Wasmtime imports by name using `Linker`
```
```
- #1165
> Match wasmtime imports by name

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/general_report.md
- .github/ISSUE_TEMPLATE/task_report.md
- .github/workflows/tests.yml
- codeclimate.yml
- Adds `codeclimate.yml` which disables some checks we are not using see [code climate issues here](https://codeclimate.com/github/ChainSafe/gossamer/issues). This config can be updated for future use.  
- Adds three distinct issue templates for bug reporting, task report and general reporting as well as, a config which outlines communication channels for the project 
- Changes code coverage report to utilize ubuntu-latest rather than macos  
```
```
- Closes #860
> Adds code climate cfg & issue templates

- .github/workflows/tests.yml
- Update ci to use local docker image to run tests
-
-
```
```
-
> Update ci to use local docker image to run tests

- dot/rpc/modules/dev.go
- tests/stress/stress_test.go
- tests/utils/dev.go
- fix time, test was previously not converting the SlotDuration to milliseconds properly, was sleeping for nanoseconds instead
- skip test for now since it takes over 10min to run
```
make it-stress
```
- related to #1026
> tests: fix multi-epoch test time

- dot/core/interface.go
- dot/core/service.go
- dot/core/test_helpers.go
- dot/network/host.go
- dot/network/sync.go
- dot/services.go
- dot/sync/syncer.go
- dot/sync/syncer_test.go
- lib/babe/babe.go
- lib/babe/verify.go
- lib/babe/verify_test.go
- syncer improvements: begin requests from head of chain + 1
- skip BABE authorship right calculation for now
- small network fix with BlockResponse handling
please see instructions here https://github.com/ChainSafe/gossamer/pull/1312
> syncer improvements, skip BABE authorship right calculation for now

- lib/babe/babe.go
- lib/babe/build_test.go
- lib/babe/crypto.go
- lib/babe/verify.go
- lib/babe/verify_test.go
- lib/common/types/uint128.go
- re-add VRF proof verification (not sure why this didn't work friday and works today...)
please see instructions here https://github.com/ChainSafe/gossamer/pull/1312
- closes #1320
> lib/babe: re-add VRF proof verification

- dot/sync/syncer.go
- dot/sync/syncer_test.go
- re-add block body handling (it no longer panics for me, even though nothing was changed? maybe the issue was something else?)
could everyone please try instructions here https://github.com/ChainSafe/gossamer/pull/1312 and sync a couple blocks to make sure my computer and I are not going crazy lol
- closes #1322
> dot/syncer: re-add block body handling

- dot/state/storage.go
- dot/state/storage_notify.go
- dot/state/storage_notify_test.go
- dot/state/storage_test.go
- dot/sync/syncer.go
- lib/common/types/uint128.go
- lib/runtime/storage/trie.go
- add TODO comments
- make digest handling async
- make writing state trie after executing block async
- 1 block now takes ~13s
```
```
-
> optimizations: add TODOs, make some functionality async

- dot/sync/syncer_test.go
- lib/runtime/storage/trie.go
- lib/trie/trie.go
- lib/trie/trie_test.go
- tests/utils/gossamer_utils.go
- Implement delete and clear prefix for versioned trie.
```
trie/trie_test.go
```
- #1349
> Implement delete and clear prefix for versioned trie.

- dot/state/storage.go
- fix node restart issue, was due to bad locking (idk how it even restarted ever :/)
```
git fetch
git checkout noot/fix-restart
make gossamer
./bin/gossamer --chain ksmcc --bootnodes /ip4/3.235.193.225/tcp/30333/p2p/12D3KooWLLvGJZWF7z6KaCw6CPPbPkccrkCHmQBch27vtfngcZki
```
let node run for a bit, restart it, make sure it doesn't hang when started up anymore
- closes #1382
> fix lock issue in StorageState, fixes restart issue

- README.md
- dot/network/host.go
- update README
- cleanup network bootstrap logs
n/a
-
> README update, cleanup network bootstrap logs

- dot/core/digest.go
- dot/core/messages.go
- dot/core/service.go
- dot/network/block_announce.go
- dot/rpc/modules/author.go
- dot/sync/syncer.go
- lib/babe/verify.go
- lib/runtime/wasmer/instance.go
- remove unneeded map access that was causing concurrent map read/write err
```
```
-
> dot/network: remove unneeded map access, sync fixes

- docs/pages/Developer_Resources.md
- Updated broken links from developer resource page
-
-
```
```
-
> update broken links

- dot/network/block_announce_test.go
- dot/network/connmgr_test.go
- dot/network/gossip_test.go
- dot/network/host.go
- dot/network/host_test.go
- dot/network/mdns_test.go
- dot/network/notifications_test.go
- dot/network/service_test.go
- dot/network/transaction_test.go
- go.mod
- go.sum
- lib/utils/test_utils.go
- Implement persistent peerstore.
```
TestPersistPeerStore
```
- closes #1368
> Implement persistent peerstore.

- dot/network/host.go
- go.mod
- go.sum
-  Fix protobuf error due to badger.
```
```
-
> Fix protobuf error due to badger.

- dot/network/sync.go
- dot/network/sync_benchmark.go
- dot/network/sync_test.go
- fix a few edge cases where the node sometimes stops requesting, update them to correct push to the request queue 
```
./bin/gossamer --chain ksmcc
```
> dot/network: small sync fixes 

- README.md
- Fix coverage badge in README
-
-
```
```
-
> chore: README: fix coverage badge

- cmd/gossamer/main.go
- update cli version to 0.3.2
```
n/a
```
- closes #1473
> chore: update cli version

- dot/network/sync.go
- forgot to remove this log in the previous PR
```
n/a
```
- related to #1491
> fix(dot/network): remove log

- .github/CODEOWNERS
- update code owners file
-
-
```
```
-
> chore(codeowners): update codeowners file

- .github/workflows/release.yml
- remove development from release flow
-
-
```
```
-
> chore(.github): remove development from release flow

- .github/workflows/tests.yml
- Given we are a public repo we dont need a codecov token
-
-
```
```
- Closes #1541
> chore:remove codecov token

- docs/docs/integrate/connect-to-polkadot-js.md
- fix image paths for integrate docs page
-
-
```
```
-
> chore(docs): fix image paths for integrate docs page

- package.json
- `package.json` overrides the release config from `.releaserc`
- Source: [Semantic Release Configuration](https://semantic-release.gitbook.io/semantic-release/usage/configuration)
```
```
-
> fix(release): Trigger release when pushed to main branch.

- docs/docs/contributing.md
- docs/docs/getting-started/overview/host-architecture.md
- docs/docs/getting-started/resources/general-resources.md
- docs/docs/usage/command-line.md
- fix block production path and add article links
-
-
```
```
-
> chore: fix block production path and add article links

- dot/network/utils_test.go
- go.sum
- Add test for leb128 to uint86 conversion.
```
readLEB128ToUint64
```
-
> chore(dot/network): Add test for leb128 to uint86 conversion.

- dot/network/stream_manager_test.go
- fix stream manager test cases that failed occasionally
```
go test ./dot/network/ -run TestStreamManager
```
- n/a
> fix(dot/network): fix stream manager tests

- .github/CODEOWNERS
- add @jimjbrettj to codeowners
> maintainence: add Jimmy to codeowners

- .github/PULL_REQUEST_TEMPLATE.md
- updated pr template to include primary reviewer
-
-
```
```
-
> chore: updated pr template to include primary reviewer

- lib/babe/verify.go
- fix error log
```
n/a
```
- n/a
-  @EclesioMeloJunior
> fix(lib/babe): fix error log 

- .github/dependabot.yml
- Add dependabot configuration for Go, Docker and Github Actions
> chore(dependabot): Add dependabot configuration for Go, Docker and Github Actions

- .github/CONTRIBUTING.md
- Document `make license` in .github/CONTRIBUTING.md
- My apologies I got too Squash'n'merge happy on the copyright PR and forgot to document
> docs(contributing): document `make license` in contributing document

- .github/workflows/build.yml
- .github/workflows/code-cov.yml
- .github/workflows/docker-grandpa.yml
- .github/workflows/docker-js.yml
- .github/workflows/docker-rpc.yml
- .github/workflows/docker-stable.yml
- .github/workflows/docker-stress.yml
- .github/workflows/docs.yml
- .github/workflows/staging.yml
- .github/workflows/unit-tests.yml
- Autoformat YML CI configuration files
- I'll eventually fiddle with workflows soon after this gets merged, to make the CI quicker
> chore(ci): auto format Github workflow files

- .dockerignore
- Dockerfile.staging
- Staging branch workflow was broken by another commit
- push to staging and ensure Kusama and Polkadot nodes are deployed
-
- @qdm12
> fix: Staging CI workflow

- README.md
- docs/docs/getting-started/installation.md
- update go version in readme to 1.17
```
n/a
```
- n/a
- @qdm12
> maintenance(docs): update go version in readme

- README.md
- Add a troubleshooting subtopic for apple silicon users inside `Installation` topic
- @1garo got problems while executing `make build`, so the problem was fixed setting new values to golang enviroment variables
```
N/A
```
- N/A
- @danforbes
> chore(docs): troubleshooting to apple sillicon

- .github/workflows/release.yml
> bug(ci): fix release workflow

- dot/network/host.go
> fix(dot/network): public IP address logging

- codecov.yml
These changes are done following the test plan document writing;
- @timwu20
> chore(codecov): change codecov.yml

- cmd/gossamer/config.go
- cmd/gossamer/config_test.go
- cmd/gossamer/flags.go
- cmd/gossamer/utils.go
- dot/config.go
- dot/config/toml/config.go
- dot/digest/digest.go
- dot/digest/digest_test.go
- dot/node.go
- dot/services.go
- dot/services_test.go
- add `--log-digest` flag to set dot/digest log level from the command line
```
go test ./cmd/...
```
- closes #1851
- @jimjbrettj
> feature(cmd): add --log-digest flag

- .gitattributes
- Modified .gitattributes to standardize how we format endlines
- @qdm12
> maintainence (gitattributes): Define repo endline settings

- dot/digest/README.md
- Add [README](https://github.com/ChainSafe/gossamer/blob/dfo/doc/digest/dot/digest/README.md) for `dot/digest`
- N/A
- Closes #2109
- @noot
> docs(digest): README

- .github/workflows/checks.yml
> fix(ci): rename lint job from `checks` to `linting`

- lib/trie/trie_test.go
- Simple test addition for DeepCopy to reach full test coverage on trie.go
I often check for 'red' code paths in this file to make sure I cover everything since it's a rather complex source file. And that's the only red path showing up, and I wanted it gone since I would check it every time.
```
go test ./lib/trie/...
```
> chore(lib/trie): add Trie `DeepCopy` unit test

- .github/CODE_STYLE.md
- Describe how mocks should be configured in subtests
- Describe exception where for loop / test cases should be broken in individual subtests
- @jimjbrettj @timwu20
> docs(codestyle): mocks configuration in subtests

- .github/workflows/fuzz.yml
- lib/trie/trie_endtoend_test.go
- Change one unit test to a fuzz test
- Add CI workflow
```
go test -fuzz=Fuzz_Trie_PutAndGet -fuzztime=10s github.com/ChainSafe/gossamer/lib/trie
```
- #2087 
- Anyone :tada:
> chore(trie): fuzz test for Put and Get

- docs/docs/getting-started/resources/general-resources.md
links to [this video](https://www.youtube.com/watch?v=ZIS0eLtBA9E)
```sh
```
Closes #2124
@timwu20
> [docs] fix copy pasta, link to video

- lib/babe/verify.go
- Check for negative numbers after casting a value to `int`
N/A
- Closes #2415
@jimjbrettj
> fix(lib/babe): check if authority index is in the `authorities` range

- lib/runtime/wasmer/imports_test.go
Fix bad sort in `Test_ext_crypto_ed25519_public_keys_version_1`
- Fixes #2160 
> fix(tests): Fix wasmer flaky sorts

- codecov.yml
- Fix `gossamer` to `project` string
- Add `mocks_*.go` ignore rule
> fix(ci): codecov.yml configuration

- cmd/gossamer/main.go
- Avoid relying on OS time zone data to provide correct times
@jimjbrettj
> feat(build): binary built-in timezone data

- Makefile
- dot/digest/digest_test.go
- dot/peerset/peerset_test.go
- dot/state/grandpa.go
- dot/state/grandpa_test.go
- dot/sync/message_integration_test.go
- internal/httpserver/option_test.go
- internal/httpserver/options.go
- internal/httpserver/run.go
- internal/httpserver/server_test.go
- lib/grandpa/round_test.go
- lib/grandpa/votes_tracker_test.go
- lib/trie/proof/generate_test.go
- lib/trie/trie_endtoend_test.go
- tests/rpc/rpc_03-chain_test.go
- tests/stress/grandpa_test.go
- tests/stress/helpers.go
- tests/stress/stress_test.go
- Bump version in Makefile
- Fix lint errors in code
@timwu20
> chore(lint): upgrade golangci-lint to v1.47

- .deepsource.toml
- Fix: add `cgo_enabled = true`
- Rename `import_paths` to `import_root`
- Update exclude patterns
- Remove `scripts/**/*`
- Only ignore json files in `chain/`
- Do not ignore `dot/config`
- Ignore all `test_data` directories
- Do not ignore test files
- Add link to deepsource documentation
Deepsource workflow passing (tested for failure as well)
@jimjbrettj
> fix(ci): deepsource toml configuration

- lib/runtime/wasmer/imports.go
Just because I saw some ugly error logs in the CI in another branch.
> fix(wasmer): error logs for signature verification

- dot/core/service.go
- dot/rpc/modules/state.go
- dot/state/storage_notify.go
- lib/babe/babe.go
- lib/crypto/keypair.go
> chore(all): add leading space in exported comments

- dot/core/service_test.go
- lib/runtime/wasmer/imports_test.go
Pin test case variable in for loop with parallel subtests
@jimjbrettj
> chore(all): fix test cases not pinned

- tests/rpc/rpc_03-chain_test.go
Fixes development branch CI
@timwu20
> fix(tests): fix block body regex in `TestChainRPC`

- dot/core/helpers_test.go
- dot/digest/helpers_test.go
- dot/helpers_test.go
- dot/network/message_test.go
- dot/rpc/helpers_test.go
- dot/rpc/modules/chain_test.go
- dot/rpc/modules/helpers_test.go
- dot/state/helpers_test.go
- dot/state/service_test.go
- dot/state/storage_test.go
- dot/sync/bootstrap_syncer_integration_test.go
- dot/sync/chain_sync_test.go
- dot/sync/syncer.go
- dot/sync/syncer_integration_test.go
- dot/sync/syncer_test.go
- dot/sync/tip_syncer_integration_test.go
- dot/types/block_data_test.go
- dot/types/block_test.go
- dot/types/header.go
- dot/types/header_test.go
- lib/babe/build.go
- lib/babe/build_integration_test.go
- lib/babe/helpers_test.go
- lib/babe/verify_integration_test.go
- lib/grandpa/helpers_test.go
- lib/runtime/wasmer/exports_test.go
- lib/trie/genesis.go
- tests/utils/rpc/header.go
`{ Just a side 5 minutes work }`
@timwu20
> chore(types): `NewHeader` returns no error

- dot/core/service.go
- dot/digest/digest.go
- dot/digest/digest_test.go
- dot/import.go
- dot/import_test.go
- dot/state/epoch.go
- dot/state/grandpa.go
- dot/types/babe.go
- dot/types/babe_digest.go
- dot/types/babe_digest_test.go
- dot/types/digest_test.go
- dot/types/header.go
- lib/babe/errors.go
- lib/babe/verify.go
- lib/grandpa/message.go
- lib/grandpa/network.go
- lib/runtime/invalid_transaction.go
- lib/runtime/transaction_validity.go
- lib/runtime/transaction_validity_test.go
- lib/runtime/unknown_transaction.go
- lib/runtime/wasmer/exports.go
- pkg/scale/README.md
- pkg/scale/errors.go
- pkg/scale/varying_data_type.go
- pkg/scale/varying_data_type_nested_example_test.go
- pkg/scale/varying_data_type_test.go
- tests/stress/stress_test.go
- tests/utils/rpc/request.go
- Return error on the Value() function for varyingDataType
```sh
go test ./pkg/scale
```
#2848
@timwu20
> enhancement(pkg/scale): return error on vdt.Value() call

- dot/sync/test_helpers.go
- dot/types/inherents.go
- dot/types/inherents_test.go
- lib/babe/build.go
- lib/babe/parachain_inherents_test.go
- lib/runtime/test_helpers.go
… add tests against encoded data from rust examples
```sh
```
> revise SetStructInherent and SetInt64Inherent to generic SetInherent

- README.md
Adds KSM address for donations. Reformat donations section.
N/A
N/A 
@timwu20 @danforbes
> chore(readme): Add KSM Address for Donations

- README.md
README changes for 22Q4 release. The rendered document can be seen here https://github.com/ChainSafe/gossamer/blob/dfo/readme/README.md.
@timwu20
> README Changes for 22Q4 Release

- dot/node.go
Spotted when Dan was screen sharing today
This should un-screw error checks and errors returned
@danforbes
> fix(dot): database close error checks

- lib/runtime/wasmer/helpers.go
- lib/runtime/wasmer/imports.go
Just something I thought would be nice whilst reviewing #2873 
It also panics on error when we would previously discard the error (and really we should not).
> chore(wasmer): `nil` helper functions

- lib/grandpa/grandpa.go
- lib/grandpa/message_handler.go
- lib/grandpa/message_handler_integration_test.go
> chore(lib/grandpa): use map set for authority keys for faster lookups

- .github/workflows/build.yml
- .github/workflows/checks.yml
- .github/workflows/copyright.yml
- .github/workflows/devnet.yml
- .github/workflows/docker-grandpa.yml
- .github/workflows/docker-js.yml
- .github/workflows/docker-rpc.yml
- .github/workflows/docker-stress.yml
- .github/workflows/docs.yml
- .github/workflows/fuzz.yml
- .github/workflows/integration-tests.yml
- .github/workflows/mocks.yml
- .github/workflows/release.yml
- .github/workflows/staging.yml
- .github/workflows/unit-tests.yml
uses build jet external runners. should not make any difference (except for speed).
n/a
n/a
n/a
> ci: add more juicy github action runners

- lib/babe/build_integration_test.go
- Rather than use hardcoded values to call buildBlock and trigger an applyExtrinsicError, I rewrote the function to build an invalid extrinsic and manually call applyExtrinsic and assert the returned error
- Opened PR with just one function so it is easier to reason about if this is a valid replacement for reviewers
```sh
go test ./lib/babe --tags=integration
```
#3060
@timwu20
> fix(lib/babe): rewrite TestBuildBlock_failing

- .github/workflows/staging.yml
- .github/workflows/staging/openmetrics.d/westend-conf.yaml
- .github/workflows/staging/westend-taskdef.json
- Adds github to staging github workflow to build, deploy and update running Westend synching node on staging cluster.
- Ensure that the westend synching node is updated when pushing code to `staging` branch.
```sh
```
- closes #2454 
@jimjbrettj
> feat(ci) Westend staging workflow

- dot/peerset/peerstate.go
- dot/types/inherents.go
- lib/babe/epoch_handler.go
- lib/blocktree/blocktree.go
- lib/grandpa/grandpa.go
- lib/trie/helpers_test.go
Just so people are aware of it (credits to Eclesio!)
> chore(all): use `maps.Keys` from `golang.org/x/exp/maps`

- dot/services.go
- dot/sync/chain_processor.go
- dot/sync/chain_sync.go
- dot/sync/chain_sync_test.go
- dot/sync/errors.go
- dot/sync/syncer.go
Add bad blocks validation in sync process to reject blocks contained in the badblocks list
```sh
go test -run ^TestChainSync_validateResponse$ github.com/ChainSafe/gossamer/dot/sync
```
Closes #3202
@timwu20 @EclesioMeloJunior
> feat(sync): Validate bad blocks

- tests/utils/node/node.go
Modify node port in rpc-test to run on macOS
```sh
make it-rpc
```
Closes #3222
@timwu20
> fix(rpc-tests): Fix node port to execute tests on macOS

- Dockerfile
Patch docker build
```sh
docker build ./
```
@timwu20
> fix(ci): fix broken docker build

- .github/CODEOWNERS
- updates the `CODEOWNERS`
@jimjbrettj
> chore(github): update codeowners

- dot/core/service.go
- dot/services.go
- dot/state/initialize.go
- Remove unneeded logs introduced from a previous commit.
```sh
```
@jimjbrettj
> chore(logs): Remove unneeded logs

- cmd/gossamer/commands/root.go
change `--metrics-address` to `--prometheus-port`
```sh
```
@kanishkatn
> fix(cmd/gossamer): update error message

- lib/parachain/collation_protocol.go
- lib/parachain/collation_protocol_test.go
- lib/parachain/statement.go
- lib/parachain/statement_distribution_message.go
- lib/parachain/statement_distribution_message_test.go
- lib/parachain/statement_test.go
added New() method and decode test for below varying data types. 
- statement
- statement distribution message
- collation protocol
- collator protocol message 
```sh
```
@kanishkatn @edwardmack
> chore(lib/parachain): add tests to decode varying data types regarding statement and collation

- lib/runtime/wazero/imports.go
- lib/runtime/wazero/imports_test.go
- lib/runtime/wazero/instance.go
- lib/runtime/wazero/instance_test.go
- lib/trie/trie.go
- Fixes some deepsource issues introduced by the wazero work. 
```sh
```
@jimjbrettj
> chore(lib/runtime): fix deepsource issues in `wazero` implementation

- .golangci.yml
- dot/state/grandpa_changes.go
- dot/state/slot.go
- dot/sync/bootstrap_syncer.go
- dot/sync/tip_syncer.go
- internal/trie/node/decode.go
- lib/grandpa/message_handler.go
Change `nilnil` linter config to not enforce when return value is pointer type.
```sh
```
@jimjbrettj
> chore(ci): update `nilnil` linter config

- Dockerfile
- go.mod
- go.sum
Remove unused wasmer dependency and fix dockerfile for CI builds
```sh
```
> chore(deps): Remove wasmer dep and fix dockerfile

- dot/parachain/service.go
- dot/peerset/constants.go
Also, added enums for common reputation values
```sh
```
@EclesioMeloJunior @axaysagathiya
> Added parachain related reputation values and reasons

- .github/workflows/unit-tests.yml
- go.mod
- go.sum
- pkg/finality-grandpa/README
- pkg/finality-grandpa/bitfield.go
- pkg/finality-grandpa/bitfield_test.go
- pkg/finality-grandpa/bridge_state.go
- pkg/finality-grandpa/bridge_state_test.go
- pkg/finality-grandpa/context.go
- pkg/finality-grandpa/context_test.go
- pkg/finality-grandpa/dummy_chain_test.go
- pkg/finality-grandpa/environment_test.go
- pkg/finality-grandpa/lib.go
- pkg/finality-grandpa/lib_test.go
- pkg/finality-grandpa/logger.go
- pkg/finality-grandpa/past_rounds.go
- pkg/finality-grandpa/report.go
- pkg/finality-grandpa/round.go
- pkg/finality-grandpa/round_test.go
- pkg/finality-grandpa/vote_graph.go
- pkg/finality-grandpa/vote_graph_test.go
- pkg/finality-grandpa/voter.go
- pkg/finality-grandpa/voter_set.go
- pkg/finality-grandpa/voter_set_test.go
- pkg/finality-grandpa/voter_test.go
- pkg/finality-grandpa/voting_round.go
- pkg/finality-grandpa/weights.go
- Standalone `finality-grandpa` package which was translated from parity `finality-grandpa` crate.
```sh
go test github.com/ChainSafe/gossamer/pkg/finality-grandpa
```
@jimjbrettj
> lib(pkg): standalone `finality-grandpa` package

- .github/CODEOWNERS
> chore: add Axay to code owners

- dot/parachain/availability-store/availabilitystore.go
- dot/parachain/backing/candidate_backing.go
- dot/parachain/collator-protocol/validator_side.go
- dot/parachain/overseer/overseer.go
- dot/parachain/overseer/overseer_test.go
- dot/parachain/overseer/types.go
- dot/parachain/types/subsystem_names.go
```sh
```
@axaysagathiya @edwardmack
> feat(parachain/overseer): added message forwarding in overseer

- dot/mock_node_builder_test.go
- dot/node.go
- dot/node_integration_test.go
- dot/parachain/availability-store/availability_store.go
- dot/parachain/availability-store/availability_store_test.go
- dot/parachain/availability-store/availabilitystore.go
- dot/parachain/availability-store/availabilitystore_test.go
- dot/parachain/availability-store/messages.go
- dot/parachain/availability-store/register.go
- dot/parachain/service.go
- dot/services.go
Implement functionality to store and retrieve Availability Data, Candidate Meta Data, and Erasure Chunk Data.
```sh
go test github.com/ChainSafe/gossamer/dot/parachain/availability-store
```
related to #3415 
@kishansagathiya 
@timwu20
> feat(parachain/availabilitystore): implement database store/retrieve

- cmd/gossamer/commands/init.go
> (fix/cli): fixes the init help

- chain/kusama/defaults.go
- chain/polkadot/defaults.go
- chain/westend-dev/defaults.go
- chain/westend-local/default.go
- chain/westend/defaults.go
- cmd/gossamer/commands/root.go
- cmd/gossamer/commands/utils.go
Fixes an issue wherein, the name and id of the node was being overridden by default-config and chain-spec
#3684
> chore/cli: fix node identity

- .github/CODEOWNERS
- updates CODEOWNERS
```sh
```
> chore(.github): update CODEOWNERS

- dot/network/host.go
- go.mod
- go.sum
- internal/pubip/README.md
- internal/pubip/pubip.go
- internal/pubip/pubip_test.go
- Given the minimal amount of code in https://github.com/chyeh/pubip, I got rid of the dependency entirely, removed unneeded code, and updated the APIURIs to remove the nonfunction ones.
- This allows us to get our public IP without the messy logs as well as gets rid of an unmaintained dependency  
Start node and make sure the ugly logs are gone
#3742 3742
@axaysagathiya
> Fix IP error logs

- dot/parachain/availability-store/availability_store.go
- dot/parachain/availability-store/availability_store_test.go
- lib/runtime/wazero/instance_test.go
```sh
```
@kishansagathiya @EclesioMeloJunior
> fix(feat/parachain): resolve rebase-induced bug

- docs/docs/getting-started/installation.md
- pkg/trie/inmemory/in_memory.go
> chore(docs): fix some comments
